### ISSUE TITLE
several live kernels persist in kernel picker in web that don't show on desktop launch

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#10123]
Repro steps

1. start a Jupyter server outside of VS Code
2. launch VS code in web
3. Specify the server from step 1 for connections in VS Code
4. Create a few notebooks using the kernels from that server and run a cell in them
5. Close the notebooks
6. Open a new notebook and select a kernel

Result:
Some of those kernels that were created still show up in web, but not in desktop kernel picker

![image](https://user-images.githubusercontent.com/2019016/170146986-906277b8-be2b-4292-baaa-726907590f92.png)

Setting a breakpoint inside the event handler here never gets hit https://github.com/microsoft/vscode-jupyter/blob/58c47af78b33deed680b99f063a84d39d8b924d7/src/notebooks/controllers/notebookControllerManager.ts#L168 , so perhaps we're not updating the list when we should. Although, those live kernels persist after a reload of vs code, so perhaps that's unrelated

**Comment by DonJayamanne** [comment]
Not following you here.
Are you saying that:
1. launch VS code in desktop (only different compared to the repro steps)
2. start a remote Jupyter server
3. Specify that server for connections in VS Code
4. Create a few notebooks, run cells in them and close the notebooks

Now reload VS Code and you don't see those old kernels (kernels associated with the notebooks you ran)?
Ideally you should, regardless of whether you're on desktop or web.

> Although, those live kernels persist after a reload of vs code, so perhaps that's unrelated

That is by design.

> never gets hit, so perhaps we're not updating the list when we should.

Not following you here. Why are you expecting the list to get updated. Are you expecting the old kernels to vanish?

**Comment by DonJayamanne** [comment]
> never gets hit, so perhaps we're not updating the list 

Oh wait, are you referring to local kernels? 
If that's the case, then that's being tracked here. https://github.com/microsoft/vscode-jupyter/issues/9517
Basically its not supported today, but will be when we enable the https://github.com/microsoft/vscode-jupyter/issues/4573 feature for local kernels (which is bloked on debt work at my end here https://github.com/microsoft/vscode-jupyter/issues/6765).

**Comment by DonJayamanne** [comment]
> There is a difference in what the kernel picker shows in web vs desktop.

Please could you share a screenshot of the desktop, so i know what's different, else its difficult to tell from the issue.

**Comment by amunger** [comment]
well, today desktop has the same amount of unused live kernels. Still not clear to me when they should be dropped from that list

**Comment by rchiodo** [comment]
Remote notebook kernels don't go away until the user closes the server.
