### ISSUE TITLE
Test Variable Viewer in the web

### ISSUE THREAD

**Issue by sadasant** [microsoft/vscode-jupyter#10170]
Refs: #9664

- [x] web @Tyriar
- [x] web @weinand

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-jupyter/issues/new?body=Testing+%2310170%0A%0A&assignees=sadasant)

---

### Requirements

- Install prerelease jupyter extension into http://insiders.vscode.dev
- Have a python environment that you can run jupyter from. (https://jupyter.org/install)
- Be familiar with jupyter notebooks

### Set up

1. Go to a command prompt where you've installed jupyter into a python environment
2. Switch to a folder you're using for testing
3. Run jupyter with the following command `jupyter notebook --no-browser --NotebookApp.allow_origin=*`

### Test Steps

1. Open insiders.vscode.dev and create a new python file
2. Add variables in the python file (Try adding some, and then in another run try adding many different variables).
3. Connet to the jupyter server:
    1. Run the 'Jupyter: Specify jupyter server for connections' command, or use the link from the IW's info message
    2. Pick 'Existing'
    3. Paste the URL from the jupyter notebook server you started in step 3 of the setup
 4. Run the command `Jupyter: Focus on Variables View`.
 5. Run the file with `Juptyer: Run Current File in Interactive Window`.
 6. See that the variables in the Variable View matched the expectations.

Try again with a `.ipynb` file:

1. Open insiders.vscode.dev and create a new `.ipynb` file.
2. Add variables in the python file (Try adding some, and then in another run try adding many different variables).
3. Connet to the jupyter server:
    1. Run the 'Jupyter: Specify jupyter server for connections' command, or use the link from the IW's info message
    2. Pick 'Existing'
    3. Paste the URL from the jupyter notebook server you started in step 3 of the setup
 4. Run the command `Jupyter: Focus on Variables View`.
 5. Run the cells on your file.
 6. See that the variables in the Variable View matched the expectations.

**Comment by weinand** [comment]
@sadasant I cannot find the "Jupyter: Open Variable View" command. All I have is a "Jupyter: Focus on Variables View".

I'm using this version of the Jupyter extension:

<img width="868" alt="CleanShot 2022-05-31 at 17 02 42@2x" src="https://user-images.githubusercontent.com/1898161/171205970-51a54c85-61af-4f60-91f7-989994d0d522.png">

**Comment by sadasant** [comment]
@weinand ”Jupyter: Focus on Variables View” should also open it — let’s try with that one!

Now, “ Jupyter: Open Variable View” should appear. We’ll investigate!

**Comment by weinand** [comment]
@sadasant ”Jupyter: Focus on Variables View” opens the "Jupyter: Variables" view but no contents is shown and the blue progress spinner runs forever...

**Comment by weinand** [comment]
@sadasant the variables view doesn't work for me.
`Jupyter: Run Current File in Interactive Window` works fine and `Jupyter: Focus on Variables View` opens the "Jupyter: Variables" view but no contents is shown and the blue progress spinner runs forever.

I'm on macOS 12.4 and I'm using python 3.10.0 and pip 22.1.2 via pyenv.

**Comment by sadasant** [comment]
Thank you, @weinand ! I'm investigating.

**Comment by Tyriar** [comment]
@sadasant I also see this, don't think I can test continue testing this, here's the console if that's helpful:

<img width="688" alt="Screen Shot 2022-05-31 at 3 44 55 pm" src="https://user-images.githubusercontent.com/2193314/171296083-7ac0190a-46b8-44e4-8625-4b174118ba30.png">

**Comment by sadasant** [comment]
@weinand turns out we haven't published the Variable Viewer! Our build failed on Friday. I'll provide an update soon.

**Comment by sadasant** [comment]
@Tyriar Thank you! Those logs are expected at the moment.

However, it turns out we haven't published the Variable Viewer! Our build failed on Friday.

I'll provide an update soon.

**Comment by sadasant** [comment]
@weinand , @Tyriar we have just published this feature with version `2022.5.1001532360`. I have also confirmed that it works! (At least or me) Please, try again 🙇‍♂️

**Comment by weinand** [comment]
@sadasant yes, with the new version things look much better...

**Comment by EnchanterTim2** [comment]
> @sadasant I also see this, don't think I can test continue testing this, here's the console if that's helpful:

> @weinand turns out we haven't published the Variable Viewer! Our build failed on Friday. I'll provide an update soon.

> @weinand , @Tyriar we have just published this feature with version `2022.5.1001532360`. I have also confirmed that it works! (At least or me) Please, try again 🙇‍♂️


Que vergonha da qualidade do trabalho desse @sadasant. Ele é Brasileiro? Um show de incompetência. 
A @luabud é outra brasileira do time de @python na @microsoft. 
Só entregam um trabalho de baixa qualidade, feito no ~jeitinho~, tudo mal feito, cheio de problemas. 

As extensões Jupyter e Python e Pylance estão todas quebradas, parece um trabalho de amador, um trabalho porco. Um visualizador de variáveis que não funciona, simplesmente não funciona. 

Chegou no nível que o sujeito criou um plano de testes para uma funcionalidade que sequer foi publicada, e mandou dois desenvolvedores @weinand e @tyriar testarem, os fez de palhaços :clown_emoji:! Quando o time do vscode vai intervir na experiência python do vscode, @egamma?

E os usuários que reclamam da qualidade do trabalho são punidos com o bloqueio e expulsãso da comunidade, sem nem serem avisados. 

Tem uma lista gigante de problemas: 

https://github.com/microsoft/vscode-jupyter/issues/10220
https://github.com/microsoft/vscode-jupyter/issues/10222
https://github.com/microsoft/vscode-jupyter/issues/10223
https://github.com/microsoft/vscode-jupyter/issues/10224
https://github.com/microsoft/vscode-jupyter/issues/10226
https://github.com/microsoft/vscode-jupyter/issues/10225
https://github.com/microsoft/vscode-jupyter/issues/10227
https://github.com/microsoft/vscode-jupyter/issues/10228
https://github.com/microsoft/vscode-jupyter/issues/10229
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10231
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10232
https://github.com/microsoft/vscode-jupyter/issues/10233
https://github.com/microsoft/vscode-jupyter/issues/10235
https://github.com/microsoft/vscode-jupyter/issues/10236
https://github.com/microsoft/vscode-jupyter/issues/10237
https://github.com/microsoft/vscode-jupyter/issues/10238
https://github.com/microsoft/vscode-jupyter/issues/10239
https://github.com/microsoft/vscode-jupyter/issues/10240
https://github.com/microsoft/vscode-jupyter/issues/10240
https://github.com/microsoft/vscode-jupyter/issues/10241
https://github.com/microsoft/vscode-jupyter/issues/10241
https://github.com/microsoft/vscode-jupyter/issues/10242
https://github.com/microsoft/vscode-jupyter/issues/10246
https://github.com/microsoft/vscode-jupyter/issues/10244

**Comment by EnchanterTim2** [comment]
@sadasant I also see this, don't think I can test continue testing this, here's the console if that's helpful:

@weinand turns out we haven't published the Variable Viewer! Our build failed on Friday. I'll provide an update soon.

@weinand , @Tyriar we have just published this feature with version 2022.5.1001532360. I have also confirmed that it works! (At least or me) Please, try again 🙇‍♂️

Que vergonha da qualidade do trabalho desse @sadasant. Ele é Brasileiro? Um show de incompetência.
A @luabud é outra brasileira do time de https://github.com/python na https://github.com/microsoft.
Só entregam um trabalho de baixa qualidade, feito no jeitinho, tudo mal feito, cheio de problemas.

As extensões Jupyter e Python e Pylance estão todas quebradas, parece um trabalho de amador, um trabalho porco. Um visualizador de variáveis que não funciona, simplesmente não funciona.

Chegou no nível que o sujeito criou um plano de testes para uma funcionalidade que sequer foi publicada, e mandou dois desenvolvedores @weinand e @Tyriar testarem, os fez de palhaços :clown_emoji:! Quando o time do vscode vai intervir na experiência python do vscode, @egamma?

E os usuários que reclamam da qualidade do trabalho são punidos com o bloqueio e expulsãso da comunidade, sem nem serem avisados.

Tem uma lista gigante de problemas:

https://github.com/microsoft/vscode-jupyter/issues/10220
https://github.com/microsoft/vscode-jupyter/issues/10222
https://github.com/microsoft/vscode-jupyter/issues/10223
https://github.com/microsoft/vscode-jupyter/issues/10224
https://github.com/microsoft/vscode-jupyter/issues/10226
https://github.com/microsoft/vscode-jupyter/issues/10225
https://github.com/microsoft/vscode-jupyter/issues/10227
https://github.com/microsoft/vscode-jupyter/issues/10228
https://github.com/microsoft/vscode-jupyter/issues/10229
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10231
https://github.com/microsoft/vscode-jupyter/issues/10230
https://github.com/microsoft/vscode-jupyter/issues/10232
https://github.com/microsoft/vscode-jupyter/issues/10233
https://github.com/microsoft/vscode-jupyter/issues/10235
https://github.com/microsoft/vscode-jupyter/issues/10236
https://github.com/microsoft/vscode-jupyter/issues/10237
https://github.com/microsoft/vscode-jupyter/issues/10238
https://github.com/microsoft/vscode-jupyter/issues/10239
https://github.com/microsoft/vscode-jupyter/issues/10240
https://github.com/microsoft/vscode-jupyter/issues/10240
https://github.com/microsoft/vscode-jupyter/issues/10241
https://github.com/microsoft/vscode-jupyter/issues/10241
https://github.com/microsoft/vscode-jupyter/issues/10242
https://github.com/microsoft/vscode-jupyter/issues/10246
https://github.com/microsoft/vscode-jupyter/issues/10244

English translation:

Shame on the quality of this @sadasant's work. He's Brazilian? A show of incompetence. @luabud is another Brazilian from the https://github.com/python team at https://github.com/microsoft. They only deliver low quality work, done in the way, all poorly done, full of problems. Jupyter and Python and Pylance extensions are all broken, looks like amateur work. A crappy variable viewer that doesn't work, just doesn't work.
It got to the point where the guy created a test plan for a feature that wasn't even published, and sent two developers @weinand and @Tyriar to test, made them clowns :clown_emoji:! When will the vscode team intervene in the vscode python experience, @egamma?

And users who complain about the quality of the work are punished with blocking and expulsion from the community, without even being warned.

It has a giant list of problems...

Maybe I should mention @brettcannon and @gramster @greazer, actually, bring the team: @sbatten @joaomoreno @rebornix @connor4312 @bpasero @jrieken @mjbvz @alexdima @sandy081

@isidorn @roblourens @aeschli let's bring all the clowns here! @misolori @dbaeumer @kieferrm @lramos15 @TylerLeonhardt @hediet
Let's bring the clown car @lszomoru @deepak1556 Did I forget anyone?

**Comment by EnchanterTim2** [comment]
An illustration of the vscode team debugging the python experience:

![giphy](https://user-images.githubusercontent.com/110574767/182738238-e7ff3211-a1f5-46e5-81e9-2085596ae0da.gif)
 
 

@luabud @weinand @Tyriar @brettcannon and @gramster @greazer @sbatten @joaomoreno @rebornix @connor4312 @bpasero @jrieken @mjbvz @alexdima @sandy081

@isidorn @roblourens @aeschli @misolori @dbaeumer @kieferrm @lramos15 @TylerLeonhardt @hediet
Let's bring the clown car @lszomoru @deepak1556 Did I forget anyone?
