### ISSUE TITLE
Variable viewer: Show variable in data viewer does nothing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#10229]
Testing #10170

Clicking this doesn't do anything for me

<img width="223" alt="Screen Shot 2022-06-01 at 7 22 16 am" src="https://user-images.githubusercontent.com/2193314/171427379-a1d0f803-2bf8-4bbd-ba40-25e7d6d636d3.png">

**Comment by sadasant** [comment]
I'll work on this today! Thank you 👍

**Comment by sadasant** [comment]
@Tyriar we decided to disable this button last week. It should be disabled in the released build as well as in the last available build. What happened is that I wasn't aware how this button related to a feature I couldn't get to during last month, which is: https://github.com/microsoft/vscode-jupyter/issues/9665 -- 9665 is one of my first priorities this week.  That is to say, the underlying issue is indeed scheduled to be accounted for during a milestone, that is June 2022.
