### ISSUE TITLE
Variable viewer: Class value info is shown for expensive getter functions

### ISSUE THREAD

**Issue by pvanschendel** [microsoft/vscode-jupyter#10385]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Unsure if this formally is a bug, but it is definitely bugging me.

The problem that I experience is that mouse hover (and the Variable Viewer) calls the __str__ function on member variables of the class, which in turn call expensive getters. I hope the code below more clearly demonstrates the issue.
When the first cell has been exectuted, the hover shows the text "return value of expensive getter function".

I think these *settings.json* entries might prevent the issue, but they do not:
- "debug.inlineValues": "off",
- "jupyter.showVariableViewWhenDebugging": false,

Can you let me know if this is a bug, or my misunderstanding?

This settings.json entry does work for the code below, but is not really feasible, because we have a lot of  generated classes, so the class names may vary:
- "jupyter.variableExplorerExclude": "module;function;builtin_function_or_method;ABCMeta;type;GetterIssue",

Perhaps a second issue: I would expect hover and Variable View to call `__repr__` rather than `__str__ `.

```python
# %%

class GetterIssue:
    """Class that has an expensive getter property."""
    def __init__(self):
        pass

    def __str__(self):
        return "getter_property: " + self.getter_property

    def __repr__(self):
        return "getter_property: <getter_property(self)>"

    @property
    def getter_property(self):
        """Calling this getter on hover or Variable View is problematic."""
        return "return value of expensive getter function"


# The problem occurs when the cursor hovers over the text 'my_issue' below:
my_issue = GetterIssue()

# %%

print(str(my_issue)) # This is the function I would like to keep
repr(my_issue) # Hacked to not use the getter, probably not generally acceptable
```

### VS Code Version

1.67.2

### Jupyter Extension Version

v2022.4.1021342353

### Language Extension Version (if applicable)

 v2022.6.3

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
@pvanschendel Looping back to check if I'm understanding the issue correctly here. Currently with hover (and variable view) you'd see something like this:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/812783/172919852-8fd47385-b2da-4080-9eef-b0614d8bb96a.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/812783/172919906-c564407d-663b-451e-9daa-9a11eafd1042.png">

From my knowledge of python this is expect, for example when just debugging a .py file (not using Jupyter / interactive window) we see similar:
<img width="824" alt="image" src="https://user-images.githubusercontent.com/812783/172920893-4c0b862e-d1dd-4e86-ac73-22b0fd594bdc.png">

I would think the issue here is that str or repr should not be calling an expensive getter. Am I maybe not getting part of this scenario that you are asking about?

Also, I believe that debugging would expect to show str over repr as that's the expected "reading friendly" representation of the object.

**Comment by pvanschendel** [comment]
Thanks for taking the trouble to check this. It is already good to know that this is expected behavior, so we have to live with it.

What was unexepcted for me is that these calls are (sometimes, when no cached value is available ?) also mode when only editing the code, so not debugging or otherwise running it, so I have to be really careful where to put my cursor, 
I guess my mistake is that, if I implement a special function like __str__, I should be prepared that any editor or other tool may be calling this, not just user code.

**Comment by IanMatthewHuff** [comment]
Yeah, str and repr can be called implicitly, especially by something like a debugger not just directly. In general you don't want them to be slow. This article here might help a bit with understanding them:
https://stackoverflow.com/questions/1436703/what-is-the-difference-between-str-and-repr

**Comment by pvanschendel** [comment]
Thanks, I am a bit wiser again.
