### ISSUE TITLE
Plot Viewer working in web extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#10405]

**Comment by sadasant** [comment]
I was having an issue with the renderers extension during my testing before PR #10881 was merged, where the renderer's activate() function wouldn't be called. However, today I tested with the both the renderers and the Jupiter extension's pre-release versions on the web and things just worked out of the box! 🎉 I'm guessing the issue was really in the approach I was using to test.

https://user-images.githubusercontent.com/417016/180300103-91771e0a-f2eb-4760-9b47-e4726e229e91.mov
