### ISSUE TITLE
Alert box styling seems not to actually work

### ISSUE THREAD

**Issue by eric-wieser** [microsoft/vscode-jupyter#10422]
Now that it's released (I was never able to get it to build locally), I notice that the alert-box styles added in #10034/#10021 don't actually seem to take effect:
* In regular markdown documents, they are correctly injected, but refer to css variables (`--theme-error-background` etc) which seem to only exist inside notebooks. Where do these variables come from?
* In notebooks, the CSS file appear not to be injected at all. Perhaps this is a bug in the code notebook handling of VSCode, and no in this reposistory

## Environment data

-   VS Code version: 1.68.0
-   Jupyter Extension version (available under the Extensions sidebar): v2022.5.1001610507
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Gitpod
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used: N/A
-   Jupyter server running: Remote

## Expected behaviour

These lines should inject a stylesheet into the markdown cells of notebooks

https://github.com/microsoft/vscode-jupyter/blob/d3f539ed4a586c195485f0ec8e0a5fbf1cdcd391/package.json#L2059-L2061

## Actual behaviour

The styles are only injected into plain markdown documents, and there the CSS variables aren't available.

## Steps to reproduce:

Open https://nbviewer.org/github/ipython/ipython-in-depth/blob/master/examples/Notebook/Notebook%20Basics.ipynb in vscode, note that the alert boxes do not render differently.

Create a markdown file containing
```
<div style="alert alert-danger">I'm in danger</div>
```
and open the markdown preview. Note that the colors are absent but the indentation is present.

**Comment by DonJayamanne** [comment]
I personally think we should revert the code added in the previous PRs used to address this issue (as it doesn't work), and re-do this as extension into the notebook Markdown renderer as described here `These lines should inject a stylesheet into the markdown cells of notebooks`

**Comment by eric-wieser** [comment]
IMO the bug here is that the jupyter notebook viewer doesn't respect `markdown.previewStyles`; if other vscode extensions add extra styles for markdown, these should probably be visible in jupyter notebooks too.

**Comment by joelostblom** [comment]
I currently use alert boxes in student assignments for jupyter notebook in order to make it easier for students to see the question prompts. In JupyterLab, the default alert styles have low contrast between the text and  the background:

```html
<div class="alert alert-info">

## No color style

Some text
here
</div>
```

![image](https://user-images.githubusercontent.com/4560057/197252668-be66f758-c3d4-47fc-8431-90b73d0d15da.png)

Because of this low contrast I explicitly set the color so that the text is easier to read in JupyterLab, which is the editor most of our students use:

```html
<div class="alert alert-info" style="color:black">

## Black color style

Some text
here
</div>
```

![image](https://user-images.githubusercontent.com/4560057/197252867-347d6450-36b8-47cd-8811-1b7124c79ef1.png)

This works really well and makes things easier to read. However, because of this issue in VS Code preventing the alert boxes from being displayed, this is what the students using VS Code see in these assignments:

![image](https://user-images.githubusercontent.com/4560057/197253631-b51cfa4b-d9b1-4695-ae9e-4b04327f18d7.png)


This makes them unusable and they are currently either changing to a light theme, switching back to JupyterLab to work, or having two windows open side by side. Is there any workaround for this that would allow students working in vscode to actually see the alert boxes, or at least have the text automatically switch color to white when in vscode? JupyterLab shows this just fine in dark mode:

![image](https://user-images.githubusercontent.com/4560057/197253522-9672b708-f0cf-4e39-bc52-89c182c9fdd6.png)

**Comment by DonJayamanne** [comment]
Looks like https://github.com/microsoft/vscode-jupyter/issues/8399 has regressed and perhaps needs to be re-implemented.

**Comment by DonJayamanne** [comment]
@amunger assigning to you as the PR was reverted and pending the investigation into what caused the issue in markdown and how we can address that.

**Comment by psychemedia** [comment]
Alert styling was one of the simplest ways of rendering styled alert boxes in Jupyter notebooks for many years. More recently, use of MyST syntax, such as [admonition blocks](https://myst-tools.org/docs/spec/admonitions), provide another way of including richer styled content in a markdown block.

In JupyterLab, this is rendered using the [`jupyterlab-myst` extension](https://github.com/executablebooks/jupyterlab-myst); a VS Code extension —  [ExecutableBookProject.myst-highlight](https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight) — supports rendering for MyST markdown extensions such as admonition blocks, but I don't think these extensions work in the notebook rendering context?

**Comment by roblourens** [comment]
I don't see any alert styling on the notebook at https://nbviewer.org/github/ipython/ipython-in-depth/blob/master/examples/Notebook/Notebook%20Basics.ipynb

**Comment by roblourens** [comment]
Seems like there isn't a pre-release for the notebook renderers extension, so I just don't have the code

**Comment by amunger** [comment]
new version was never released. doing that now and it should be available with insiders

**Comment by amunger** [comment]
verify you see the colors in a markdown preview for a markdown cell with contents
```
<div class="alert alert-success">
Enter edit mode by pressing `Enter` or using the mouse to click on a cell's editor area.
</div>

<div class="alert alert-info">
Enter command mode by pressing `Esc` or using the mouse to click *outside* a cell's editor area.
</div>

<div class="blah-alert alert alert-danger">
Do not attempt to type into a cell when in command mode; unexpected things will happen!
</div>
```
