### ISSUE TITLE
Incorrect coloring and syntax error

### ISSUE THREAD

**Issue by GF-Huang** [microsoft/vscode-jupyter#10644]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Variable names have several colors at the same time.

![image](https://user-images.githubusercontent.com/4510984/176588867-ba7e79de-2fe1-49de-b12d-94bdd435da2a.png)

### VS Code Version

1.68.1

### Jupyter Extension Version

v2022.5.1001601848

### Coding Language and Runtime Version

Python 3.9.12 by Miniconda

### Language Extension Version (if applicable)

Python v2022.8.1

### Anaconda Version (if applicable)

conda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by IanMatthewHuff** [comment]
Thanks for filing. I don't have enough info here to exactly repro this, but this type of coloring mismatch it usually due to a disconnect between the notebook and Pylance, which is supplying the coloring for the syntax here.

Could you please pull the logs from Output->Jupyter? Might help up with understanding this scenario. @rchiodo are there also Pylance logs we should be getting here?

**Comment by rchiodo** [comment]
Yes there are settings for pylance. Unfortunately these depend upon the experiment state of the machine before we can get logs for pylance (well because the experiment determines what way pylance is started).

**Comment by amunger** [comment]
closing this since it has been over a month since the last request for info
