### ISSUE TITLE
Magic commands in interactive Python mode not working

### ISSUE THREAD

**Issue by TarjinderSingh** [microsoft/vscode-jupyter#10711]
Using MacOS 12.4, and the newest v2022.5.1001601848.

When using magic commands in interactive Python mode (`test.py`),

```
# %%
#!%%timeit
print('hi')
```

I get `UsageError: Line magic function `%%timeit` not found.`

However, when I directly type in the following in the interactive Python page, it works.

```
%%timeit
print('hi')
```

Is there some I should do to get the magic commands to work in the interactive Python situation?

**Comment by DonJayamanne** [comment]
Thanks for filing this issue,
This has been fixed in the latest pre-release version.
You can try the latest pre-release by installing VS Code Insiders and then installing the pre-release version of the Jupyter extension.
Or this fix will be available in the next release, which would be some time today/tomorrow
