### ISSUE TITLE
Bash cell rendered as python

### ISSUE THREAD

**Issue by RafalSkolasinski** [microsoft/vscode-jupyter#10739]
I believe https://github.com/microsoft/vscode-jupyter/issues/4554 should not be closed. Would normally comment there but your policy locks threads. 

The reply from you before closing was basically that it's PyLance problem. I rather believe this is a problem of rendering jupyter notebook part to understand that cell is not a Python cell but rather a bash cell and should be validated / rendered as such.

As was pointed in original thread a cell for a magic can be also`%%sh`, `%%html`, `%%javascript`. 
Saying this is responsibility of PyLance which is [Feature-rich language support for Python in Visual Studio Code](https://devblogs.microsoft.com/python/announcing-pylance-fast-feature-rich-language-support-for-python-in-visual-studio-code/) to render / validate other languages is wrong.

**Comment by rchiodo** [comment]
Thanks for the issue.

The 'language' of a cell determines what language server is in use. That's why Pylance was mentioned.

However we have a feature request to automatically change the language based on magics being entered. See this issue here:
https://github.com/microsoft/vscode-jupyter/issues/4588
