### ISSUE TITLE
Execution of cell being sent to terminal

### ISSUE THREAD

**Issue by jejsemin** [microsoft/vscode-jupyter#1090]
I have been having many problems with this extension

I am using this Jupyter notebook as an extension to run my Python ipynb files but every time I go to run it it runs in the console instead of the notebook
It is reset to Python instead of Jupyter every time I try to run it. How do I get them to stop returning to Python and stay on the Jupyter setting?
I want to be able to use Python extension without this Jupyter notebook extension as the previous version was much more friendly, how do I do that?
![Screen Shot 2020-11-12 at 2 24 08 PM](https://user-images.githubusercontent.com/63566417/98987011-a7744580-24f3-11eb-9344-4af9025a5800.png)

**Comment by DonJayamanne** [comment]
> b files but every time I go to run it it runs in the console instead of the notebook

I'm assuming you are using `ctrl+enter` in the editor.
This is a known bug and we're looking into this.

> How do I get them to stop returning to Python and stay on the Jupyter setting?
I want to be able to use Python extension without this Jupyter notebook extension as the previous version was much more friendly, how do I do that?

If you prefer the old Notebook editor (which will eventually be deprecated in favor of the new editor, which is wha tyou are using), then please add the following setting into your settings.json file
```json
	"jupyter.experiments.optOutFrom": [
		"NativeNotebookEditor"
	],
```

**Comment by DonJayamanne** [comment]
I cannot replicate this on  my mac.

**Comment by emmanoni** [comment]
Changing the setting "jupyter.sendSelectionToInteractiveWindow" to true worked for me

**Comment by greazer** [comment]
@jejsemin, from what I'm reading above, it sounds like your original issue would be addressed if you opt out from the NativeNotebookEditor experiment or switch to VS Code stable. This experiment is responsible for turning on the new notebook experience. In VS Code insiders it's active by default. In VS Code stable it's not.

@emmanoni, I assume that you were trying to run cells from a python script (rather than a notebook) and that's why the setting you changed allowed code to be executed in the interactive window instead. If this isn't the case, and you were executing cells from an ipynb file that were originally going to the terminal, please enter a separate issue. 

Thank you both!
