### ISSUE TITLE
bogus URL should be removed 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode-jupyter#10956]
Testing #10911

Not sure what the URL that initially appeared was from, but could that be empty instead since it's invalid?

**Comment by rchiodo** [comment]
Do you have a screenshot? I assume you're talking about the placeholder text? It's supposed to show you what a URL should look like

**Comment by meganrogge** [comment]
I was confused because the URL seemed random. Maybe it could say example or something?

**Comment by meganrogge** [comment]
Part of my confusion was I expected it to be filled in for me 🤔 from the terminal but maybe that's too much too ask 😅

**Comment by rebornix** [comment]
I ran into the same today and the problem is

* Copied a new server URL
* Open VS Code, choose to add a server
* The quick pick has a URL filled in, but not the one from my clipboard, and in @meganrogge 's case and some of my cases, the URLs are invalid
* Pasting from clipboard updates the input box, meaning the original URL was not from clipboard (or something is wrong with the VS Code clipboard API)

**Comment by amunger** [comment]
I don't think we're pre-populating that input box anymore with that experiment (I cannot repro at all). @meganrogge or @rebornix - can you confirm if you're still seeing?

**Comment by DonJayamanne** [comment]
Re-assigning as this is a UI issue with regards to remote kernel connection and I believe this falls under kernel selection UI.

**Comment by DonJayamanne** [comment]
This has been fixed
