### ISSUE TITLE
Fail to render the cells & type with the cursor not moving (weird!)

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode-jupyter#10973]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When I delete a line with Backspace, the color of all words in the notebook becomes disordered, and this happens:

![2](https://user-images.githubusercontent.com/40828952/181666502-c6f0f91a-8ae4-4177-a3b5-82e2d0986ff3.gif)
 
Only reloading the window can restore the notebook, with all variables and my work missing.

### VS Code Version

Version: 1.69.2 (system setup) Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a Date: 2022-07-18T16:12:52.460Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.6.1201981810

### Coding Language and Runtime Version

Python v3.8.12

### Language Extension Version (if applicable)

v2022.6.2

### Anaconda Version (if applicable)

2020.07

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
The gif doesn't show what triggered this, right? Was it just backspacing until the line was erased? Does it happen consistently or was this just a one off occurrence?

The poor font colorization could be caused by us, and if you see it again, can you provide the logs from the output window for Juptyer? (command `Jupyter: Show Output`)

The strange cursor behavior is either from vs code core, or another extension you have installed - can you try disabling other extensions, or using the `Help: Start Extension Bisect` command to try and narrow down the cause (if it repros easily)?

**Comment by amunger** [comment]
can you also try setting `"python.pylanceLspNotebooksEnabled": true` in your settings to see if that resolves the issue?

**Comment by Saltsmart** [comment]
The poor font colorization happens consistently. It is reported to be caused by Jupyter notebook renderers when running `Help: Start Extension Bisect`. No additional output is generated.

I haven't seen the strange cursor behavior since then.
