### ISSUE TITLE
Debugger can't restart when paused in a separate file

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#11026]
It happened like this: 

I was debugging a notebook cell, which called a module.  
I Set a breakpoint on the module I imported (.py file). 
Somewhere during the debug session I clicked "restart debugging".

Then I got: 
"Couldn't find a debug adapter descriptor for debug type 'Python Kernel Debug Adapter' (extension might have failed to activate)"

And I'm no longer able to debug the notebook until I restart vscode: 

![t](https://user-images.githubusercontent.com/92439290/182275636-3241819c-a81c-412d-9887-e9d55e825776.png)

_Originally posted by @phgmacedo in https://github.com/microsoft/vscode-jupyter/issues/10596#issuecomment-1201927331_

**Comment by DonJayamanne** [comment]
I think the problem here is we're re-starting the kernel without first shutting down the existing debugger.
Looking at the error message, this is from VS Code, leading me to believe debugger crashes unexpectedly (due to restart of the kernel), hence the error message from VS Code.
I.e. if we're already debugging, then we should shutdown the debugger, then restart the kernel.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode-jupyter/issues/7670
