### ISSUE TITLE
"Create Interactive Window" command does not open in the current work directory

### ISSUE THREAD

**Issue by Diogo-Rossi** [microsoft/vscode-jupyter#1108]
## Environment data

-   VS Code version: 1.51.1 (**Portable version**)
-   OS: Windows 10
-   Python version: 3.8.3

## Expected behaviour

When run the command **"Jupyter: Create Interactive Window"** (```jupyter.createnewinteractive```)
The python interactive window should open on the current project's folder as working directory,
which can be seen with line command ```pwd```

## Actual behaviour

The python interactive window opens in VSCode installation folder.

## Steps to reproduce:

1. Open VS Code in some folder
2. Run the command **"Jupyter: Create Interactive Window"** (```jupyter.createnewinteractive```)
3. Verify the current work directory with command ```pwd``` in the opened Python Interactive Window

Remark: Using the **Portable version** of VS Code (don't know if this makes difference)

**Comment by DonJayamanne** [comment]
Apologies for the delay in getting back to you.
Please could you provide the following info:
* Do you have a workspace folder opened? Is it a single folder or a multiroot workspace folder
(a screenshot with list of files/folders opened in VS Code would help)

**Comment by Diogo-Rossi** [comment]
Hi there.
I have a single folder opened, but it also happens when I have a multi-root workspace. The two examples are shown bellow:

Single folder:

![image](https://user-images.githubusercontent.com/57204023/100808129-567cb080-3412-11eb-8554-b5ab9e9e576f.png)

Workspace:

![image](https://user-images.githubusercontent.com/57204023/100811568-ae6ae580-3419-11eb-9352-c14491337adf.png)

**Comment by DonJayamanne** [comment]
Please could you :
* Enable debug logging, go into settings `Jupyter-> Logging` and select `debug`
* Restart VS Code
* Run a cell
* Capture the output from `Jupyter` output panel & paste that output here.

**Comment by nobrn** [comment]
I have the same issue. I followed the steps above, here is my debug output: [debug_output.txt](https://github.com/microsoft/vscode-jupyter/files/5876612/debug_output.txt)

**Comment by DonJayamanne** [comment]
Thanks for the logs, & I'm sorry for not getting back to you on this.
Please could you let me know where you `Temp` folder is located, could you provide the fully qualified path to that.
Please could you modify `test.py` and add the following & run it
```python
import os
print(os.getcwd())
print(__file__)
```

Please run in your terminal (ensure the conda environment has been activated in the terminal) & then in the kernel.

**Comment by nobrn** [comment]
I did my best to replicate Diogo-Rossi's setup. My `test` folder is located at `C:\Dev\test`

I also created new logs for this folder: [debug_log.txt](https://github.com/microsoft/vscode-jupyter/files/5907217/debug_log.txt)

![screenshot](https://user-images.githubusercontent.com/51063625/106526654-9d873080-64ab-11eb-956d-48bf43220628.png)

**Comment by DonJayamanne** [comment]
Thanks for the information, this is very weird, let me have a look at the code.

**Comment by DonJayamanne** [comment]
I'll try to send you a custom VSIX.

**Comment by DonJayamanne** [comment]
@nobrn Please could you:
* Install VS Code Insiders
* Install the Jupyter extension
* Try this out again

We have added a lot of logging & udpated the code recently and believe this would be addressed there.

Also what is the value of the following setting at your end:
![Screen Shot 2021-03-26 at 10 01 01](https://user-images.githubusercontent.com/1948812/112667197-371eee80-8e1a-11eb-995b-6407e147851b.png)

**Comment by nobrn** [comment]
I apologize for the wait.

![debug_img](https://user-images.githubusercontent.com/51063625/115140223-d723fe00-9ffb-11eb-9a63-9853456d4caa.png)
[debug_log.txt](https://github.com/microsoft/vscode-jupyter/files/6330835/debug_log.txt)

The interactive window 1 was opened with the 'Jupyter: Run Current File in Interactive Window' command. Window 2 was opened with 'Jupyter: Create Interactive Window' with editor focus on the `test.py` file. Window 3 was opened with the same command but with focus on the explorer. The file `test.py` was run in the terminal below. `debug_log.txt` was copied from the Jupyter output afterwards.

Both my original VSCode installation and the insiders version had `${fileDirname}` under the Notebook File Root setting.

I tried the same thing on my original VSCode installation and a couple of the times I tried it, focusing on the `test.py` window while calling the 'Jupyter: Create Interactive Window' command would give an python output of `c:\Dev\test`. When I opened another interactive window while focusing on the explorer, it would give the VS Code folder as output instead of `c:\Dev\test`. I wasn't able to replicate this in either version of VSCode.

Using a Jupyter Notebook File Root of `${workspaceRoot}` worked every time for me (always printed `c:\Dev\test`) both in my original version and the insider's version of VSCode.

**Comment by DonJayamanne** [comment]
I've finally figured out the problem, sorry for the delay in getting to the bttom of this.

**Comment by Diogo-Rossi** [comment]
Hi.
I'm testing the new "[native built-in interactive window](https://code.visualstudio.com/updates/v1_58#_jupyter-interactive-window)" and the issue now happens even when I use the command "Run current file in the interactive window". which it didn't before.

But now the window opens in the drive's root folder `C:\`, as show below

![image](https://user-images.githubusercontent.com/57204023/125212156-e379c900-e281-11eb-86b9-eac41ee87eac.png)

**Comment by joyceerhl** [comment]
@Diogo-Rossi  That's been fixed in VS Code Insiders 😊 https://github.com/microsoft/vscode-jupyter/issues/6549

**Comment by joyceerhl** [comment]
Should be fixed in the native interactive window. Please file a new issue if this doesn't work for you.
