### ISSUE TITLE
Different fonts for markdown vs code cells

### ISSUE THREAD

**Issue by melaniewalsh** [microsoft/vscode-jupyter#1109]
It would be great if the font for markdown cells could be different than the font for code cells (as they are in regular Jupyter notebooks). Is it possible to change the font just for markdown cells? 

Here's a screenshot of some markdown and code in a Jupyter notebook opened with VSCode, which both seem to appear in the same font:

![Screen Shot 2020-11-13 at 11 14 20 AM](https://user-images.githubusercontent.com/20325102/99094304-a00b7580-25a1-11eb-8943-1f94a57ba94e.png)

**Comment by greazer** [comment]
Thanks for your feedback. This issue will be addressed once VS Code adds native support for editing notebooks. Please see https://github.com/microsoft/vscode/issues/91987.

**Comment by manujchandra** [comment]
Hi,

The Issue is marked as closed. I am using the following version:

```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:37:02.931Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.11.0-7612-generic
```

The font of markdown cells are still in monospace and are not picked from markdown font settings.

@greazer Are you referring to Improved markdown editing > Preview todo item which will implement this change? If yes then we can track that item.
