### ISSUE TITLE
Latex not rendered correctly in Jupyter Notebook 

### ISSUE THREAD

**Issue by zqni** [microsoft/vscode-jupyter#1112]
Issue Type: <b>Bug</b>

Can't rendered any formulas such as
$x_{i}$ 
in the Jupyter Notebook at an insider  VS Code.

Extension version: 2020.12.360617350-dev
VS Code version: Code - Insiders 1.52.0-insider (050a123750e4ef4009930d0da1ff7a1a6441d4f3, 2020-11-12T05:43:04.852Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 5.4.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (21.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Zq|
|OS|Linux x64 5.4.0-53-generic|
|CPUs|Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz (16 x 1200)|
|Memory (System)|62.51GB (49.46GB free)|
|VM|0%|
</details>

**Comment by CaesarOG** [comment]
I am experiencing the same issue with Jupyter in VSCode Insiders back since this started as the preview notebook feature back in July. Anything markdown in dollar signs such as $\sum_{\lambda}$ does not render as per LaTex and just shows the raw text with the dollars signs, from things as simple as $n$ . Itching to drop Jupyter Lab/Notebooks for VSCode Insiders the moment this is fixed since notebooks now have full IDE errors & completion & goto which actual Jupyter even Lab can't compete with, as well as inherit all syntax colors from theme!!

Extension version: 2020.12.360431621-dev

VSCode version: Code - Insiders   1.52.0-insider Commit: ee46c1f89ebb213e0827886f1688c0fbb55be49f Date: 2020-11-13T06:04:37.031Z (1 day ago)

OS version: Mac OS 10.15 Catalina

**Comment by jasongrout** [comment]
> ITCHING to drop Jupyter Lab/Notebooks for VSCode Insiders the moment this is fixed since notebooks now have full IDE errors & completion & goto which actual Jupyter even Lab can't compete with

FYI, check out the JupyterLab LSP plugin which I think provides some of these things for JupyterLab: https://github.com/krassowski/jupyterlab-lsp

**Comment by DonJayamanne** [comment]
Closing as a dup of https://github.com/microsoft/vscode-jupyter/issues/1216
