### ISSUE TITLE
Flaky test: IPyWidget Script Manager: "before all" hook for "Returns the right base Url"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#11328]
https://github.com/microsoft/vscode-jupyter/runs/8238528902?check_suite_focus=true

**Comment by DonJayamanne** [comment]
Looks like the test failed due to something else.
No logs, very weird, the error renderer is not loading, i think there could be some other flaky ness here, more like infrastructure.

![Screen Shot 2022-09-08 at 14 42 38](https://user-images.githubusercontent.com/1948812/189035982-073d537c-c8af-413a-988a-f18b8cb9ffbe.png)

**Comment by DonJayamanne** [comment]
No longer flaky
