### ISSUE TITLE
no currency symbols for Indian currency (₹)

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/vscode-jupyter#11352]
### Applies To

- [X] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

<img width="83" alt="image" src="https://user-images.githubusercontent.com/53593544/189585597-1adac756-8535-4a2f-96a2-87f3bed657a3.png">
while using jupyter notebooks to view the excel files using pandas the currency symbols are not being shown in the interactive output window.

Can anybody please provide a fix to that?

### VS Code Version

1.71.0

### Jupyter Extension Version

6.4.12

### Coding Language and Runtime Version

Python v3.9.13

### Language Extension Version (if applicable)

2022.10.1 (14 July 2022)

### Running Jupyter locally or remotely?

Local

**Comment by soumesh2002** [comment]
> @soumesh2002 may I ask what's the editor font you are using?

I'm using Consolas (default font)

**Comment by soumesh2002** [comment]
@rebornix I use Consolas

**Comment by amunger** [comment]
the symbol seems to show up correctly everywhere for me, what happens if you just run a cell like this (and also open the data viewer from the Jupyter variables panel)

```
data = ({'a': '\u20B9 5000'})
data
```

![image](https://user-images.githubusercontent.com/2019016/206322619-864bc59c-d6c8-4738-b2bf-967e24ec67a0.png)


![image](https://user-images.githubusercontent.com/2019016/206322399-a6bd83fa-c28d-4161-8594-4537a0202839.png)

**Comment by amunger** [comment]
actually the symbol can just be used directly

```
data = ({'a': '₹ 5000'})
data
```

How are you viewing the data frame
