### ISSUE TITLE
Something wrong with the widge "leaflet"

### ISSUE THREAD

**Issue by Alanwak3** [microsoft/vscode-jupyter#11399]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by DonJayamanne** [comment]
I'm sorry for missing this, please could you provide more information about the problem.
Please fill in the missing information such as expected behaviour, actual behavior and steps to repro the issue.
I'd be happy to re-open this issue once the information has been provided, or please feel free to create a new issue.

FYI - You might be running into the issue #8552
