### ISSUE TITLE
Plotly charts fail to load with a message about WebGL is not supported

### ISSUE THREAD

**Issue by nikhilwoodruff** [microsoft/vscode-jupyter#11400]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I tried to display a Plotly chart in a Jupyter notebook. After some debugging, I've managed to narrow down the issue. The following works perfectly:
```python
import plotly.express as px
import numpy as np

px.line(y=np.linspace(0, 1, 1_000))
```
Result:
![image](https://user-images.githubusercontent.com/35577657/190918347-aa2fb1af-a18a-40b3-b97c-1d1901b23f69.png)

The following fails:
```python
import plotly.express as px
import numpy as np

px.line(y=np.linspace(0, 1, 1_001)) # 1000 + 1
```
Result: 
![image](https://user-images.githubusercontent.com/35577657/190918380-f3c67ac8-2f26-4812-b79e-ab59b8c7bac7.png)

### VS Code Version

1.71.2

### Jupyter Extension Version

v2022.8.1002431955

### Jupyter logs

```shell
N/A
```

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
thanks for filling this issue 
please could you
* go into the command palette and select `Toggle Developer Tools`
* look for any errors in the console window and paste that here
* provide details of your OS

**Comment by DonJayamanne** [comment]
FYI - I've tried this at my end, and I'm not seeing this behaviour, I've tried `1_000_000` and I'm not running into this issue.

**Comment by nikhilwoodruff** [comment]
Hmm, OK here's the result set from the log window (no errors, just outputs).
[vscode-app-1663596746396.log](https://github.com/microsoft/vscode-jupyter/files/9599683/vscode-app-1663596746396.log)

My OS is Ubuntu 20.04.5 LTS (from a Dell XPS 9300).

Thanks

**Comment by DonJayamanne** [comment]
@nikhilwoodruff 
* are you running VS Code with `--disable-gpu` command line flag for VS Code 
* Can you try the same thing in Jupyter outside VS Code and let me know how this goes?

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by nikhilwoodruff** [comment]
Oh thanks @DonJayamanne - I actually haven't reproduced this issue recently anyway. Thanks for the help though!

**Comment by JPvRiel** [comment]
This happened on my Ubuntu 20.04.5 system as well. As a wild guess, I suspect it could be something to do with suspend and resume as I only noticed it after resuming. In my case, I have an NVidia GPU and proprietary drivers, and in the past, NVidia hasn't had the best track record for providing stable drivers on Linux Desktops given NVidia forum posts I've seen about Linux users having problems and strange graphics artifacts after resuming.

Since vscode is rendered via chrome in some way, this it might be relevant?: [Issue 1155863: WebGL lost context can't be restored after suspend on Linux Nvidia](https://bugs.chromium.org/p/chromium/issues/detail?id=1155863)
