### ISSUE TITLE
Why are you prompting to get people on pre-release?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#11477]
Related: https://github.com/microsoft/vscode-jupyter/issues/9005

I just installed the autopep8 extension and opened a python file and then see this:

![image](https://user-images.githubusercontent.com/2193314/192803206-e81c531a-4762-4e6e-8929-5fcc8019bfad.png)

1. I don't know why it's asking about the Jupyter extension when I've simply opened a python file.
2. Why are you asking at all? Isn't prerelease the default install when installing an extension on Insiders so you will get users on it over time and this notification is going to bother people. Example:
   ![image](https://user-images.githubusercontent.com/2193314/192803643-b33ac9b3-a0be-47e9-aecb-0816a21a23d8.png)
3. Why is it a warning?

**Comment by amunger** [comment]
related https://github.com/microsoft/vscode-jupyter/issues/9005

assigning @IanMatthewHuff since he's on that one

**Comment by IanMatthewHuff** [comment]
Resolved by totally removing this notification I don't believe it's helpful anymore. I believe it was a leftover from the day where we didn't have an "official" pre-release version.

Validation: On VS Code - Insiders change the dropdown to install Stable Jupyter instead of the default Pre-Release. You should not be prompted to install pre-release after that.
