### ISSUE TITLE
Notebooks - variable explorer icon taking long time to appear in toolbar

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#11573]
## Environment data

-   VS Code version: 1.72.0 - insider
-   Jupyter Extension version (available under the Extensions sidebar): v2022.9.1002791758
-   Python Extension version (available under the Extensions sidebar): v2022.16.0
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local
## Expected behaviour

Variable Explorer icon to be in toolbar reasonably quickly 

## Actual behaviour

When opening notebooks or creating new notebooks it takes a really long time for the variable explorer icon to appear in the toolbar

## Steps to reproduce:
1. create new notebook 
2. wait for variable explorer icon to appear

**Comment by roblourens** [comment]
The only thing that would slow it down is this part of the "when" clause `notebookKernel =~ /^ms-toolsai.jupyter\\//`, we can't add the button until we know that it's compatible with the selected kernel. For me, the button appears pretty much instantly, along with the kernel. It's also possible that this got faster in the past couple months with all of the work around kernels we've done. If it's still slow, then that's probably because the kernel selection is slow and we can't really improve the button. Let me know if this is still bad for you on the latest, especially if it seems like it takes longer than it takes to select the kernel.
