### ISSUE TITLE
Support kernel detection (pull) in addRemoteJupyterServer API

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#11650]
With the movement to multiple remote kernel finder and making the kernel detection push model (other than pull), we might want to change how the extension api `addRemoteJupyterServer` API works to better support third party extensions.

Firstly the assumptions I took are the remote kernel finders work in such fashion:

* When a jupyter server uri is added to the storage, we will create a `RemoteKernelFinder` for it, and register the `RemoteKernelFinder` to the kernel finder registry.
* A kernel spec/session will be kicked off asynchronously. When kernel specs/sessions are found, it will broadcast the event and the Controller component will create controllers for it based on the strategy users choose (Traditional or the new workflow @IanMatthewHuff is working on).

With above in mind, we also want to support third party extensions to set a remote jupyter server uri, and wait for `NotebookControllers` to be created for them. Thus the `addRemoteJupyterServer` will need to

- [x] Register a remote jupyter server uri to the storage
- [x] A new `RemoteKernelFinder` is created for the server uri and registered to the kernel finder registry
- [ ] We can then get the `RemoteKernelFinder` instance for the server uri
- [ ] We can then wait for the `RemoteKernelFinder` to find the kernel specs/sessions lookup.
- [ ] We can then ask the `ControllerLoader` to create `NotebookController`s for the newly found kernels.
- [ ] Now the API method can resolve

**Comment by IanMatthewHuff** [comment]
I like it. Lines up with how I'm thinking about the kernel sources.

One question. Since we were discussing this a bit on the other item. Where exactly is the ownership between points 1 and 2 on your list? Right now I kinda had the UniversalRemoteKernelFinderController doing this (watching the server list, then creating individual kernel finders) but I'm not fully sure about that I did design. Feels a bit awkward to me.

Is the storage doing it? That also seems like an odd responsibility for a storage class.

Also I'm not sure if this is just a wording difference, but this here:
> We can then ask the ControllerLoader to create NotebookControllers for the newly found kernels.

I thought that everything from the ControllerLoader perspective was running through the single main kernel finder and the message to see when kernels were updated. Do you just mean signaling that kernels were updated at this point (which is what I would assume)? Or did you mean actually some other channel to the ControllerLoader?

**Comment by rebornix** [comment]
> One question. Since we were discussing this a bit on the other item. Where exactly is the ownership between points 1 and 2 on your list

Since we need to store the remote uri list, we always need a storage (which is `ServerUriStorage` now) and a manager which can create kernel finders from the entries in the storage. I'm wondering if we can do something similar to the Editor Types in VS Code core, the storage will contain both `Type` and additional info:

```ts
interface IKernelFinderInstance<T> {
  type: KernelFinderType;
  data: T;
}
```

then we can store a list instances in momento as 

```ts
[
  { type: LocalKernelFinder }
  { type: UniversalRemoteKernelFinder, data: { uri } }
]
```

When we deserialize the cache from momento, we can look up the types and know how to create a kernel finder instance from it. 

At the end, the `ServerStorageUri` and kernel finder manager would be the same thing.

**Comment by rebornix** [comment]
This is archived through MRU kernel picker and will be tested there.
