### ISSUE TITLE
Blank notebooks default to the first kernel (regardless of language)

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#1183]
Not sure if this happens with old webview stuff but with new native notebooks we pick the first kernel returned by Jupyter. This might be something like a julia kernel.

Jupyter does this when creating a new notebook:
![image](https://user-images.githubusercontent.com/19672699/90659613-c071a100-e1f9-11ea-895b-8253f30e4784.png)

I think we need to do the same. Ask the user for a kernel when they start execution (or maybe at least pick the first kernel that matches the language of the first cell in the notebook)

**Comment by DonJayamanne** [comment]
This has been fixed, moving to validate.

**Comment by DonJayamanne** [comment]
Going to ensure we make this change only for native notebooks.
Changing for webview notebooks requires a lot of changes, that will soon be (hopeuflly) unnecessary when live share is handled by VS Code for native notebooks.

**Comment by rchiodo** [comment]
This does not seem to be fixed? 

I can't create a blank notebook with a different language other than python. The kernel is always python. The only time it is not is I explicitly set it.

**Comment by DonJayamanne** [comment]
> 1) Create blank notebook
1) Set cell to C#
1) Run notebook (it uses python, does not ask)

This is as expected, we were never planning on fixing that.
If however you have some empty cells and then change your kernel to C#, then we will change the languges of the cells to C# from Python or other.

Just because you change the cell language doesn't mean we'll change the kernel. Its possible in Python you can change the cell language to JavaScript or Bash or other & you can still use a Python kernel.

If however you open an existing notebook, then we'll default the kernel based on metadata in the notebook.

If its a blank notebook, then theres' nothing that can be used to default the kernel & i don't think we should change the kernel either just because the language in the cell is changed. 
Moving to backlog & I don't think this is required for experiment (adding label) & hopeuflly we can discuss and sort out the requirements 
@claudiaregio  /cc

**Comment by IanMatthewHuff** [comment]
Validated with a Julia notebook.
