### ISSUE TITLE
Cannot see python kernels, only the julia one

### ISSUE THREAD

**Issue by VolodyaCO** [microsoft/vscode-jupyter#11844]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a project where I use both julia and python jupyter notebooks. After I opened a julia notebook for the first time, the selected kernel was set to julia, but the python kernels disappeared, even though when I open any .py file on vscode on that project, the python interpreter of my choice can be easily loaded by choosing a path to the interpreter.

### VS Code Version

1.72.2

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
N/A
```

### Coding Language and Runtime Version

Python 3.9.10, and Julia 1.8.0

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
@VolodyaCO 
I'm very sorry for missing this issue and never getting back to you.
I believe this would have been resolved in our latest pre-release version (somethign we plan to ship next week)
We made a lot of fixes in loading interpreters.

Please could you:
* Install vscode insiders
* Install the latest pre-release version of the jupyter extension
Verify this has been fixed in there, if not please feel free to reopen this issue or create a new issue.
