### ISSUE TITLE
Support for separated jupyter and kernel environment

### ISSUE THREAD

**Issue by skwde** [microsoft/vscode-jupyter#12201]
To run notebooks in VSCode we have to install `jupyter` and `ipykernel` in the **same** environment. To former comes with a lot of other dependencies which blows up the environment.

I used to run jupyter in a different environment and just connect to the different kernel environment.
I.e. I have two environments

- minimal `jupyter` environment
- the actual kernel environment where I installed the actual packages required to run the code + `ipykernel`

This setup requires the additional package `nb_conda_kernels` (see also <https://github.com/Anaconda-Platform/nb_conda_kernels>) in the `jupyter` environment.

Currently this does not work with VSCode Jupyter extension (at least to my knowledge).

At least to my mind shipping the Jupyter extension with the tools required to run the server while enabling users to connect to different kernels (via `nb_conda_kernels`) would be a good approach.
Allowing users to just connect to the kernel they want while only requiring the install of the kernel itself would be great.

Is something like this planned? Or already possible and I just fail to understand how to properly set it up?

**Comment by DonJayamanne** [comment]
> Allowing users to just connect to the kernel they want while only requiring the install of the kernel itself would be great. 

this is already supported

> Weird, when I just tested it once more it seems to be enough to only install ipykernel in the python environment.

Thats right, thats evidence that you have found this to be workign as expected

> Can you please clarify the linked part and how choosing a python interpreter via Python: Select Interpreter and then choosing a kernel in the upper right of the notebook plays together?

If you were to select a Python environment, such as a new virtual environtment or a conda environment with python in it, then we will install (with users consent) ipykernel into this selcted pythonn environment.
Behind the scenes we launch the kernel just as Jupyter does and communicate with it over the same protocol that Jupyter application uses. I.e. you could also think that we're registering a temporary kernel thats transparent to the user.

hope that makes sense.

> Currently this does not work with VSCode Jupyter extension (at least to my knowledge).

Please could you create an issue with details of the problems you ran into.

As this issue seems to have been addressed. I'm going to close this. The original issue was a requset to separate jupyter from the kernel, and thats already been addressed.

I'm curious why you created this issue, i.e. what lead you to believe that things weren't working as expected. Please file an issue for that.
If the above answer still doesn't answer the question please do feel to post here.
