### ISSUE TITLE
Merge builtin and jupyter error renderer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#12285]
We should merge the features from jupyter's error renderer to the builtin one so we can benefit from all features shipped with the core, including scrollable output.

* Link detection for local file path
  * [x] https://github.com/microsoft/vscode/issues/132145
    * [ ] how to differenciate remote and local paths?
  * [x] https://github.com/microsoft/vscode/issues/131239
  * [ ] 🏃https://github.com/microsoft/vscode-jupyter/issues/9879
* [x] Support open files from another editor group through file link
* Debt
  * [x] https://github.com/microsoft/vscode-jupyter/issues/12018
  * [x] https://github.com/microsoft/vscode/issues/160745

**Comment by rebornix** [comment]
The builtin error renderer already supports the necessary link detection. Will remove the jupyter one early Jan.

**Comment by corneliusroemer** [comment]
Aside: Finally found the PR/Issue that was mentioned in February 2023 release (am I dumb or is there no easy way to find PRs from the release notes? There's no changelog apparently, and no markup in release notes and wording is often different - please educate me if I'm missing something obvious)

Does this feature ["Jupyter extension's error renderer was deprecated in favor of the built-in error renderer." ](https://code.visualstudio.com/updates/v1_76#_better-link-support-for-builtin-error-renderer )mean that these:
- https://stackoverflow.com/questions/75607544/how-to-display-formatted-jupyter-stack-trace-from-full-output-data?noredirect=1&lq=1
- https://stackoverflow.com/questions/71195740/vs-code-text-output-unreadable-format-in-new-window
- https://github.com/microsoft/vscode/issues/153839
- https://github.com/microsoft/vscode/issues/153855

issues should be resolved now? Or are the linked cases different because these errors are not handled by VSCode?

**Comment by amunger** [comment]
@corneliusroemer - one thing this change does is make those issues easier to tackle since we can just focus on one renderer.
There is not usually a direct link to issues from the release notes, might be something for us to consider adding.

For error output, tomorrow's insiders release should enable scrolling on errors to provide the full stack within the notebook: https://github.com/microsoft/vscode/issues/174634
Some other follow up work for scrollable output is here https://github.com/microsoft/vscode/issues/175778

There is still an issue open somewhere for unreadable characters when opening the text editor for output, but we're currently focused on improving the scrollable region as a workaround for that.
