### ISSUE TITLE
Kernel discovery issue

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#12362]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> I still do not understand why it is impossible to add a kernel other than the main one (Python 3/11) It seems that all the libraries for working with Jupiter are installed. However, another version showed up a couple of times in the list of cores and that's it. Then again only the main version remained, 3.11. <br><br>Translated from:<br>"Я так и не понял, почему невозможно добавить иное ядро кроме основного (Python 3/11) Вроде бы все библиотеки для работы с Юпитером установлены. Однако другая версия пару раз показалась в списке ядер и все. Затем опять осталась только основная версия, 3.11."

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue, 
Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.
* And please could you let me know which one is supposed to show up in the list, so that i can find that in the logs

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.
