### ISSUE TITLE
TqdmWarning: IProgress not found

### ISSUE THREAD

**Issue by david-waterworth** [microsoft/vscode-jupyter#12684]
The process that installs jupyter the first time a notebook is opened in vscode in a new environment doesn't appear to install `ipywidgets`. When I run certain code that relies on tqdm for the first time I get the warning

> .venv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
>   from .autonotebook import tqdm as notebook_tqdm
> 

It's an easy fix `pip install ipywidgets`

I believe it can be tested using

`from tqdm.autonotebook import tqdm as notebook_tqdm`

It would be nice if `ipywidgets` was installed with jupyter as it seems to be a dependency of many ML libraries.

**Comment by DonJayamanne** [comment]
Jupyter is only installed into an environment to launch the Jupyter application and that is not required on all OS.
Right now Jupyter is only installed on Mac M1 (arm chip) and a few Linux distros.

When running python code against a kernel, users can chose different any different envioronment and that point the user is prompted to install IPyKernel. At this point we could probably prompt the user to also install IPyWidgets

However I'm not convinced this is a good idea as IPyWidgets 8 got release very recently, and the Jupyter extension in vscode does not support that. Users with existing code might be targetting ipywidgets 7, hence even if we supported 8, installing 8 could then cause other issues with the users envionrments and installation of apckages via requirements.txt files or the like.

As IPYwidgets is an add on feature and not crucial for kernel functionality, I think users should chose how to isntall them (and have control over pinning them to specific versions)

Thanks for the suggestion, how ever due to the above reasons, I don't think we're yet in a place to make this a standard recommendation
