### ISSUE TITLE
Execute Code silently waits forever if there is no response from the execute request

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#12785]
1. debug the jupyter extension
2. disable zmq `"jupyter.disableZMQSupport": true,`
3. put a breakpoint right [after an execute request is sent to jupyter](https://insiders.vscode.dev/github/microsoft/vscode-jupyter/blob/f2f5fb3169c8032362853914b84600687b245d93/src/kernels/helpers.ts#L619)
4. run a cell 
5. when that breakpoint is hit, wait 90 seconds before continuing to cause `WebSocket ping timeout after 90000 ms.`

:bug: the `await request.done;` line will wait forever because there won't be any more communication from jupyter
This makes it look like we're still trying to connect:

![image](https://user-images.githubusercontent.com/2019016/217670191-e2d1035c-5002-4d3a-992d-d895e6a77f61.png)

**Comment by DonJayamanne** [comment]
> put a breakpoint right [after an execute request is sent to jupyter](https://insiders.vscode.dev/github/microsoft/vscode-jupyter/blob/f2f5fb3169c8032362853914b84600687b245d93/src/kernels/helpers.ts#L619)

Since you are debugging the Jupyter extension and waiting for 90 Seconds in the debugger, then ALL communication is paused (thats because the debugger will stop everything in the event loop).
I.e. you are deliberrately stopping all communication to the kernel. I suspect there's a timeout somewhere for 90s, and since you stopped everything, there's aboslutely nothing we can do other than increase the timeout (this is how the debugger works)

I do not think we need to do anything here as users will not run into this issue, 

However if you feel we can do something to improve the debugging of jupyter extension experience in this case, please do feel free to re-open and make some changes there,
