### ISSUE TITLE
New error renderer does not support line wrapping

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#12842]
Seems like we always display a horizontal scrollbar
This feels like a bad UX, even in VS Code we support work wrap, and I htink there are settings for this.
IF this is configurable, then having to always scroll to read error messages feels like a poor UX as we didn't have to do this in the past

To me this feels pretty bad as it used to be better, and now we're changing the UX significantly

**Comment by rebornix** [comment]
> This feels like a bad UX,
> IF this is configurable, then having to always scroll to read error messages feels like a poor UX as we didn't have to do this in the past

This can be very opinionated like we are seeing with editor word wrapping. I often find the error call stacks hard to read due to the word wrapping. A similar issue reported before https://github.com/microsoft/vscode-jupyter/issues/7818. 

> now we're changing the UX significantly

With that said, it's a noticeable UX change and might have big impact than anticipated. Adding a setting makes perfect sense and also making "wrapped" as the default value feels fine to me. cc @amunger .

**Comment by DonJayamanne** [comment]
> This can be very opinionated like we are seeing with editor word wrapping. I often

oh yes, you are right, sorry
Let’s leave this as a debt or please feel free to close this issue

**Comment by aa-hh-7200** [comment]
> يبدو أننا نعرض دائمًا شريط التمرير الأفقي. هذا يبدو وكأنه UX سيئ ، حتى في VS Code نحن ندعم التفاف العمل ، وأعتقد أن هناك إعدادات لذلك. إذا كان هذا قابلاً للتكوين ، فإن الاضطرار إلى التمرير دائمًا لقراءة رسائل الخطأ يبدو وكأنه تجربة مستخدم سيئة حيث لم يكن علينا القيام بذلك في الماضي
> 
> بالنسبة لي ، هذا يبدو سيئًا جدًا لأنه كان من قبل أن يكون أفضل ، والآن نحن نغير تجربة المستخدم بشكل كبير

free cgtxEd sad gxewsc$\\dSC
