### ISSUE TITLE
DS: Provide rich debugger support for pandas DataFrames

### ISSUE THREAD

**Issue by apryor6** [microsoft/vscode-jupyter#1286]
I build lots of Flask APIs that internally use pandas DataFrames, and almost daily I find myself jumping into the debugger; however, there is not a particularly good way to inspect the contents of DataFrame. Ideally there would be a way to, perhaps, double-click or hover on a DataFrame variable and have a popup that shows the first few rows spreadsheet-style

The Spyder IDE has something like what I describe

Currently, I find I am limited to either:

- Calling print(df.head()) from the debugger console. This is pretty clunky
- Writing the DataFrame to a file and re-importing into a Jupyter notebook, iPython, etc. This method introduces a class of problems in addition to the time inconvenience
- Inspecting the variable from the debugger Watch menu, but for an object as complex as a DataFrame this doesn't work as well. There is an implicitly structured context to a DataFrame that is not fully captured here.

I've felt for some time that this would be a great feature, but honestly I assumed there would be a large number of other data scientists sharing the same request and that it would magically appear. This is me conceding that point and doing what I should have already and making the request.

Edit: I see a teaser for such functionality from some time ago [here](https://visualstudiomagazine.com/articles/2019/04/24/vs-code-python-update.aspx), but I don't see this inside of the app. Am I missing something, or is there an update?

**Comment by chopeen** [comment]
I spent some time researching this topic to see how hard it would be to create such a visualizer extension for the Python debugger in VS Code. I found no easy way. [Debug Visualizer](https://github.com/hediet/vscode-debug-visualizer), but the support for Python (not to mention DataFrames) is [very limited](https://github.com/hediet/vscode-debug-visualizer/issues/34).

I created a [feature request](https://github.com/microsoft/vscode/issues/111105) for VS Code to support custom data visualizers. It will be added to the roadmap when it gathers 20 upvotes.

🗳️ Go to https://github.com/microsoft/vscode/issues/111105 and vote by clicking 👍!

**Comment by deutschmn** [comment]
I built myself a solution for numpy arrays in Jupyter notebooks. It works in VS code but also in other Jupyter environments. Probably doesn't entirely replace the feature asked for in this thread, but it's a good enough intermediary solution - for me at least. 😄 

<img width="650" alt="full_example" src="https://user-images.githubusercontent.com/37573274/105382187-1961bd00-5c10-11eb-82ce-fc3a55eafcd4.png">

https://github.com/deutschmn/ndpretty

**Comment by joyceerhl** [comment]
We have added the ability to open DataFrames in our data viewer when paused on a breakpoint in the debugger by right-clicking on the variable's name. You can see a GIF of this in action in our blog post:

https://devblogs.microsoft.com/python/python-in-visual-studio-code-january-2021-release/#data-viewer-when-debugging

Our data viewer currently supports an allowlist of data types with more enhancements on the way. We appreciate your patience and look forward to your feedback!

**Comment by agrimaldi74** [comment]
That's quite a good start!
It takes a few seconds to open, but then it works perfectly.
What I'd like to have is a refresh button to update the content of the variable after it has been modified, instead of having to select it and open in Data Viewer again in a separate tab.
And also the possibility to change the value of a dataframe or array element.
One thing on filtering pandas dataframes:
I can click on Filter Rows button and enter a condition in any of the white boxes that appear below the column names. The dataframe gets filtered in real time. But when I click again on teh Filter Rows button, the dataframe stays filtered. I'd expect that once the filters are masked, they are not applied. One could get confused unless he shows the filters.
My suggestion is that the filters gets applied only when the conditions are visible or, alternatively, add some indication that the dataframe is filtered even when the conditions are hidden.
Hope in future improvements!
Thanks a lot for now

**Comment by joyceerhl** [comment]
Thanks for your ideas @agrimaldi74, I've created new issues to track them. 

We'll be closing this issue now that we have added DataFrame support to the debugger. Please open a new issue if you encounter problems or have suggestions for improving the current experience 😊
