### ISSUE TITLE
Cannot render Matplotlib in VSCode with %matplotlib inline

### ISSUE THREAD

**Issue by 93chanle** [microsoft/vscode-jupyter#12879]
### Applies To

- [x] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I suddenly have trouble rendering plots in Jupyter Notebook ouput in VSCode, even with %matplotlib inline. It only shows e.g. **<Figure size 640x480 with 1 Axes>**

I came across [this issue](https://github.com/microsoft/vscode-jupyter/issues/9697) and updated the ipympl package, but the problem still persists.

Thanks for helping!

### VS Code Version

1.75.1

### Jupyter Extension Version

v2023.1.2010391206

### Jupyter logs

```shell
<Figure size 640x480 with 1 Axes>
```

### Coding Language and Runtime Version

Python 3.10.8

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this issue.
Its possible you have version 8 of the ipywidgets package installed.

This has been fixed in the latest pre-release version
* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

If that does not work, please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by 93chanle** [comment]
Thank you very much, that did it for me!
