### ISSUE TITLE
Widget load failed due to moved links on jsdelivr.com CDN

### ISSUE THREAD

**Issue by xueyunquan** [microsoft/vscode-jupyter#12946]
## Environment data

-   VS Code version: 1.75.1
-   Jupyter Extension version (available under the Extensions sidebar): v2023.1.2010391206
-   Python Extension version (available under the Extensions sidebar): v2023.2.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: 3.10.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Expected behaviour

Widgets rendered correctly.

## Actual behaviour

Widgets not rendered.

## Steps to reproduce:

When running this simple code:
```python
import ipywidgets as widgets

w = widgets.ToggleButton(
    value = False,
    description = 'Test Button',
    button_style = 'primary',
    icon = 'check'
)

display(w)
```
nothing is shown, and logs below are produced.

Comparing the extension code with the actual (working) URL reveals that the source code wants the files at 
```
https://cdn.jsdelivr.net/npm/${packageName}@${moduleVersion}/dist/${fileName}
```
while the files live actually at 
```
https://cdn.jsdelivr.net/npm/${packageName}@${moduleVersion}/lib/${fileName}
```

## Logs
error 16:11:57.035: Widget load failure {} {
  className: 'ToggleButtonStyleModel',
  moduleName: '@jupyter-widgets/controls',
  moduleVersion: '2.0.0',
  cdnsUsed: false,
  isOnline: true,
  timedout: false,
  error: '{}'
}
error 16:11:57.051: Widget Error: Error: Failed to render widget 384b89745dcb4fcba7de4ffef0bdceb0, Error: Module @jupyter-widgets/controls, semver range ^2.0.0 is not registered as a widget module

**Comment by DonJayamanne** [comment]
Looks like you are using IPyWidgets 8,
This has been fixed in our main branch, you could either wait for the next release (some time thsi week)
or please try this in vscode insiders asn the pre-release version of the Jupyter extension, see here for instructions
If that does not work, please do ping here or feel free to re-open this issue or create a new one

* Please install latest VS Code Insiders
* Open the extensions page, search for Jupyter and click the button `Switch to Pre-Release Version`
* Similarly please install the latest `Pre-Release` version of the Python extension

<img width="572" alt="Screenshot 2023-02-04 at 09 24 37" src="https://user-images.githubusercontent.com/1948812/216722719-fd8e14dc-783f-4859-8235-012b1bc796d9.png">

**Comment by xueyunquan** [comment]
Thanks for the reply. It works in the insiders version, as you suggested. Thanks.

**Comment by DonJayamanne** [comment]
Since a new version of vscode was shipped last week, this should work in the latest stable version as well
