### ISSUE TITLE
Autocomplete hangs the kernel for interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#1300]
`Version: 2020.1.58038 (13 January 2020)`

I have a dataframe with shape of (810103, 26). If I type code and run a cell from the editor, everything is fine. But it will be extremely slow if I run code from the interactive window directly such as `df.head()`, `df.columns`. I can even make a screenshot without shortcut😂

![image](https://user-images.githubusercontent.com/33796896/72404984-48a03d00-3725-11ea-9398-04add5f7822c.png)

**Comment by radusuciu** [comment]
> 
> 
> Some of the advice here seems to alleviate the problem:
> [jupyter/notebook#3224](https://github.com/jupyter/notebook/issues/3224)
> 
> I typed this in to the interactive window:
> 
> ```
> %config Completer.use_jedi = False
> ```
> 
> and now it responds immediately. At least with the csv you mentioned above.

This fixed the issue for me as well.

**Comment by adrianomartinelli** [comment]
> Finally had a chance to profile the IPython kernel. The autocomplete from typing is hanging the kernel and preventing the execution of a cell. We should be able to fix this by interrupting the kernel if it's in the middle of autocompletion.

I experienced the same issue with slow executions with simple commands like .shape or .head().
However I also observed the following: I only experience the lag if I type the command into the IPython console, but if I select the command from the history it does not lag.

> %config Completer.use_jedi = False

This actually solved the issue so far.

**Comment by rchiodo** [comment]
> However I also observed the following: I only experience the lag if I type the command into the IPython console, but if I select the command from the history it does not lag.

This further points out what I found out while debugging. If you just up arrow on the history, it won't cause autocompletion to fire so the kernel won't be busy doing that when executing.

**Comment by GeoffNordling** [comment]
%config Completer.use_jedi = False
...solves  it for me as well. But I'm a little unclear on how to add this to startup commands, as @rchiodo suggests. Is this correct?
!
[Capture](https://user-images.githubusercontent.com/33404577/102816989-ea4ff580-439c-11eb-8fc3-30523e5da7bb.PNG)

**Comment by GeoffNordling** [comment]
No, that was not correct. Jupyter: Run Startup Commands was throwing error about invalid type "expected Array". So, wrapping in brackets might work...at least it makes the error go away. Since this problem is sporadic and random, I won't immediately know if this fixed the issue.
![Capture](https://user-images.githubusercontent.com/33404577/103368594-f8390100-4a95-11eb-87b0-b0566003e86e.PNG)

**Comment by nemar3** [comment]
this is a bit annoying..just to get the shape of a dataframe it takes a while

![image](https://user-images.githubusercontent.com/65395704/112904987-0543ab80-90ea-11eb-8e09-1c992f7ff10a.png)
 
![image](https://user-images.githubusercontent.com/65395704/112905036-1096d700-90ea-11eb-8a81-996c26f0ea8b.png)

**Comment by rchiodo** [comment]
@nemar3 did you follow the advice above?

```
%config Completer.use_jedi = False
```

Either put this in your startup commands or run this first in the interactive window.

**Comment by nemar3** [comment]
@rchiodo yes I did add it before and it didn't help then..but I added it again and now it seems to have helped...

**Comment by greazer** [comment]
Closing for now as it seems most issues have been resolved. Please enter a new bug if necessary.

**Comment by rchiodo** [comment]
This is not fixed. We still need to address this.

**Comment by greazer** [comment]
Longstanding bug, and the workaround seems to alleviate the situation for the most part. Moving to October.

**Comment by DonJayamanne** [comment]
Why don't we keep track of the pending completion requests & let users know that things are slowing down because of Jedi in the kernel & ask them to just turn this off.

Some (if not most, totally guessing here) users will want this, to get better completion.
Feel its better to let them know when things are slowing down & what they can do.

Just like in VS Code core, they let users know what extension is chewing up CPU process & slowing VS Code down, then Users can optionally blitz that extension. Similarly users can opt into disabling jedi completely (we can just add that into a startup command if they click `yes` and if they want they can go back and just remove that line from the settings.json startup commands)

**Comment by rchiodo** [comment]
Yeah I wanted an automated solution. We didn't originally just do make this a startup command because we never spent the time to investigate what the possible side effects of this were. Why is this not the default for jupyter in the first place?

**Comment by DonJayamanne** [comment]
> ust make this a startup command because we never spent the time

I agree, we should get to the bottom of the issue, rather and applying a bandaid fix.

**Comment by rchiodo** [comment]
It looks like we already implemented the 'disable jedi for kernels'. Code is here.
https://github.com/microsoft/vscode-jupyter/blob/e567b896aec30a7bb811a3f7b135f4a96ea2f1df/src/client/datascience/jupyter/kernels/kernel.ts#L527

Closing this as I don't repro it anymore with that setting enabled.

**Comment by zrxdaly** [comment]
I also had same problem. After some searching online, I think i found how this problem occured and how to alleviate it. 

This long hangs occured after I updated my conda version and at the same time my ipykernel also needs to update to higher version. I guess it is because of the version of ipykernel. In my case is: 6.4.1. 

1. create a new virtual env
2. set ipykernel version as 5.3.4
3. before run code in cell, run [conda install jupyter](https://stackoverflow.com/a/69468056/15954839). This ensure vscode will not upgrade your ipykernel directly.
