### ISSUE TITLE
Adopt quick pick hover for kernel picker

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#13086]
* When Python extension is not installed, then display a tooltip for the corresponding quick pick item (Completed in https://github.com/microsoft/vscode-jupyter/pull/12988) 
* When Python is not installed, then display a tooltip for the corresponding quick pick item (Completed in https://github.com/microsoft/vscode-jupyter/pull/12988)

* When we have a conda environment without Python installed in it, then display a tooltip for the corresponding quick pick item (will be done as part of https://github.com/microsoft/vscode-jupyter/issues/11855)

**Comment by connor4312** [comment]
I don't see a tooltip on the initial "install python" hint

<img width="702" alt="image" src="https://user-images.githubusercontent.com/2230985/226709643-3d896f6a-4a57-4670-b669-c9d419d073a9.png">

I couldn't go further, since running in a devcontainer without Python installed, it just "detects kernels" forever

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/2230985/226710719-ae9d36fa-d8bc-4ac0-8d41-4fb9f03122df.png">

**Comment by DonJayamanne** [comment]
@TylerLeonhardt any idea why the tooltip isn't being displayed for @connor4312 
I can see this working at my end (tried in desktop and dev containers) Possibly OS related?
Not sure whats going on.

@connor4312 can you try moving the mouse around while hovering over the quick pick item, to get the tooltip.

**Comment by DonJayamanne** [comment]
> I couldn't go further, since running in a devcontainer without Python installed, it just "detects kernels" forever

Will file a seprate issue for that.

**Comment by TylerLeonhardt** [comment]
It could be that the hover doesn't show up fast enough... additionally, I'm curious if `ctrl`+`space` shows the hover.
