### ISSUE TITLE
Exception `Exception while attempting zmq` not present in output

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-jupyter#13127]
Testing #13092

Here is what I did:

- Docker container with the following devcontainer.json file
```
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/python
{
	"name": "Python 3",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/python:0-3.11"

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "pip3 install --user -r requirements.txt",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```
- installed Python extension (v2023.5.10791707)
- installed Jupyter extension (v2023.3.1000820547)
- create Jupyter notebook
- when prompted installed kernel

What I see in the output channel is:

```
info 07:52:16.552: ZMQ loaded via fallback mechanism.
```

**Comment by dbaeumer** [comment]
Uninstalling `pyzmq` didn't change anything since it will be reinstall on execution after prompting to update / install the kernel.

**Comment by DonJayamanne** [comment]
@dbaeumer this is correct
Oops, i made a small mistake and that tiny mistake change the test completely
You have verified that the this works as expected

I have updated the issue to include the word `not` in the verifcation step, basically the error message should NOT exist
sorry for the confusion.
Also this issue verifies (due to lack of the message) the issue was tested and works properly as expected.
