### ISSUE TITLE
hang-ups and reconnecting to kernel issues on mac m2

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13229]
From https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details

> I used to really enjoy using this plug-in until I was forced to get a new computer and had to reinstall everything. I downloaded the latest version of this extension and now face constant hang-ups and reconnecting to kernel issues. I have a feeling this might be because of a recent version of Mac or the M2 chips I was forced into but this has become a real pain now unfortunately.

**Comment by rebornix** [comment]
@DonJayamanne do you think this issue is already fixed with the upcoming release?

**Comment by DonJayamanne** [comment]
I'm sorry you are running into this issue.
Looks like you are running into a known issue here https://github.com/microsoft/vscode-jupyter/issues/12775#issuecomment-1447175314

We believe we have addressed this issue in the latest version of the Jupyter extension due to be released some time this week.

As a temporary work around (until the new version is released), please try downgrading some packages as described below:
* Open the command palette and select `Select Interpreter to Start Jupyter Server`
    * The selected item will be displayed in the dropdown
    * This is the Python environment used to start Jupyter, 
* Run the following command against the above Python environment
`python -m pip install "jupyter-client<8" "pyzmq<25" `


If this does not work, please do let us know and we'll look into this, to help you please could you provide the logs as requested below
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by DonJayamanne** [comment]
Closing as the underling issue has since been resolved
