### ISSUE TITLE
Add more end-to-end integration tests

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode-jupyter#13267]
From [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter&ssr=false#review-details):

> This is a complex project which relies on many other complex parts of other projects (e.g. jupyter-server, jupyterlab/services, etc.). More end-to-end integration tests should be added to ensure that upstream changes and bugs don't break things when bumping their versions.

**Comment by DonJayamanne** [comment]
> ex project which relies on many other complex parts of other projects (e.g. jupyter-server, jupyterlab/services, etc.). More end-to-end integration tests should be added to ensure that upstream changes and bugs don't break things when bumping their versions.

We do have a lot of integration tests.
and we are some of the first to catch some of the breakages, however shipping new version or identifying the fact that these are related to upstream issues is not easy.
E.g. just because a kernel fails, we do not know whether its caused by ipykernel, ipython, traitlets, etc, 
even if we do identify a cause, shipping fixes is next to impossible in most cases, as these packages are installed by users.
