### ISSUE TITLE
Support all actions in the three dot Altair/Vega-Lite menu

### ISSUE THREAD

**Issue by joelostblom** [microsoft/vscode-jupyter#13261]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Clicking the three dots menu of an Altair/Vega-Lite charts and selecting "Open in Vega Editor" does nothing. It would be great if the the editor was actually opened instead, as it is when clickign the same link in JUpyterLab. Related to https://github.com/microsoft/vscode-jupyter/issues/11294

Sample code:

```py
import altair as alt
from vega_datasets import data


source = data.wheat()

alt.Chart(source).mark_line().encode(
    x="year:O",
    y='wheat:Q'
)
```

### VS Code Version

1.72.2

### Jupyter Extension Version

v2022.9.1303220346

### Running Jupyter locally or remotely?

None

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, unfortunately these cannot be enabled due to the way the Vega editor expects data to be passed to it.

These menu items require access to the vega window (to pass data from the output from the output to the Vega editor in another window/page) that will be opened up, and since VS Code does not run in a browser context, this will not work

**Comment by mattijn** [comment]
Gentle ping @domoritz, are you aware of this? Do you know another approach how we could adjust Vega-Embed/Editor to make this work again?

**Comment by domoritz** [comment]
One way to open a spec in the editor is to encode the whole spec in the url. We lz compress the json and then put it in the url woth base64 encoding.
