### ISSUE TITLE
Update latex/markdown renderer to drop nteract (use something better)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#1327]
We're constantly fixing bugs here,
I think we should try to address this by using something else.
Also, add support for offline usage (currently I think we need network connection).

* This seems to handle everything https://marketplace.visualstudio.com/items?itemName=goessner.mdmath
* Or use markdown it latex extension (create our own renderer, the above extension is already doing that)
* Or submit fixes upstream
* Or use another

**Comment by ashic** [comment]
I'm seeing a similar issue, however, for me it appears that the rendered markdown shows the underlying LaTex.

![capture](https://user-images.githubusercontent.com/565991/103135760-7e2e0400-46b2-11eb-9dea-affabd2c98db.png)

**Comment by AceEviliano** [comment]
When I waas redirected here I thought there might be a workaround or something. So do we need to be online to be able to render latex in jupyter notebook? I was directed here from this question in stackoverflow [here](https://stackoverflow.com/questions/63274331/latex-wont-render-in-jupyter-notebook-in-vs-code-but-does-running-jupyter-noteb). Hope this issue is solved soon.

**Comment by alistairwallace97** [comment]
Not a long term solution, but as a workaround for people working on offline VMs then presumably if the required web address is found then you could put an exception in the firewall in the same way you do for pip.

**Comment by joyceerhl** [comment]
Notebooks now use builtin KaTeX for math rendering, provided by VS Code. Please file an issue on https://github.com/microsoft/vscode if you encounter bugs in markdown rendering.
