### ISSUE TITLE
add support for matlab 

### ISSUE THREAD

**Issue by codingToPerfection** [microsoft/vscode-jupyter#13314]
I think it is possible for matlab proxy working in vscode-jupyter environment. 

The related issue is here [matlab proxy unable to run on vscode-jupyter](https://github.com/mathworks/jupyter-matlab-proxy/issues/24)

# here's what's returned when i tried to use matlab proxy on vscode-jupyter
I use [vscode-jupyter](https://github.com/microsoft/vscode-jupyter) to launch `matlab kernal`. 

It returns :
```log
Kernel needs to be started by a Jupyter Server. Please use JupyterLab or Classic Notebook while using MATLAB Kernel for Jupyter.
```

**Comment by DonJayamanne** [comment]
Thanks for filling this issue and sorry you are running into this
Please can you provide steps to replicate this issue (with instruction to setup matlab and the like)

**Comment by DonJayamanne** [comment]
> Kernel needs to be started by a Jupyter Server. Please use JupyterLab or Classic Notebook while using MATLAB Kernel for Jupyter.

where is this displayed, please could you provide a screenshot

**Comment by DonJayamanne** [comment]
Closing this issue as its been over 4 weeks, since the information was requested.
We'll be happy to reopen the issue when the requested information has been provided.

**Comment by Houndoom96** [comment]
I am having a similar issue.

steps to replicate:

1. Install matlab as per their instructions and add to PATH: https://www.mathworks.com/help/install/ug/install-products-with-internet-connection.html
3. install [jupyter-matlab-proxy](https://github.com/mathworks/jupyter-matlab-proxy) using pip to current python environment.
4. create a new notebook in vscode and select kernel MATLAB Kernal (my_env). This option appears in the VS code kernel select menu under "Select Another Kernel > Jupyter Kernel > MATLAB Kernel (my_env)"
5. try to run cell with matlab code and error message appears in output section.
![Screenshot 2023-10-05 at 4 58 34 AM](https://github.com/microsoft/vscode-jupyter/assets/37459033/e947620e-e90a-48fe-a466-bf1dacffed24)

log output:
`05:04:42.228 [info] Handle Execution of Cells 0 for ~/Documents/Research/energy_graphs.ipynb
05:04:42.229 [debug] start the kernel, options.disableUI=false for ~/Documents/Research/energy_graphs.ipynb
05:04:42.230 [debug] Execution Request Sent to Kernel for cell 0
05:04:42.234 [debug] Start cell 0 execution @ 1696507482234 (clear output)
05:04:42.234 [info] Kernel acknowledged execution of cell 0 @ 1696507482234
05:04:42.236 [info] End cell 0 execution @ 1696507482236, started @ 1696507482234, elapsed time = 0.002s
05:04:42.236 [debug] Cell 0 executed with state Success`

Note that I was able to make this work by starting jupyter notebook server with the kernel first and then connecting to the existing server in vs code instead of selecting a kernel
