### ISSUE TITLE
Recover debugpy adapter without restarting the kernel

### ISSUE THREAD

**Issue by ju-w** [microsoft/vscode-jupyter#13474]
## Description

When debugging is started for the first time, a `debugpy adapter` process is created for that kernel. If this adapter process was killed or exit for some reason, no more debugging from vs-code is possible, until the kernel is restarted.
It would be great if the extension could recover in this case and just created a new adapter process instead of having to restart the whole kernel.

**Comment by roblourens** [comment]
I see that if I manually kill that process `.../site-packages/debugpy/adapter --for-server 64293 --host 127.0.0.1 --port 64292 --server-access-token ...` then debugging can't start again until I restart the kernel. @int19h can this be handled better, and if so is it an issue for debugpy or ipykernel?

**Comment by int19h** [comment]
It would be both, I think - debugpy would need an API to restart the adapter, and the kernel would need to use it as needed.

That said, this is unlikely to be something we'd do anytime soon in debugpy because the architecture tightly couples the various helper processes and is not designed to gracefully handle state recovery in cases where some part gets recycled like this outside of its control. It's possible in principle, but chasing down all the various corner cases that rely on implicit guarantees in the current arrangement would likely take a while.

**Comment by roblourens** [comment]
Thanks. Rather than recovering from it, would it be possible for one of the parties to fail debug startup with a helpful error?

**Comment by DonJayamanne** [comment]
@int19h you may have missed Robs las question, please can you let us know if thats an option? thanks

**Comment by DonJayamanne** [comment]
Thank you for filing this feature request, given that there haven't been any upvotes or other users reporting this issue for the past 6 months, I'm closing this issue.

**Comment by ju-w** [comment]
I disagree with the decision to close this. When encountering this issue, there is no indication on what is going on. At least an error message should be displayed.
