### ISSUE TITLE
Can't connect to a new remote kernel without restarting vscode

### ISSUE THREAD

**Issue by varunjain-github** [microsoft/vscode-jupyter#13484]

**Comment by DonJayamanne** [comment]
Pleat can you provide more information with steps to repro this issue

Also Please could you enable logging as follows:
* Open settings & go into `Jupyter->Logging`
* Change the value to `verbose`
* Reload VS Code,
* Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by Huntrr** [comment]
v2023.3.1000851011

1. open vscode
2. open a notebook
3. click `Select Kernel`
4. click `Select Another Kernel`
5. click `Existing Jupyter Server...` and paste in my uri
6. vscode goes back to the "Select Another Kernel" screen
7. click `Existing Jupyter Server...` and vscode shows `Enter the URL of a running Jupyter Server` instead of what I expect (I expect a list of running jupyter servers to select from)

I can't copy my whole output panel, but the tail looks like

```
info 14:46:17.740: Creating server with url : <redacted>
debug 14:46:18.019: Disposing session manager
debug 14:46:18.019: SessionManager - dispose contents manager
debug 14:46:18.019: ShutdownSessionAndConnection - dispose session manager
debug 14:46:18.021: Finished disposing jupyter session manager
debug 14:47:47.645: creating new code watcher with matching document <redacted>
debug 14:47:47.847: No controller, hence notebook communications cannot be initialized for editor <notebook file path, redacted>
info 14:47:53.628: Loading webview. View is notset
info 14:47:53.629: Loading web view...
info 14:47:53.629: Webview panel created.
info 14:47:53.775: Web view react rendered
```

If I close and reopen vscode then the kernel select button says "Detecting Kernels..." and then when I click it I can select my remote kernel correctly

**Comment by rjra2611** [comment]
Hey,

I'm facing the same issue as well. I'm only able to connect to the new remote Kernel on restarting the VSCode.

I have implemented the interface `IJupyterUriProvider`. The `getServerUri` is successfully resolved in both cases. 

Attaching the verbose logs for both the cases

[without restart.txt](https://github.com/microsoft/vscode-jupyter/files/11452820/without.restart.txt)
[After restart.txt](https://github.com/microsoft/vscode-jupyter/files/11452821/After.restart.txt)

The difference I notice in the logs is that the `After restart.txt` logs contains 
```
18:35:56.349 [debug] Disposing session manager
```

which doesn't happen without restart once both have logged `No controller, hence notebook communications cannot be initialized`

**Comment by DonJayamanne** [comment]
@rjra2611 you are running into a different issue, please could you file a separate issue for that.
