### ISSUE TITLE
VSCode cannot open files from the traceback if they are with absolute paths but it can with relative paths

### ISSUE THREAD

**Issue by ramajoballester** [microsoft/vscode-jupyter#13639]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The error was narrowed down to this:

```
raise Exception("Opening ./mono_det_demo.py works, ~/sensus-loci/sensus/notebooks/mono_det_demo.py does not work, and neither does /home/user/sensus-loci/sensus/notebooks/mono_det_demo.py")
```

I can open the first file from the traceback, not the other two (file not found). With plain python I can open all of them. The issue only happens with remote ssh. I can open them correctly when using vscode locally.

### VS Code Version

Version: 1.78.2 Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435 Date: 2023-05-10T14:47:05.613Z Electron: 22.5.2 Chromium: 108.0.5359.215 Node.js: 16.17.1 V8: 10.8.168.25-electron.0 OS: Linux x64 5.15.0-72-generic Sandboxed: Yes

### Jupyter Extension Version

v2023.4.1011241018

### Jupyter logs

```shell
Exception                                 Traceback (most recent call last)
Cell In[9], line 1
----> 1 raise Exception("./mono_det_demo.py works, ~/sensus-loci/sensus/notebooks/mono_det_demo.py does not work, and neither does /home/user/sensus-loci/sensus/notebooks/mono_det_demo.py")

Exception: ./mono_det_demo.py works, ~/sensus-loci/sensus/notebooks/mono_det_demo.py does not work, and neither does /home/user/sensus-loci/sensus/notebooks/mono_det_demo.py
```

### Coding Language and Runtime Version

Python 3.8.16

### Language Extension Version (if applicable)

Python extension v2023.8.0

### Anaconda Version (if applicable)

conda 23.3.1

### Running Jupyter locally or remotely?

Remote

**Comment by drauh** [comment]
I am also experiencing a similar issue. My environment is a remote setup using Remote SSH extension. 

The issue occurs when I'm trying to open a file from a traceback link in a Jupyter notebook that's running on the remote server. When I click on the link, VSCode attempts to open the file locally instead of on the remote server, which obviously could fails if the file is not available locally. If I have a compatible path locally, it will open it, which is very confusing... 

The problem is consistent for me regardless of how the file path is referenced in the traceback, i.e., whether it is absolute, relative, or contains user directory shorthand (~).

Here's my setup:

Version: 1.79.0-insider
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:30:25.999Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.8-060208-generic

Extensions:
Remote SSH: v0.103.2023060715
Jupyter: v2023.5.1001582324

**Comment by thatguy7** [comment]
The file links do not work in WSL at all. Just tried it in Windows natively, and it surprisingly worked - as long as there is no space in the path. But in WSL it does not work at all.

**Comment by amunger** [comment]
tracking in https://github.com/microsoft/vscode-jupyter/issues/13212
