### ISSUE TITLE
Review API `JupyterServerProvider` and prepare for stable API

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#13894]
This would be our exercise for our first stable API `JupyterServerProvider`
```[tasklist]
### Tasks
- [x] Use `CancellationError` and return `undefined` to distinguish between `cancel` and `back` (see how done in VS code Kernels)
```

**Comment by DonJayamanne** [comment]
@mjbvz Please can you have another look at the API.
https://github.com/microsoft/vscode-jupyter/blob/main/src/api.proposed.d.ts

Note: I used `JupyterServerCommand` instead of  VS Codes built in `Command`.
The reason is, I need a detail that gets displayed in the quick pick, the VS Code command only has label and tooltip.

Here is a screenshot of what it looks like today, and as you can see the detail is pretty important (to let the user know about the specs of the server).
Unfortunately that text cannot be part of the `label` as the `label` is used as the name of the server which gets displayed elsewhere.


![Screenshot 2023-08-11 at 11 38 45](https://github.com/microsoft/vscode-jupyter/assets/1948812/24ee53d2-ea34-4e8e-9d4f-fdeabbe95759)

**Comment by DonJayamanne** [comment]
This is where the discussions are taking place https://github.com/microsoft/vscode-jupyter/pull/14106

**Comment by DonJayamanne** [comment]
API Discussion outcomes
* [ ] Use CancellationError and return undefined to distinguish between cancel and back (see how done in VS code Kernels)
* Commands is tricky
    * We would like to enforce a good UX (ensure 3rd party extension have back button etc)
    * The command API is very much tied to the UI

**Comment by DonJayamanne** [comment]
Done
