### ISSUE TITLE
connection to insecure server was denied

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#13941]
the issue is that vscode seems to sometimes disallow connections to http:// jupyter servers that are password protected. Sometimes there's the warning that asks to allow but sometimes it plainly errors directly.

![grafik](https://github.com/microsoft/vscode-jupyter/assets/11522213/54a84bd8-0aa1-4516-9b92-2383d5bcf9d1)

_Originally posted by @chris-aeviator in https://github.com/microsoft/vscode-jupyter/issues/11594#issuecomment-1640551403_

**Comment by amunger** [comment]
@DonJayamanne are you familiar with the error that @chris-aeviator is seeing?

**Comment by DonJayamanne** [comment]
Unfortunately there's no way for us to tell that the server is hosted with SSL, the error message `Denied connection to insecure server` is the error returned by the Node.js
If you are trying to connect to an SSL protected server, then I would suggest you use `https://` instead of `http://`
Thats when you would get the prompt to allow connecting to servers with untrusted SSL certs

@chris-aeviator
My guess is that you are running into the latter (i.e. you need to ensure you use `https` instead of `http`)
Please try that, if it does not work ples feel free to file a new issue and I'll look into this,

**Comment by chris-aeviator** [comment]
@DonJayamanne I'm not trying to connect to an SSL enabled server, this is jupyter running on a local machine and I can access it just fine with http:// in the browser.

**Comment by DonJayamanne** [comment]
Ok, so is the problem in trying to connect to a password protected Jupyter server from the browser (vscode.dev)?
