### ISSUE TITLE
Jedi autocompletion not working in VS Code native notebooks editor preview

### ISSUE THREAD

**Issue by Silfalion** [microsoft/vscode-jupyter#1419]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1.Right click on a notebook file
2.Choose Open with preview Notebook editor
3.Import OS module
4. os. doesn't display the list of available methods

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Remote
-   **Extension version:** v2020.8.93699-dev
-   **VS Code version:** 1.47
-   **Setting python.jediEnabled:** false
-   **Setting python.languageServer:** Pylance
-   **Python and/or Anaconda version:** 3.7.7
-   **OS:** Ubuntu through WSL2
-   **Virtual environment:** conda

## Developer Tools Console Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by sergiocalde94** [comment]
Hi! This issue is occurring with both pylance and jedi, isn't it?

**Comment by rchiodo** [comment]
This issue should not be happening with pylance if you're using insiders. Jedi doesn't currently support notebooks.

**Comment by astrowonk** [comment]
> This issue should not be happening with pylance if you're using VS Code insiders. Jedi doesn't currently support notebooks.

@rchiodo Little fuzzy on what you mean. Jupyter running the regular way in a web browser uses ipython which uses jedi for autocompletion, as far as I understand.

Just speaking for myself, until VS code has autocompletion parity with a regular jupyter server (i.e. for custom classes ,for file names when doing something `pd.read_csv('my_very_long_file_name')` etc), then it's just not going to be as good as a normal jupyter server, and I can't really use it.

I rely on the feature set of jupyter autocompletion every day. This isn't a nice to have, it's a vital part of the experience.

**Comment by rchiodo** [comment]
Sorry, @astrowonk this bug is out of date.

The python extension has multiple intellisense providers. One of those is Jedi. The jedi provider (at the time this bug was created) did not support intellisense in the new native notebook editor. 

However Jupyter itself also has intellisense and is handled with a different code path. Internally there are two 'autocompletion' providers. The one from the python extension (which is statically parsing the notebook and all modules in your workspace) and one that the jupyter extension provides by talking to a jupyter kernel (which is dynamically returning autocomplete items from the active kernel).

The combination of these two completion providers is what provides intellisense in a VS code notebook. The first one (from the python extension) when it specifies Jedi as the source doesn't work with notebooks at the moment (although that's soon to change). The second one (from the jupyter extension, and ultimately from the kernel) which uses Jedi under the covers does work with notebooks.
