### ISSUE TITLE
Am asked to reenter the password for a server, even when not using a kernel from that server

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-jupyter#14213]
Testing #14199

- I did the steps for the server without a token,
- Then did the steps for a server with a token
- When I reloaded, the window, I was asked to enter the password again for the first server, even though I wasn't actually using a kernel from that server. Is there some reason that we stay connected to the server even when not needing a kernel, or is it possible to not ask for a password unless I explicitly pick a kernel from there again?

**Comment by DonJayamanne** [comment]
The proposed solution is to save the password https://github.com/microsoft/vscode-jupyter/issues/13671

> I wasn't actually using a kernel from that server. Is there some reason that we stay connected to the server even when not needing a kernel, or is it possible to not ask for a password unless I explicitly pick a kernel from there again?

The algorithm for chekcing whether a server is used is currently not the best, the fact that you have added a server is marked as using it.
Once a server is used, we need to fetch the kernels so that we can build the controllers for VS Code to display as selected controller (if a notebook had the same kernel selected previously).

Closing in favour of the above issue to save the password
