### ISSUE TITLE
Connection To Remote Jupyter Kernel Fails After Introduction of 'extension id' property

### ISSUE THREAD

**Issue by rjra2611** [microsoft/vscode-jupyter#14232]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Upgrading Jupyter Extension from `v2023.6.1101941928` to `v2023.7.1002152029` breaks successful connection to remote jupyter kernels.

Previously, the `serverId` was being calculated as a SHA-256 of `https://remote/?id=${providerId}&uriHandle=${handle}`

After, [13632](https://github.com/microsoft/vscode-jupyter/issues/13632) the logic to compute the serverId seems to have changed because of the new extensionId property. 

I'm trying to find the new pattern to compute the serverId but unable to do so. Can I please get directed to somewhere to help understand:
- The new serverId compute logic
- How to register the extensionId if required 

### VS Code Version

Visual Studio Code - Insiders (1.82.0-insider, undefined, desktop)

### Jupyter Extension Version

v2023.7.1002152029

### Running Jupyter locally or remotely?

None

**Comment by rjra2611** [comment]
The new pattern seems to be `https://remote/?id=${providerId}&uriHandle=${handle}&extensionId=${extensionId}`. 

The `extensionId` when trying to register a remote jupyter server using API `addRemoteJupyterServer` doesn't accept `extensionId` instead assigns it itself?

**Comment by DonJayamanne** [comment]
@rjra2611 just an FYI, we are planning on stabilizing the API you are using.
By stabilizing I mean, reviewing the API and going through internal discussions to ensure its in a shape so that it can be officially documented and supported.
Here is a **draft** of the new API https://github.com/microsoft/vscode-jupyter/blob/main/src/api.proposed.d.ts
Please feel free to review that and try it out, we will submit a sample on how to use that new API.

Note: The old API will not be remote just yet, we will come up with a plan to ensure you & others have time to migrate to the new API.
