### ISSUE TITLE
Auto update can't be applied in jupyter extension.

### ISSUE THREAD

**Issue by marquis08** [microsoft/vscode-jupyter#14259]
## Environment data

-   VS Code version: Version: 1.76.0 (Universal)
-   Jupyter Extension version (available under the Extensions sidebar): v2023.7.1002162226
-   Python Extension version (available under the Extensions sidebar): v2023.4.0
-   OS (Windows | Mac | Linux distro) and version: Ubuntu
-   Python and/or Anaconda version: python 3.10.0, conda 23.3.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

Disabled jupyter extension update.

## Actual behaviour

VSC automatically updates jupyter extension and can't find existing kernels.

## Current state
Every time extension got updated, I have to reinstall previous jupyter extension to find existing kernels.  
I disabled auto update in vscode preference setting as update mode and extensions audo update are set to 'none'.  
Altough python extension is applied with this diasbled setting, jupyter does not.

**Comment by DonJayamanne** [comment]
> S Code version: Version: 1.76.0 (Universal)


thanks for filling this issue and sorry you are running into this
You are using a fairly old version of vscode and a number of issues have been addressed since then specially with regards to finding kernels

You cannot update to the latest version of the Jupyter extension as the latest version of the Jupyter extension also relies on the latest version of vscode

please update to the latest version
If the problem still persist, please feel free to create a new issue

closing this oasis for now
