### ISSUE TITLE
splitting for preview

### ISSUE THREAD

**Issue by Mfundo-debug** [microsoft/vscode-jupyter#14294]
Greetings, so is here an idea again I am trying to link everything from one link to another [prev](https://github.com/microsoft/vscode-copilot-release/issues/389)

so is it possible for you guys to create a feature whereby?
1. split notebooks for comparison 
2.  split the cell maybe perhaps i want to test certain code using different way
3.  outputs two different answers from the same cell that was split into (referring to `2`)
4.  and perhaps accept one cell according to the user liking the output he wants. 
I really hope this makes sense.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, however this is not something that is supported.
if you would like to try something with two different options, then you might want to use the Interactive Window instead of using Notebooks.

The interactive window is built specifically for this, you can try multiple options without making changes to your notebook.
When you are happy you can eventually either
* Export the Interactive window to a notebook
* Or copy the final code into a notebook

Unfortunately I do not see us providing the feature you requested as this could get confusing.
Today notebooks do support split views, but its a mirror image of the existing notebook, and not the way you have sugeged
