### ISSUE TITLE
Can't connect to JupyterHub server in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#14378]
Testing #14367

1. Start a JupyterHub server in a codespace
2. Make the port public and copy the forwarded address
3. Connect to it from insiders.vscode.dev
4. :bug: JupyterHub says it's not a valid URL. Dev tools shows a CORS error. I can use this address from inside a codespace though

**Comment by DonJayamanne** [comment]
>  I can use this address from inside a codespace though

Thanks
Thats correct, codespaces is in a different domain a vscode.dev is in a different domain.
Closing as not planned, simply because JupyterHub does not support CORS

Will use this to test whether its possible to provide a better error message as mentioned here https://github.com/microsoft/vscode-jupyter/issues/14377

**Comment by DonJayamanne** [comment]
Wait, re-opening, as I though we had an auth mechanism to support this scenario.

**Comment by DonJayamanne** [comment]
> I can use this address from inside a codespace though

@joyceerhl When you say you san use this inside codespaces, is this codespaces in desktop or the browser?
I can get it working in desktop.
However in the browser, I cannot get port forwarding to work and then access JupyterHub in the browser.
Could be because JupyterHub too has a lot of proxying built into it and that doesn't work well when forwarding ports again.

**Comment by DonJayamanne** [comment]
> Make the port public and copy the forwarded address

Once you have made it public, can you access this from the browser, if not
then this is definitely not an issue with the extension

**Comment by joyceerhl** [comment]
Yes I can access it from the browser

**Comment by DonJayamanne** [comment]
Please can you send me detailed steps to setup Jupyter hub in codespaces and connect from browser
Eg steps like command used to install, version of Python and repo used etc
I cannot get this working

**Comment by DonJayamanne** [comment]
Closing this as there's nothing we can do about this, JupyterHub does not support CORS.
We will need to document this and provide users with work around

**Comment by DonJayamanne** [comment]
Will use this as the issue instead

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter-hub/issues/30
