### ISSUE TITLE
Embed a more feature-complete REPL-like experience (General feedback about improvements to Interactive Window)

### ISSUE THREAD

**Issue by taoluo** [microsoft/vscode-jupyter#1444]
There is a [web-based ipython console](https://github.com/jupyterlab/jupyterlab/tree/master/packages/console) in the jupyterlab project,  basically a [QTConsole](https://github.com/jupyter/qtconsole) counterpart in browser. 
It supports inline display of matplotlib plot and good pandas DataFrame rendering which is extremely important for interactive data processing related tasks.
hope to see that console embeded in VS Code.
a related issue may be (https://github.com/DonJayamanne/vscodeJupyter/issues/19)

**Comment by manojbaishya** [comment]
Some visual feedback from MATLAB:

![screenshot-matlab mathworks com-2021 04 18-00_27_10(1)](https://user-images.githubusercontent.com/28330014/115124535-67ece080-9fe0-11eb-94a6-e198d6d2764f.png)

![screenshot-matlab mathworks com-2021 04 18-00_51_53](https://user-images.githubusercontent.com/28330014/115124539-6e7b5800-9fe0-11eb-9339-2ce56c58fc42.png)

This workflow is script-REPL based. Individual panes can be maximized (in small screens). MATLAB might have a horrible language design :cringeface: but the tooling feels like one piece. 😄 This is not to criticise VSC given its broad focus but to relay back some information on script-based data workflows, since many people like me use only VSC now.

**Comment by connor4312** [comment]
Recently, we [have switched] to the native VS Code notebook experience and interactive window. This supports debugging and pluggable [notebook renderers](https://code.visualstudio.com/api/extension-guides/notebook#notebook-renderer) to allow rich visualization of diverse outputs, which was the original request in the issue. If there are specific features you're still missing, please [open a feature request](https://github.com/microsoft/vscode/issues/new/choose) for us!

**Comment by GitHunter0** [comment]
Is there a way to search text in the output displayed in the interactive window? I could not find a way to do It, although it is a very handy feature.

**Comment by rchiodo** [comment]
@GitHunter0 I turned your comment into an issue for VS code. We should be able to make the interactive window searchable too.

**Comment by GitHunter0** [comment]
@rchiodo , it will be really helpful, thanks a lot.
