### ISSUE TITLE
How to set environment variables for Python Interactive Window (aka IPython)?

### ISSUE THREAD

**Issue by svdHero** [microsoft/vscode-jupyter#1467]
Hi there,

I am using version `2019.6.24221` with Anaconda 2019.07 and Python 3.7.3 under Windows 8.1.

I am working at a software project where all python files are located in a subfolder "src". Hence, I added
```
"terminal.integrated.env.windows": {
        "PYTHONPATH" : "${workspaceFolder}/src;${env:PYTHONPATH}"
 }
```
to my local workspace `settings.json`.
When choosing "Run Python File inTerminal" via right-click on any of my Python files, it is exectued without any problems, because all the modules in the local directory `src` are found.

However, when I choose "Run Current File in Python Interactive Window", I get a `ModuleNotFoundError` in the Python Interactive Window, because my local source code files are not found.
When executing the IPython magic command `%env`, I can also see that the environment variable `PYTHONPATH` is not set in the Python Interactive Window environment.

How can I tell IPython/Jupyter about mylocal  `src`subfolder? Can I set project specific environment variables for IPython/Jupyter somewhere?

On Stackoverflow I have only found this post:
https://stackoverflow.com/questions/53275420/how-can-i-set-enviroment-variables-for-data-science-mode-of-vscode
which did not offer any solution.

**Comment by m-yaghini** [comment]
This is a problem when loading Jupyter notebooks inside VSCode as well.

In short, the problem is that your environment variables (that you may have defined in .zshrc/.bashrc, etc) are not automatically loaded by the local notebook server. 

Two solutions:
1. Write down the environment variables in an `.env` file in your project root, followed by their value (no quotes or exports necessary), for instance like this:
```
DYLD_LIBRARY_PATH=/Users/user/SCIPOptSuite-7.0.2-Darwin/lib
```
and reload vscode. 

2. Load your own server, outside of vscode (in a terminal for instance) and change the Jupyter server to "Existing" and enter the server's URI.

**Comment by espoirMur** [comment]
> This is a problem when loading Jupyter notebooks inside VSCode as well.
> 
> In short, the problem is that your environment variables (that you may have defined in .zshrc/.bashrc, etc) are not automatically loaded by the local notebook server.
> 
> Two solutions:
> 
> 1. Write down the environment variables in an `.env` file in your project root, followed by their value (no quotes or exports necessary), for instance like this:
> 
> ```
> DYLD_LIBRARY_PATH=/Users/user/SCIPOptSuite-7.0.2-Darwin/lib
> ```
> 
> and reload vscode.
> 
> 1. Load your own server, outside of vscode (in a terminal for instance) and change the Jupyter server to "Existing" and enter the server's URI.

Thanks for this.. .the the first solution seems to be the workaround...

**Comment by tothedistance** [comment]
.env with absolute path does not seem to work. anybody has the same issue?

**Comment by rchiodo** [comment]
This item is not under consideration for any time in the near future (you can check if it's on a milestone or not). 

There's a workaround though. Put something like so in your 'jupyter.runStartupCommands'

```
import sys
sys.path.insert(0, "F:\\Workspace\\src")
```

**Comment by Riezebos** [comment]
The title of this issue seems like it is about setting environment variables in Python Interactive in general, but the content seems like it is specifically about setting `PYTHONPATH` using `${workspaceFolder}`. My comment here is related to the former, not the latter.

Is it correct that the `python.envFile` setting is only respected in "Run and Debug" and not in Jupyter/Interactive/terminal? That seems to be the case on my system but based on the comments here I'm not sure whether this is the intended behavior. I am trying to use `python.envFile` to set env vars in the interactive window (not specifically PYTHONPATH), as I think is mentioned here:

> Not a bad idea (to mention absolute paths are required). The documentation for .env files is here: https://code.visualstudio.com/docs/python/environments#_environment-variable-definitions-file. You should be able to submit an issue (or a PR) against the docs here: https://github.com/Microsoft/vscode-docs

**Comment by rchiodo** [comment]
> Is it correct that the python.envFile setting is only respected in "Run and Debug" and not in Jupyter/Interactive/terminal?

Yes this is true.

**Comment by huweiATgithub** [comment]
> > Is it correct that the python.envFile setting is only respected in "Run and Debug" and not in Jupyter/Interactive/terminal?
> 
> Yes this is true.

Why? I mean, though python, jupyter are two different plugins, should jupyter respect the settings of python as it adds features to that?

**Comment by rchiodo** [comment]
I think we could implement this for the raw/direct kernel case by loading the .env file prior to kernel launch. Maybe for the jupyter/remote case we'd load it after launch and set each environment in it.

**Comment by rchiodo** [comment]
This should be fixed now.
