### ISSUE TITLE
Add nbextensions support for Jupyter Notebooks

### ISSUE THREAD

**Issue by qdlmcfresh** [microsoft/vscode-jupyter#1473]
# Feature: Notebook Editor, Interactive Window, Python Editor cells

## Description

Would be great to have support for nbextensions since that would fully replace a notebooks instance.

**Comment by greazer** [comment]
Guessed at area path
Thanks for your feedback. This issue is addressed with new native support for editing notebooks starting with v1.59 of VS Code. However, VS Code's notebooks do not necessarily support the extensions known by nbextensions. Extensions that you find most useful may already exist for VS Code notebooks in their marketplace, or may simply already be supported with no extensions required.
