### ISSUE TITLE
can't open data viewer from Python debug variables view

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#15058]
Consistently failing
https://github.com/microsoft/vscode-jupyter/actions/runs/7608735308/job/20718517810

**Comment by amunger** [comment]
issue in product caused by https://github.com/microsoft/vscode-jupyter/commit/14fc23d695bbabc4bf851815537c31e031ab3304

In `onVariablePanelShowDataViewerRequest(request: IJupyterVariable)`, the request parameter actually has the shape
`{ variable: IJupyterVariable }` when opening the dataviewer from the debug variables view.

**Comment by amunger** [comment]
verification steps:
1. create a jupyter notebook
2. run a cell that creates a list `x = [1,2,3]`
3. after that completes run a cell with F10 to run by line, or hit a breakpoint while debugging
4. go to the variables view in the debug pane 
5. right click the `x` variable and select 'View value in data viewer'

**Comment by eleanorjboyd** [comment]
is having to install "pandas" expected to "view value in data viewer"?

**Comment by amunger** [comment]
yes, data viewer converts everything into a pandas dataframe, so it needs that package
