### ISSUE TITLE
Add ability to reconnect to a running kernel

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#1516]
Currently our remote connection support always starts up a new kernel session. This means that if you close VSCode or get disconnected you can't get back to the session that you started. This could be an important thing for long running sessions on remote compute.

**Comment by rchiodo** [comment]
This should be working now. At least for remote. Not all that helpful if you want to use this for local.

**Comment by jayemar** [comment]
@rchiodo ?Since you closed this issue, can you explain what is working, or how to use the new functionality?  Is there any documentation explaining the new functionality and how to use it?

I came to this issue by way of [issue 1669](https://github.com/microsoft/vscode-jupyter/issues/1669) which better describes what I'm attempting to do, ie connect a "Jupyter Interactive Window" to the running kernel used by a vscode notebook.  That issue was closed as a duplicate of this one, but I'm still unable to figure out how to enable this functionality.

This ticket seems to imply that if I were to start up a jupyter notebook in a terminal (outside of vscode) that I could then connect a vscode notebook to this existing kernel, and possibly also the Interactive Window (as this was marked as a duplicate of issue 1669).  I'm having trouble figuring how to do either one.

**Comment by rchiodo** [comment]
This was closed because if you're using 'remote' you can:

- Reopen a notebook. It will auto reconnect to the existing kernel. Meaning if you close notebook foo.ipynb, then reopen it, it will be connected to the same kernel. 
- Switch a notebook or interactive window to an existing kernel. The 'running' kernels are listed in the drop down (like so at the moment)

![image](https://user-images.githubusercontent.com/19672699/147963932-67a38673-86ed-4ffa-8050-0be1eae1fecb.png)


Note - all of this only works for a 'remote' connection.

**Comment by stromal** [comment]
@rchiodo 
I just run VSCODE jupyter it as it is. 
So I don't set up a runing jupyter environemnt own server to connect to that I let VSCODE "Remote SSH" extension to do the work. 
After I reconnect the kernel that I used is invisible. 
But if I just run jupyter lab in browser set up my own runing jupyter on the EC2 than this is not a problem.
So this is an existing problem

**Comment by rchiodo** [comment]
> @rchiodo I just run VSCODE jupyter it as it is. So I don't set up a runing jupyter environemnt own server to connect to that I let VSCODE "Remote SSH" extension to do the work. After I reconnect the kernel that I used is invisible. But if I just run jupyter lab in browser set up my own runing jupyter on the EC2 than this is not a problem. So this is an existing problem

Yes, there was no general solution for reusing a kernel. If you want to reuse a kernel, you have to start your own jupyter server. That's what my comment above was about. 

Local kernels started by the jupyter extension are killed off when closing all attached editors. If you want to reuse local kernels, it would be better to open a new issue I think.
