### ISSUE TITLE
use background thread on kernel to gather variable information

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode-jupyter#15485]
example: https://insiders.vscode.dev/github.com/microsoft/vscode-jupyter/blob/main/src/standalone/chat/extesnion.ts#L82-L100

**Comment by amunger** [comment]
@DonJayamanne can you help me with a couple questions:

- Our namespaced built-ins aren't available in the scope of the bg thread, does that mean that normal built-ins are ok to use?
- `"../../standalone/api/kernels/backgroundExecution" imported in restricted zone. Only modules from ./src/platform and ./src/telemetry can be imported into ./src/kernels.`
  - can we move this hleper into platform?

**Comment by DonJayamanne** [comment]
Yes to both,
Though I'm not sure why first isn't working. it should
Perhaps its the way the code is structured,
If i recall we used to send multiple requests, instead of sending multiple requests, we might want to send one single request,
Else a function created in one request might not be available to the other request (after all the scope is different as each run in a function scope in different threads).
