### ISSUE TITLE
Failed to start the Kernel.  Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmpx5q4_1bm\build\_deps\bundled_libzmq-src\src\epoll.cpp:73).  View Jupyter log for further details.

### ISSUE THREAD

**Issue by higasam** [microsoft/vscode-jupyter#15639]
【error】
Failed to start the Kernel. 
Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmpx5q4_1bm\build\_deps\bundled_libzmq-src\src\epoll.cpp:73). 
View Jupyter log for further details.

【log】
 [error] Error in execution (get message for cell) Error: The kernel died. Error: Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmpx5q4_1bm\build\_deps\bundled_libzmq-src\src\epoll.cpp:73)... View Jupyter [log](command:jupyter.viewOutput) for further details.
    > Kernel Id = .jvsc74a57bd0492244d51cd61b2b425836b79afdcd8d6e3d563cea4be4d40911009f5cff8d08.~\AppData\Local\Microsoft\WindowsApps\python3.11.exe.~\AppData\Local\Microsoft\WindowsApps\python3.11.exe.-m#ipykernel_launcher
    > Interpreter Id = ~\APPDATA\LOCAL\MICROSOFT\WINDOWSAPPS\PYTHON3.11.EXE
    > at ChildProcess.<anonymous> (~\.vscode\extensions\ms-toolsai.jupyter-2024.3.1-win32-x64\dist\extension.node.js:337:2035)
    > stdErr = Bad file descriptor (C:\Users\runneradmin\AppData\Local\Temp\tmpx5q4_1bm\build\_deps\bundled_libzmq-src\src\epoll.cpp:73)
18:22:01.613 [info] Process Execution: ~\AppData\Local\Microsoft\WindowsApps\python3.11.exe -c "import ipykernel;print('6af208d0-cb9c-427f-b937-ff563e17efdf')"
18:22:02.484 [info] Cell 0 completed in 0s (start: undefined, end: undefined)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue and sorry you are running into this.

this issue arises when ipykernel or libzmq has not been installed correctly.
My suggestion is to re-install libzmq and ipykernel and related packages (as the installation is definitely not working, i.e. not installed correctly).

Optionally, please create a new Python environment such as a virtual environment (or a Conda environment using the Python extension) and install the dependencies into that.

Closing as this isn't an issue with VS Code or the Jupyter extension, but due to dependencies being installed incorrectly.

**Comment by rzhao271** [comment]
I am now seeing this issue on Windows 11 with the vscode-jupyter pre-release extension.
The only Python I have installed is Python 3.11 from the Microsoft Store, and I get that exact error with C:\Users\runneradmin when I try running a notebook with it.

**Comment by DonJayamanne** [comment]
@rzhao271 Is this the same issue you ran into last we spoke, and I believe it was resolved by using a virtual environment. Is that correct?

**Comment by rzhao271** [comment]
I believe it was resolved by using conda on Windows instead of venv.

**Comment by DonJayamanne** [comment]
Closing as this was resolved by creating a new environment, meaning this wasn't an issue with the extension but an issue with the setup of environment at users end.
