### ISSUE TITLE
[Freeze/Slow] Unable to save/format notebook

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#15700]
Marketplace review

> It would be good if this was more stable, because every other week something goes wrong with Jupyter in VSCode. Suddenly you cannot save anymore, or the notebook stays in pending state for literal minutes, or you cannot run your formatter, or Copilot interacts weirdly and makes VSCode hang. All of these literally happened to me in the span of two weeks.

**Comment by amunger** [comment]
@andyscho - are you on vscode insiders, or stable?

It would be great to see a trace log from the window output when this happens - `Developer: set log level` command and choose trace.
Once the issue occurs, go to the output panel and select window from the drop down. You might need to copy the output into a file and attach it here since it will be a lot of logs.

**Comment by DonJayamanne** [comment]
This issue has been open for a while now, as we haven't had any new information provided. hence closing this issue.
