### ISSUE TITLE
Requires the ability to systematically change file paths in Jupyter

### ISSUE THREAD

**Issue by jeanne150** [microsoft/vscode-jupyter#15795]
I want to change the file path to the parent of the file that is currently running. The solution now is to use the Python OS module to change the working directory. Use the `os.chdir()` of the `os` module to manually set the file path.  It's like this:
```
import os 
os.chdir(os.path.expanduser("~"))
```
I'd like to have a way to do this systematically instead of manually modifying it every time.

**Comment by jeanne150** [comment]
Related on StackOverflow：[here](https://stackoverflow.com/questions/78664306/vscode-changing-the-file-path-used-by-the-interactive-editor)

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, please can you provide more details here.
I've checked stack overflow and that doesn't seem to be realted, i.e. I do not see anyone in that issue trying to change the cwd to the user folder, in your case you are trying to change the directory to the user folder and not the parent folder.

Please can you share more information by roviding details that is missing in the issue template
* Version of VS Code
* OS
* Version of extension
* Workspace folder opened & folder structure and the file you are running in Jupyter (is it a notebook or Interactive window)
* What is the expected CWD with respect to the file in the workspace folder

**Comment by collavoce** [comment]
- Version of VS Code: 1.90.2
- Commit: 5437499feb04f7a586f677b155b039bc2b3669eb
- Date: 2024-06-18T22:54:35.075Z
- OS: MacOS (or perhaps you meant VS Code OS: Darwin arm64 23.5.0)    
- Version of Extension: Jupyter extension: v2024.5.0
- Local workspace: ~/workspace/learning/Python/nlp/src/ containing clone of https://github.com/LinkedInLearning/advanced-nlp-with-python-for-machine-learning-3807097
- being run locally as an interactive window
- expected CWD ~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2/ (when executing [this file](https://github.com/LinkedInLearning/advanced-nlp-with-python-for-machine-learning-3807097/blob/main/Chapter%202/Ch2_challenge.ipynb) . Actual recognized CWD in the editor: ~/workspace/learning/Python

**Comment by DonJayamanne** [comment]
> being run locally as an interactive window

What commands are you using exactly here.
Or how did you achieve this?

Are you running Interactive Window or a Notebook, the file you linked is a Notebook Document.
Please can you share a screen recording using gifcap.dev or the like

**Comment by DonJayamanne** [comment]
This works as expected for me.

![Screenshot 2024-06-28 at 11 28 58](https://github.com/microsoft/vscode-jupyter/assets/1948812/79b99c56-f2c3-4b91-a0c6-1103a8ae63d3)

Here is my setting

![Screenshot 2024-06-28 at 11 29 15](https://github.com/microsoft/vscode-jupyter/assets/1948812/0785c298-ab03-4aef-85b6-15bcf359ca59)

**Comment by DonJayamanne** [comment]
* Can you check if the settings under `Workspace` tag are different/
* Please could you enable logging as follows:
    * Open settings & go into `Jupyter->Logging`
    * Change the value to `verbose`
    * Reload VS Code,
    * Attempt to repro the issue & then copy the output from the `Jupyter` output panel.

**Comment by collavoce** [comment]
Under the workspace tab, same Jupyter root tag -- no difference

I added the verbose option (and the settings.json file with that new setting is showing up under /Users/jm/workspace/learning/Python) and ran both Developer: Reload Window and Python: Clear Cache and Reload window. 

Same behavior as before when running the cell containing os.getcwd() ("/Users/jm/workspace/learning/Python") -- and this was the output in the console:

09:37:33.786 [info] Disposing kernel .jvsc74a57bd0d0fb27f5aef107e0a3b82a4c76b7f537ca4a5f6b97d318ca945c3103546b5d9c./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12.-m#ipykernel_launcher for notebook /Interactive-1.interactive due to selection of another kernel or closing of the notebook
09:37:33.787 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2/Ch2_challenge.py'
09:37:33.794 [info] Dispose Kernel '/Interactive-1.interactive' associated with '~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2/Ch2_challenge.py'
09:39:19.459 [info] Starting interactive window for resource '~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2/Ch2_challenge.py' with controller '.jvsc74a57bd0d0fb27f5aef107e0a3b82a4c76b7f537ca4a5f6b97d318ca945c3103546b5d9c./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12.-m#ipykernel_launcher (Interactive)'
09:39:19.592 [info] Starting Kernel (Python Path: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12, Conda, 3.12.3) for '/Interactive-1.interactive' (disableUI=false)
09:39:19.595 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:39:19.601 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 -m ipykernel_launcher --f=/Users/~/Library/Jupyter/runtime/kernel-v2-491522L0D46pqWO1h.json
    > cwd: //Users/~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2
09:39:21.099 [info] Kernel successfully started
09:39:21.101 [info] Generated code for 1 = <ipython-input-1-9e96808d78df> with 5 lines
09:39:21.106 [info] Generated code for 2 = <ipython-input-2-9f0f8fa44d85> with 2 lines

**Comment by DonJayamanne** [comment]
> Same behavior as before when running the cell containing os

Please can you share all of the output,
There are some parts that I need, e.g. we calculate the working directory and set it up, spawn the processes, etc.
You can see the information and feel free to strip out any sensitive information, we try not to include the user names and the like.
If you do strip anything out, then do let me know what was replaced, thanks.

**Comment by collavoce** [comment]
Steps taken:
1) In settings, Jupyter Logging level is set to "info" with "verbose logging for tasks" enabled. 

2) reloaded the window and this appears in the console under "output":
`Visual Studio Code (1.90.2, undefined, desktop)
Jupyter Extension Version: 2024.5.0.
Python Extension Version: 2024.8.1.
Pylance Extension Version: 2024.6.1.
Platform: darwin (arm64).
Workspace folder ~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097, Home = /Users/jm`

3) ran this in a notebook (and interactive editor):
```
import os
print(os.getcwd())
```

The resulting output was "/Users/jm/workspace/learning/Python" 

The output in the console was:
```
09:45:09.350 [info] Starting interactive window for resource '~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2/Ch2_challenge.py' with controller '.jvsc74a57bd0d0fb27f5aef107e0a3b82a4c76b7f537ca4a5f6b97d318ca945c3103546b5d9c./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12./Users/~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12.-m#ipykernel_launcher (Interactive)'
09:45:09.511 [info] Starting Kernel (Python Path: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12, Conda, 3.12.3) for '/Interactive-1.interactive' (disableUI=false)
09:45:11.222 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 -m pip list
09:45:11.292 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 -c "import ipykernel; print(ipykernel.__version__); print("5dc3a68c-e34e-4080-9c3e-2a532b2ccb4d"); print(ipykernel.__file__)"
09:45:11.294 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 -m ipykernel_launcher --f=/Users/~/Library/Jupyter/runtime/kernel-v2-70162Ov4Fy8nwMJKl.json
    > cwd: //Users/~/workspace/learning/Python/nlp/src/advanced-nlp-with-python-for-machine-learning-3807097/Chapter 2
09:45:13.098 [info] Kernel successfully started
09:45:13.102 [info] Process Execution: ~/opt/anaconda3/envs/nlp_linkedin_prof_stripling/bin/python3.12 /Users/~/.vscode/extensions/ms-toolsai.jupyter-2024.5.0-darwin-arm64/pythonFiles/printJupyterDataDir.py
09:45:13.103 [info] Generated code for 1 = <ipython-input-1-9e96808d78df> with 5 lines
09:45:13.107 [info] Generated code for 2 = <ipython-input-2-9f0f8fa44d85> with 2 lines
```
(see screen shot)

Should I be looking elsewhere for the verbose logs other than the console? 

![jupyter_output_with_verbose_logging](https://github.com/microsoft/vscode-jupyter/assets/81253291/031594ed-e081-48e5-a23a-31520cdfb1ee)

**Comment by DonJayamanne** [comment]
* Please go into your user settings
* enable `trace` logging as per below screenshot, 
* Re-load VS Code
* Try again & share the logs

![Image](https://github.com/user-attachments/assets/90c52561-9f8b-408d-bc3c-de2fc95ddc20)
