### ISSUE TITLE
Undo works wrong

### ISSUE THREAD

**Issue by sebthedoc** [microsoft/vscode-jupyter#15870]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Easy to reproduce:
1. Create a block A and add code
2. Create block B and add code
3. Go to block A and modify the code
4. Run the block A
5. Undo

The undo will remove the block B, not undo the change to block A code.

If the user focuses block A and undo, it will undo the code change in block A.

### VS Code Version

Applies both insiders and latest

### Jupyter Extension Version

v2024.2.2024022602 (pre-release)

### Running Jupyter locally or remotely?

Local

**Comment by DonJayamanne** [comment]
> If the user focuses block A and undo, it will undo the code change in block A.

Thank you for filing this issue, however this is by design.
What we've found is that this is the best and most common expectation from users.
I.e. users expect undo/redo to work in code only when they focus the code, this way 
hitting undo/redo doesn't undo/redo code in other cells ..

You can try disabling this setting to change this.


![Image](https://github.com/user-attachments/assets/fa8253d3-318b-445b-927d-4b541685f71a)
