### ISSUE TITLE
Integrated Terminal Running the Notebook Accessible in Terminal Panel

### ISSUE THREAD

**Issue by RaimiSol** [microsoft/vscode-jupyter#15895]
**Issue**
It would be nice to have access to the terminal that is running the jupyter notebook when using the virtual environment approach. An example usecase is that I want to log in to some third party service by executing some shell commands.

**Current Approach**
My current approach is to start a jupyter server with jupyter lab and then connect to it with the vscode-jupyter feature but I would prefer to use the approach with using a virtual environment directly because the url changes every time i start the local jupyter server.

**Comment by DonJayamanne** [comment]
> It would be nice to have access to the terminal that is running the jupyter notebook when using the virtual environment approach

The Jupyter extension doesn't start Jupyter servers 99.9% of the time, its very rare that its starts a server (if thats the case, its only due to some missing dependencies)

> example usecase is that I want to log in to some third party service by executing some shell commands.

So, I'm guessing you need to initialize some environment variables, as thats the only thing that will be carried over to the Jupyter Servers (& kernels).
If thats the case, then the solution is to use `.env` files.
Just create a `.env` file in your workspace folder and add the necessary environment variables to that and the kernel will have access to those variables.

Or you might want to run some startup commands in the kernel that will ensure you always sign into the 3rd party service as part of the startup of the kernels.

Let me know if either one of these work for you.

**Comment by RaimiSol** [comment]
Thanks you gave me some good hints.

I see the extension doesn't start Jupyter servers but there must be some child process that executes the specific notebook. And in my opinion it would be nice to have an integrated terminal tab to run commands in that affect this. Because of course I can set the environment variables manually but if there are session related and require authentication it is more effective to automate this approach.

**Comment by DonJayamanne** [comment]
> I see the extension doesn't start Jupyter servers but there must be some child process that executes the specific notebook. 

The only process is the kernel, and there is no terminal session associated with the process . As we don’t use terminals to start the kernels

The only way to pass env variables to the kernel is to use .env files
given that’s the only solution I can offer I’m closing this issue
Please do try to setup the env variables in the .env file 


Also I’m not sure how a terminal session would work either, as that’s not how they work, the env variables setup in a terminal will not be propagated to an already running process (unless you want a terminal before the kernel is started, again that’s not possible as we don’t use terminals )
