### ISSUE TITLE
Jupyter kernel not found after switching between two local machines connected to the same remote server

### ISSUE THREAD

**Issue by TSBB2012nc** [microsoft/vscode-jupyter#16065]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

- Initial connection: I connect to the remote server from Machine A using VS Code Server and successfully run Jupyter notebook code.
- Disconnecting: I then disconnect from the remote server on Machine A.
- Subsequent connection: I connect to the same remote server from Machine B using VS Code Server.
- Kernel not found: When trying to run Jupyter notebooks on Machine B, the window keeps finding kernel

### VS Code Version

Version: 1.92.0 (system setup) Commit: b1c0a14de1414fcdaa400695b4db1c0799bc3124 Date: 2024-07-31T23:26:45.634Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.22631

### Jupyter Extension Version

v2024.7.0

### Running Jupyter locally or remotely?

Remote

**Comment by amunger** [comment]
Just to clarify, are you connecting to the remote machine with an ssh connection? (rather than just selecting a remote jupyter server kernel through the kernel picker)

Can you collect some logs for us:

1. set `"jupyter.logging.level": "trace"`
2. Repro the issue
3. copy the logs from the output panel after running `Jupyter: Show Output` and paste them here
