### ISSUE TITLE
Can not reload module automatically when use Jupyter in VS code.

### ISSUE THREAD

**Issue by luomeng007** [microsoft/vscode-jupyter#16167]
[Problem](https://github.com/microsoft/vscode/issues/229123#issuecomment-2363049572)

Is there anyone who can help me check this? Any solutions about this one? I asked VS code engineer, but they labeled this as an extension error. Thus now I turn to Jupyter for help.

**Comment by DonJayamanne** [comment]
Thank you for filing this issue. I've tried this and it works for me.
Tried and it works for me, 
Please avoid using file names such as `test.py`, as these names are generally reserved names in Python
You might want to create a file named `test_import.py` and try that. Its likely caused by that.

Also, when filing issues, please use the issue template instead of deleting that. We have templates with sections asking for information.
E.g. I have no idea whether you're using an old version of Jupyter extension or old version of VS Code or even an version of Python thats no longer supported, similarly we have sections asked for logs and the like.
All of that information helps us provide better assistance to you, leading to a quicker resolution.

If this still doesn't work in the latest versions, please can you create a new issue and provide the information requested in the issue template.

**Comment by luomeng007** [comment]
Ok, I will have a try then.
