### ISSUE TITLE
Can't install ipykernel

### ISSUE THREAD

**Issue by itsdebartha** [microsoft/vscode-jupyter#1709]
Issue Type: <b>Performance Issue</b>

I tried to install the ipykernel extension for python, but it seems that there is some problem with the download.

Extension version: 2020.8.103604
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:13:11.295Z)
OS version: Windows_NT x64 6.3.9600

it's showing this:
```
PermissionError: [Errno 13] Permission denied: 'C:/Users/DEEP'
'A~1' is not recognized as an internal or external command,
operable program or batch file.

```

**Comment by Rdk0** [comment]
Hi,
VSCode 1.50.1 on Win10
On running any .ipynb cell using conda's (conda 4.9.2) environment I am getting this message:
Python 3.8.6 64-bit ('teachopencadd': conda) requires ipykernel to be installed. 
then on attempting to install ipykernel this error message is displayed: IPyKernel not installed into interpreter Python 3.8.6 64-bit ('teachopencadd': conda).
The conda's environment has ipykernel  already installed. 
Thank you.

**Comment by greazer** [comment]
Unfortunately, this is a really old issue and we have been making changes related to getting ipykernel to install. These fixes may or may not address the problems indicated above, but because we haven't had the time to really investigate here, I'm going to close. If anybody can still repro the permissions problem that started this issue, please reopen it. 

Thanks, and sorry for not being able to get to this for so long.

**Comment by SheldonCurtiss** [comment]
Just had this start for me :/
