### ISSUE TITLE
python.dataScience.textOutputLimit does not work

### ISSUE THREAD

**Issue by simonm3** [microsoft/vscode-jupyter#1739]
This setting does not work. I get the message below. I have already set it to 0 but still the same message. I also increased max output size already.

Output was trimmed for performance reasons.
To see the full output set the setting "python.dataScience.textOutputLimit" to 0.
...

**Comment by aaronlee28** [comment]
How do you change the setting? I searched for it on the setting bar tab and I could not find it still.

**Comment by rchiodo** [comment]
The setting is here now:

![image](https://user-images.githubusercontent.com/19672699/110824907-5594bf80-8248-11eb-91de-08e1a7f951bd.png)

However it depends upon which UI you have. If your notebook looks like this:

![image](https://user-images.githubusercontent.com/19672699/110825093-8674f480-8248-11eb-9300-f2ca9700099f.png)

Then those settings apply. 

If your using the new UI:

![image](https://user-images.githubusercontent.com/19672699/110825147-97be0100-8248-11eb-89dc-783cdfc110db.png)

Then they don't.

**Comment by aaronlee28** [comment]
Hi rchiodo, 

My UI looks like this: 
![Screen Shot 2021-03-12 at 1 52 48 PM](https://user-images.githubusercontent.com/75769661/110903797-90772000-833a-11eb-96a0-960b302e857b.png)

But as you can see the output is still really long and I cannot scroll through it whatsoever. 

This is the setting that I have: 
![Screen Shot 2021-03-12 at 1 55 49 PM](https://user-images.githubusercontent.com/75769661/110903861-ac7ac180-833a-11eb-8b6a-3c3fdcbbe0d2.png)

Please let me know what else I could do so that my output could be scrollable. Thank you again!

**Comment by rchiodo** [comment]
I'm wondering if it's whatever your generating. It may not be the 'text/plain' type. 

For me I have this set:

![image](https://user-images.githubusercontent.com/19672699/110980006-38302600-831a-11eb-96d6-06c28e63d17e.png)

And this code here generates a scrollbar

![image](https://user-images.githubusercontent.com/19672699/110980056-454d1500-831a-11eb-8979-f10e2e2f5227.png)
