### ISSUE TITLE
IPyWidget tests randomly fail

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#238]
## Environment data

-   VS Code version: XXX
-   Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
This is still happening. My current theory is that the execution fails because the correct cell is not selected.

**Comment by DonJayamanne** [comment]
> This is still happening. My current theory is that the execution fails because the correct cell is not selected.

How about splitting the cells into separate notebooks & using the commands run all, might be less flaky, as we tests separte notebooks instead of output of individual files.

**Comment by joyceerhl** [comment]
Was just looking at this as part of investigating https://github.com/microsoft/vscode-jupyter/issues/3955. If I manually run the ipyvolume notebook, the first cell actually does take a fair bit of time to run, so I'm not surprised that we sometimes timeout waiting for the cell to execute. I noticed that at least for the ipyvolume test, we have retry logic for the part where we verify the outputs, but we don't retry execution if that times out. I tried moving the cell execution into the retry for the ipyvolume test since that seems to be the one that times out the most often, if that helps and sounds like a good idea we can maybe consider doing this for the other tests.

**Comment by DonJayamanne** [comment]
> g the cell execution into the retry for the ipyvolume test since that seems to be the one th

Helps to have a new pair of eyes looking into a problem..

**Comment by joyceerhl** [comment]
Ah, I see now that the retry logic was there because we don't always know whether the widget has finished rendering. I still think moving the cell execution into the retry is a good idea since the output sometimes fails to show up, but might contribute to more tests timing out after the 3 min limit.

**Comment by DonJayamanne** [comment]
But doesn't that mean we're still not sure why its timing out.
Still not convinced with the fix. The fix just means output didn't appear for some reason (i.e. cell execution didn't work as expected)hence the retry of the entire execution, but that means we're masking a bigger issue of cell execution not working.

**Comment by joyceerhl** [comment]
Agreed, I don't have a root cause for why the output sometimes fails to show (and unfortunately it doesn't repro reliably). I guess the question to ask is whether the widgets are just flaky in general or if there's some problem with how we update cell output.

**Comment by joyceerhl** [comment]
Update: there are three failure types I have seen based on past GHA run logs: 
1. Timeout after 3min: this is associated with a 'Failed to load resource net::ERR_CONTENT_LENGTH_MISMATCH' error. Not sure what the root cause of this is. Don had submitted a PR that we thought would fix this but it's still cropping up. This is the most common failure case.

2. rendered_execution timeout. I cannot repro this yet. Just need to add more logging.

3. AttributeErrors in the output. That one as far as I can tell is the CDN not responding with the script source. This is the least common failure and also the one we can do the least about.
