### ISSUE TITLE
Remote jupyter server connections for Native Notebook

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#254]

**Comment by DonJayamanne** [comment]
* For GA at a minimum get feature parity
	* Get estimate
* Nice to have for experiment (based on estimate)

**Comment by DonJayamanne** [comment]
Notes from https://github.com/microsoft/vscode-jupyter/issues/4328

Here's a temporary solution outlined by @ayim (temporary = Old notebook experience in Native notebooks without the full blow remote experience)


The Jupyter Server entry point that used to be located here: 
![image](https://user-images.githubusercontent.com/10951869/103951208-1dabb780-50f3-11eb-997e-6a39646dc06a.png)

Will be moved to the global status bar in Native Notebooks since the original entry point is no longer available.
![image](https://user-images.githubusercontent.com/10951869/103958685-79ca0800-5102-11eb-8e9a-784bfc7e73c8.png)

All functionality should remain the same - this will help achieve experience parity in native notebooks.

**Comment by claudiaregio** [comment]
https://github.com/microsoft/vscode-jupyter/issues/1206

Use as inspo

**Comment by ayim** [comment]
### Parity UI/UX experience

Prototype Link (all users with MS SSO should be able to sign in): https://www.figma.com/file/OGTDR9c9U5sFemy6xMlaE2/Visual-Studio-Code-Toolkit-Community?node-id=91%3A627

**Screen: Local**
![Local](https://user-images.githubusercontent.com/10951869/105392940-a2590400-5bd0-11eb-91b5-0b4425a3f13e.png)
**Screen: Local / Connections**
![Local _ Connections](https://user-images.githubusercontent.com/10951869/105392947-a38a3100-5bd0-11eb-9786-6a41abfe4f5d.png)
**Screen: Local / Connections / URI**
![Local _ Connections _ URI](https://user-images.githubusercontent.com/10951869/105392951-a4bb5e00-5bd0-11eb-8b63-5d54f897596c.png)
**Screen: Remote**
![Remote](https://user-images.githubusercontent.com/10951869/105392965-a84ee500-5bd0-11eb-96e0-c4940bc18849.png)
**Screen: Remote/Connections**
![Remote _ Connections](https://user-images.githubusercontent.com/10951869/105392969-a9801200-5bd0-11eb-8c3c-200b7fd4c8f7.png)

**Prototype in Image Form**
**Local Flow:**
![image](https://user-images.githubusercontent.com/10951869/105393156-ddf3ce00-5bd0-11eb-91d0-1e7c736fb306.png)
**Remote Flow:**
![image](https://user-images.githubusercontent.com/10951869/105393217-f237cb00-5bd0-11eb-9b8c-2b4b9c98b109.png)

**Comment by Reapor-Yurnero** [comment]
Hi there. The ideal workflow in my mind would be we open up a remote jupyter notebook in VSC just like what we do when normally open it in a browser: we can see a tree view of the files and can see running kernels/notebooks, and we can edit it directly, but with the strong feature language server and other plugins of VSC

**Comment by IanMatthewHuff** [comment]
@DonJayamanne This was just marked needs-triage, but it seems like work that was already done? Leaving open for now.

**Comment by ejkitchen** [comment]
I came here from StackOverflow: https://stackoverflow.com/questions/59765486/vscode-remote-jupyter-notebook-open-an-existing-notebook-in-a-specific-folder

I am confused by this thread from 2 years ago. Does VS Code support opening remote notebooks now or is this still in the "enhancement" request phase? I am also confused as a user that I am able to connect remotely to a notebook server but how do I retrieve my notebooks that are already there? Is this only for people who have local notebooks but for some reason want to have them run remotely on more powerful hardware???

**Comment by rchiodo** [comment]
@ejkitchen there are multiple ways to use remote.

If you want to use remote hardware (because maybe the GPU is more powerful), but don't need your files on the remote machine,  then you would use this command:

![image](https://user-images.githubusercontent.com/19672699/153914388-6c6bbe32-2554-44da-be69-ae36e01f4d74.png)

That connects to a remote jupyter server but does NOT copy any files to the remote machine.


If you want to connect to a remote machine and see all of the files in VS code, then you'd use something like [Remote SSH](https://code.visualstudio.com/docs/remote/ssh). In the remote SSH scenario, a VS code server runs on the remote machine, serving up files to your local client. Kernels are run from this VS code server and can access all the remote files.

Our long term goal is to unify these two modes so they behave the same, but we haven't gotten that far yet.

**Comment by FlorinAndrei** [comment]
> Kernels are run from this VS code server

@rchiodo That doesn't work.

https://stackoverflow.com/questions/73408585/vscode-run-remote-jupyter-server-with-remote-notebook-files-all-on-same-remote

**Comment by FlorinAndrei** [comment]
Turns out, if you install the local extensions onto the remote server, it actually works. But there aren't many clues in the GUI that suggest that.

Anyway, I've figured it out, it's working now. Would be nice if these features were made more explicit somehow.

**Comment by Europium-152** [comment]
I think this feature would be really useful

**Comment by Reapor-Yurnero** [comment]
May I ask what is the current status of this feature. This seems to have been implemented but I'm not able to find any clues from the doc on how to use it.

**Comment by DonJayamanne** [comment]
Here are the docs https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_existing-jupyter-server

**Comment by Reapor-Yurnero** [comment]
> Here are the docs https://code.visualstudio.com/docs/datascience/jupyter-kernel-management#_existing-jupyter-server

That is very different than what is described here as I have mentioned. The goal here is to be able open up existing Jupyter notebook URL and edit files there through VSC as a replacement of the browser. The link you shared only uses the remote kernel. Any running notebook cannot be opened up in VSC with that manner.

**Comment by DonJayamanne** [comment]
You are looking for https://github.com/microsoft/vscode-jupyter/issues/1366
