### ISSUE TITLE
Open and save remote notebook files without using VS code Remote SSH

### ISSUE THREAD

**Issue by sym233** [microsoft/vscode-jupyter#2815]
# Description
Hi, I'm using VSCode to write ipynb files but can only open and save them locally.
I wish VSCode can access and save remote files by remote jupyter server, as Jupyter Notebook in browser can do.

I've read the docs for remote SSH and remote Docker extension, but that requires remote VSCode installed and is inconvenient. 

## Your Jupyter and/or Python environment

- Jupyter server running: Remote, in Docker image tensorflow/tensorflow:latest-py3-jupyter
- Extension version: 2019.10.41019
- VS Code version: 1.39.2
- Python version: Python 3.7.0 64-bit in host, Python 3.6.8 64-bit in Docker container
- OS: Windows 10 Pro 1903 x64 18362.418

**Comment by francisduan** [comment]
Hi I am facing a similar problem. My team is using a remote JupyterHub without SSH connection. We can set up the remote Jupyter configuration and run notebooks with server kernels. However, we cannot manage the JupyterHub file system within VS code, not can we use server kernels to run a whole repository locally. Is it possible to

1) make remote file management on Jupyter system possible, without SSH connection
Or
2) make local scripts able to communicate to each other, rather than to the server files

Thanks

**Comment by Reapor-Yurnero** [comment]
so there's no plan to support this currently?

**Comment by DonJayamanne** [comment]
We're looking into adding support for remote vscode  without ssh in  here https://github.com/microsoft/vscode-jupyter/issues/254
Please feel free to upvote/add comments there.
