### ISSUE TITLE
Shift + Enter does not run a cell on native notebook

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#328]
It can run a cell in the terminal or do nothing.

Repro steps:

1. Open notebook
1. Create a new cell at the top
1. Add code
1. Hit shift ENTER

## Expected behaviour

Cell executes

## Actual behaviour

Nothing or it executes the cell in the terminal (cause python extension gets the shift+enter)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by nathancarter** [comment]
Extremely strong upvote to this one.  The absolute first thing any user tries is broken (from the user's point of view).

Doubly bad because, as far as I can tell, there doesn't even exist an action (!) for "execute cell and put cursor in next cell and/or make a new one" which is the default behavior in Jupyter itself.  The user literally has to choose one of these two workflows as a replacement for Shift+Enter:
 * Option 1:
     1. Ctrl+Enter to execute cell
     2. Esc to switch out of cell edit mode
     3. B to add a cell below
 * Option 2:
     1. Ctrl+Enter to execute cell
     2. Grab the mouse and click the ... button on the rightmost edge of the cell.
     3. Navigate to "Insert Cell" submenu, then "Insert code cell below" item.

Keep in mind that these workarounds are replacements for literally the most commonly executed keyboard shortcut in all of Jupyter, by a long shot.  I realize I'm being a bit blunt, but my mind boggles at a UX decision like this.  It's like putting the steering wheel in the glove compartment.

**Comment by rchiodo** [comment]
This is actually this bug here:
https://github.com/microsoft/vscode/issues/101436

which seems to have regressed? Our extension doesn't provide the shift+enter keyboard shortcut for the new notebook UI.

**Comment by rchiodo** [comment]
Okay actually it looks like this might be caused by the shift+enter from the python extension stealing shift+enter.

**Comment by rchiodo** [comment]
And this is not by design. It wasn't a conscious choice.

**Comment by nathancarter** [comment]
Glad to hear it! :) So is the easy workaround to turn off that keyboard shortcut in the Python extension?

**Comment by rchiodo** [comment]
Yes if you disable the shift+enter on the python extension, the keystroke is not stolen.

**Comment by nathancarter** [comment]
Excellent, I just confirmed that works.  Thanks for the super-fast reply!

**Comment by nathancarter** [comment]
Of course, I'm sure you're still interested in making sure that Shift+Enter works without this workaround, because in an educational context (where I work) you want first-time users (students) to just drop in and it works.  But this is great in the interim.

**Comment by greazer** [comment]
We need to detect if shift-enter is being invoked in the context of a native notebook.
