### ISSUE TITLE
[Feature Request] scroll past the end in Python Interactive window

### ISSUE THREAD

**Issue by StevenLi-DS** [microsoft/vscode-jupyter#3659]
## Environment data

- VS Code version: 1.30.2
- Extension version (available under the Extensions sidebar): 2018.21.1
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Anaconda Python 3.6
- Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda

## Actual behaviour

Unlike the code editor, the current version of the extension does not support scroll past the end in the Python Interactive tab. The only way to bring the output cells on the screen up is to run empty cell, which is a common practice in the data science community by people using Jupyter. People in the community have been requesting this feature of scroll past the end for a while.

I wonder if the vscode term can make this happen! 

![python_en](https://user-images.githubusercontent.com/33796896/51215993-d1a54e00-18f0-11e9-864b-dd346c40c7b4.gif)

**Comment by GitHunter0** [comment]
@rchiodo , I wish this feature was not implemented... Scrolling past the end in interactive window is incredibly annoying since I cannot see my last output when I press 'End' and I have to be always careful with the mouse wheel to avoid going past it, so that I can actually view my last output result.
Is there an option to revert back to the old behavior? 
Also related, is there an option to make the interactive window auto scroll to the last output regardless of the scroll position?
I believe these are little things that avoids a lot of nuisance, depending on the user preferences.
Thank you
