### ISSUE TITLE
DS: Support JupyterHub 

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#3684]
The Data Science vm uses JupyterHub to handle connections to it. We should support logging in via a user API token (different from server API token) to connect to the machine. After we support this we also need to support mismatched certs, as the DS VM only uses a local certification which might not be accepted unless we allow it.

**Comment by tristan957** [comment]
Was this just closed due to the inability to garner upvotes or was support implemented? Wondering because people on my team are curious. If it was the prior, is there any avenue to reopen? I see that this issue has reached the first page when sorted by upvotes as of 1/7/2021.

Otherwise I have read the Jupyter Blog post about using VSCode and JupyterHub and will link that to my team.

**Comment by rchiodo** [comment]
This should be working now. We implemented jupyterhub support last year sometime but didn't receive much feedback on it. (see this item: https://github.com/microsoft/vscode-jupyter/issues/2394)

We test it about once a month with a very simple setup so if it's not working there might be something missing. Please file a new issue if it's not working for you.

**Comment by tristan957** [comment]
@rchiodo thanks. I will let my team know :).
