### ISSUE TITLE
Can't change remote jupyter notebook kernel

### ISSUE THREAD

**Issue by mrober01** [microsoft/vscode-jupyter#3724]
Hi,
-pointed here from stackoverflow-
With the new version i am able to connect to a remote jupyter session and that works great, but there does not appear to be a way to change the remote kernel. This feature would be very helpful. 
Thanks,
Mike

**Comment by mparq** [comment]
Hi @DonJayamanne / @rchiodo, I see this issue is closed. We're trying to use a local docker container running jupyter in vs code and have the same issue regarding wanting to select different kernels on the remote server. Should this be possible now or is it possible in the new UI?

**Comment by rchiodo** [comment]
It should be possible. Remote kernel selection should work. For VS code stable anyway. VS code insiders is using something that doesn't have remote support just yet.

Please open a new issue if you're using VS code stable and you can't pick a remote kernel.

This is what it shows for me:

![image](https://user-images.githubusercontent.com/19672699/105427732-9f770700-5c02-11eb-99c6-af7c99c83de0.png)

Those first 3 kernels being already running kernels.

**Comment by mparq** [comment]
Ahh, you're right! I see what the issue was. I'm on VS code stable. I was using the functionality for running a cell directly from a `.py` file which was able to use the Jupyter Server I had configured from the jupyter extension.

From the `.py` file and the Interactive window, I can't see `Jupyter: Select a Kernel` in the command pallette, but if I export the `.py` file as an `.ipynb`, I do get that command and I can select remote kernels properly.

But this made me check back and it looks like I still have the kernel selection available through the UI in the python interactive window and I can select a kernel properly from there.

![image](https://user-images.githubusercontent.com/2523118/105440111-07921100-5c34-11eb-967e-38f7f2f75156.png)

Is it a bug that `Jupyter: Select a Kernel` isn't available in the interactive window? I can create a new issue if so.

**Comment by rchiodo** [comment]
> Is it a bug that ```Jupyter: Select a Kernel``` isn't available in the interactive window? I can create a new issue if so.

Yes seems like an over sight. Please enter an issue.
