### ISSUE TITLE
Interactive window doesn't open as default

### ISSUE THREAD

**Issue by dhhomie** [microsoft/vscode-jupyter#4007]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): v2020.11.371526539
-   OS and version: macOS Big Sur
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.4

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

1. Write codes in  .py file
2. Select lines and press `Shift`+`Enter`
3. Execute codes of lines in python interactive window (right side of editor as default)

[all I want to do](https://youtu.be/Q2jHMGod_rM#t=*1#17)

## Actual behaviour

1. Write codes in  .py file
2. Select lines and press `Shift`+`Enter`
3. Execute codes of lines in **Terminal** (bottom of editor), not interactive window

- still can use interactive window by right-click lines, or add cells by writing `#%%` in the head of codes
   - but I have used interactive window as **default**, just by pressing `Shift`+`Enter`, and want to do that way again
<img width="1280" alt="스크린샷 2020-11-23 오전 2 21 08" src="https://user-images.githubusercontent.com/45308756/99910915-3ffc9800-2d34-11eb-8cde-0e17ff0c127e.png">

- can't find `Python: Run Selected Line in Interactive Window` command in command palette, only have Jupyter's.
<img width="1280" alt="스크린샷 2020-11-23 오전 2 20 59" src="https://user-images.githubusercontent.com/45308756/99910916-412dc500-2d34-11eb-9b0e-53771a10e1a8.png">

- also can't find same command in Keyboard shortcut setting
   - Jupyter's command is set as shortcut(`Shift`+`Enter`) but it still doesn't work in .py files as default
<img width="1280" alt="스크린샷 2020-11-23 오전 2 21 39" src="https://user-images.githubusercontent.com/45308756/99910914-3c691100-2d34-11eb-91a7-01b55033c268.png">

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by joyceerhl** [comment]
Hi @dhhomie, sorry for the trouble here. We recently refactored the Python interactive window into the new [Jupyter extension for VS Code](https://devblogs.microsoft.com/python/introducing-the-jupyter-extension-for-vs-code/). This is why you're seeing 'Jupyter: Run Selection/Line in Interactive Window' instead of 'Python: Run Selection/Line in Interactive Window'--they are the same command, just under a different extension now.

For 
> Jupyter's command is set as shortcut(Shift+Enter) but it still doesn't work in .py files as default

we are working on fixing this and we are tracking it in https://github.com/microsoft/vscode-jupyter/issues/3993. Since we have an existing issue for this problem I'll be closing this issue--feel free to reopen if you feel that they are not related. Sorry again for all the trouble caused.
