### ISSUE TITLE
GUI changes

### ISSUE THREAD

**Issue by manojbaishya** [microsoft/vscode-jupyter#4013]
Hi, I am suggesting below five changes for the notebook (coming from a MATLAB/Spyder environment):

1.  A duplicate Variable Viewer pane in the Explorer sidebar with Name and Type columns only. (The original remains for a more "detailed peek").

![image](https://user-images.githubusercontent.com/28330014/100074065-4c800e00-2e64-11eb-996e-67eaaf72d194.png)

2. An option to collapse the Plot Gallery overbar in the expanded Plots tab and also maybe shift to or create a duplicate pane in the Explorer sidebar.

![image](https://user-images.githubusercontent.com/28330014/100074401-b26c9580-2e64-11eb-987b-0f62fa5b00c0.png)

3. It might be a good idea to collect the above panes into a standalone Jupyter sidebar accessible from the activity bar.

![image](https://user-images.githubusercontent.com/28330014/100074716-18591d00-2e65-11eb-97eb-104c201fa218.png)

4. Line numbers in Jupyter code cells.

![image](https://user-images.githubusercontent.com/28330014/100074871-463e6180-2e65-11eb-8512-3b3ccb1f43e3.png)
 
5. Is it possible to have a dedicated IPython console for piping .py script files and storing the session variables in the Variable Viewer (like MATLAB or Spyder) so that I can work on a program output interactively? I used Code Runner extension and Interactive Notebook, but they seem cumbersome so I just open an IPython console, cd to my document folder and use ``` %run script.py ``` to run and ``` %whos ``` to inspect variables. This works fine but automating it will probably be more efficient.

If there are other issues mentioning these points, please link them here and close this!
If I need to mention more specifics, please tell me.

**Comment by IanMatthewHuff** [comment]
Hey @manojbaishya thanks for providing this feedback. It's well detailed and thoughtful. The slight tricky bit here is that we are currently in the process of moving over to a new UI for our notebooks. Previously VS Code did not have a built in notebook UI, so we created them via "webview" which are basically just a webpage that an extension can host in VS Code. VS Code is now creating a native notebook interface which we are moving over to using. Should have our notebooks much better matching the look and feel of VS Code.

https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

I'd suggest that you take a peek at how the new editors look and feel. I think that some of your suggestions might still apply. But since we are moving over to this new UI I know that we won't be fixing anything with our old webview based UIs unless it's a major breaking issue.

**Comment by manojbaishya** [comment]
Wow, I just tried the new notebook on insiders and it is very smooth, fast and feels like Colab! I am very happy to know that a new UI is in active development and more features are being integrated. Shall wait till it is released on stable. The lesser priority suggestions may be looked into later if not yet incorporated!

With the notebook, variable explorer, data viewer and plots window already implemented, if a synced editor + console tied to the variable exp. and a help pane is built, then VSCode with Python truly has the power to replace MATLAB or a dozen other tools out there, and combined with C++ tools there's not a need to use anything else!

**Comment by IanMatthewHuff** [comment]
@manojbaishya Glad that you like it! We're happy on our team as we get to do away with a large amount of custom code that we used to try to make the old webviews work like full vscode editor instances. We do have plans in the immediate future to move variables into a separate panel that can be docked where desired, and are adding a sidebar to hold new features, so both of those are already in the plans.
