### ISSUE TITLE
Error mgs on save notebook

### ISSUE THREAD

**Issue by felipetac** [microsoft/vscode-jupyter#4014]
Issue Type: <b>Bug</b>

When i save a change for jupyter notebook save but appear a msg: "Erro ao salvar 'ARQ.ipynb': Canceled" 

Extension version: 2020.11.372831992
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:31:29.624Z)
OS version: Linux x64 5.4.0-54-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2857)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|5.72GB (1.00GB free)|
|Process Argv|--no-sandbox --unity-launch --crash-reporter-id ef642c20-6a56-471d-9952-c1d3e56d1cb4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by IanMatthewHuff** [comment]
@felipetac Sorry about the issue here. To debug this, we're going to need a bit more information. In vscode settings could you set the Jupyter->Logging->Level to "debug." Then rerun your scenario that creates the save issue. After reproing the bug check out the "Jupyter" section of the output tab. And copy off everything in there. Just save that in a file and attach that file to a comment here. That info should have all our detailed debug output, which I'd need to dig in more here.

**Comment by DonJayamanne** [comment]
@IanMatthewHuff 
Sounds like a bug in VS Code for custom editor, see here for details of the original issue https://github.com/microsoft/vscode/issues/107190

Possible that fix is not yet in stable VS Code or its separate issue all together

**Comment by greazer** [comment]
This should be fixed in the next release of VS Code.
