### ISSUE TITLE
Markdown cell cannot display latex equation

### ISSUE THREAD

**Issue by zhuo931077127** [microsoft/vscode-jupyter#4039]
I input latex equation in markdown cell: 
![图片](https://user-images.githubusercontent.com/12757730/100517599-a2d3b080-31c6-11eb-912f-53e77bd6c8c8.png)
then run this cell, equation cannot be shown:
![图片](https://user-images.githubusercontent.com/12757730/100517622-d44c7c00-31c6-11eb-805e-797e3ca7f574.png)

**Comment by claudiaregio** [comment]
Hi @zhuo931077127, I am unable to reproduce at this time. 
![image](https://user-images.githubusercontent.com/19276747/100559423-758b0f00-3267-11eb-9324-0a08a0bbed05.png)

Are you using the Python Extension or just the Jupyter Extension? 

If you are using the Python Extension, can you please update to the latest version of VS Code and the Python Extension and let us know if the problem is still persisting?

**Comment by greazer** [comment]
@zhuo931077127, Please reopen if you are still able to reproduce this problem.
