### ISSUE TITLE
Jupyter doesn't respect workspace interpreter.

### ISSUE THREAD

**Issue by sarthak7gupta** [microsoft/vscode-jupyter#4094]
Steps to Reproduce-

1. Create a venv.
2. Select the environment as the python interpreter for your workspace.
3. Open a ipynb file.
4. Executing `import sys; print(sys.excecutable)` gives the global interpreter (/usr/bin/python3.8) rather than the selected environment (venv/bin/python)

**Comment by rchiodo** [comment]
This is actually by design. The notebook remembers the kernel you ran it with last time. It does not use the python interpreter in the lower left. 

You can change the kernel one of two ways (depending upon if you're using VS code stable or insiders):

For stable, it's here:

![image](https://user-images.githubusercontent.com/19672699/100943453-1f5ddc00-34b2-11eb-966a-4cae14a8f242.png)

For insiders, it's here:

![image](https://user-images.githubusercontent.com/19672699/100943507-3997ba00-34b2-11eb-9ee9-fcc681d6d114.png)

However if you create a blank notebook, it should default to the interpreter in the lower left. Additionally the interactive window (https://code.visualstudio.com/docs/python/jupyter-support-py#_python-interactive-window) will also start with the interpreter.
