### ISSUE TITLE
"python.autoComplete.addBrackets": true not respected into Notebooks

### ISSUE THREAD

**Issue by scollovati** [microsoft/vscode-jupyter#4158]
## Environment data

-   VS Code version: 1.51.1
-   Jupyter Extension version (available under the Extensions sidebar): ms-python.python
-   Python Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS (Windows | Mac | Linux distro) and version: W10
-   Python and/or Anaconda version: 3.8.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local 

## Expected behaviour

I would expect that tipying even a simple function like `print` will transform it into `print()` after pressing enter as it happens for `.py` files. "python.autoComplete.addBrackets" is set to true for the User (and Workspace, if used).

## Actual behaviour

Bracket autocomplete is not perfomed.

**Comment by IanMatthewHuff** [comment]
@scollovati Currently our jupyter notebooks are implemented using webviews, which are basically just a webpage hosted in vscode. We tried to line them up with how vscode works, but we don't respect every setting such at the add brackets setting. However we are moving over to using the new native VSCode interface for notebooks. In this interface we'll respect all vs code editor settings. 

https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/

You can currently preview this new UI (see above). I'm going to close down this issue, not because the issue doesn't exist (it does) but because the new UI will address this, and we don't intend to fix it for the old UI that we are moving away from.
