### ISSUE TITLE
Opened .ipynb files don't switch from JSON to Webview after extension install

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#4229]
Testing [Codespace Scenario: 1791](https://github.com/microsoft/vssaas-planning/issues/1791)

## Environment data

-   VS Code version: 1.52.0-insider (Codespace)
-   Jupyter Extension version (available under the Extensions sidebar): 2020.12.1
-   Python Extension version (available under the Extensions sidebar): 2020.11.2
-   OS (Windows | Mac | Linux distro) and version: Linux Codespace
-   Python and/or Anaconda version: 3.8.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

Opened .ipynb files automatically switches from JSON view to Notebook after installing the Python and Jupyter extensions (wasn't prompted for a reload).

## Actual behaviour

1. .ipynb file opened.
2. Prompted to install Python extension (no indication of Jupyter - we should be more clear about that dependency for now).
3. Finished installing and not prompted for a reloaded - extension commands work.
4. Opened .ipynb file remains in JSON form.

## Steps to reproduce:

[See above and reproduce in Codespace]

**Comment by greazer** [comment]
@SiddhanthUnnithan, since you were using vscode-insiders, you should be defaulting to vscode native notebooks when opening any ipynb. You should never see JSON or the old notebook UI. Can you try with the latest insiders? 

Also, if we ever break the dependency between Python and Jupyter extension, we'll consider re-messaging then. :)
