### ISSUE TITLE
Please add "Undo deleted cell" just like Jupyter has

### ISSUE THREAD

**Issue by noppGithub** [microsoft/vscode-jupyter#4310]
I can not see this feature being requested, but it is a very good one.

This feature allows you to get accidentally deleted cells back and save your coding time by alot.

**Comment by rchiodo** [comment]
Thanks for the suggestion.

We actually already support this. 

In VS code stable, you can hit the 'z' key to undo any delete (we got this from Jupyter's keyboard mappings). Make sure to move to 'command' mode instead of edit mode.

In VS code insiders, ctrl+Z will undo any action you previously performed.

**Comment by noppGithub** [comment]
Thanks
