### ISSUE TITLE
Native notebook cell language does not update when kernel is changed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4354]
1. Pick a non Python kernel 
2. Execute code
3. Switch to a Python kernel
4. Cell language marker is not updated even after editing the cell and executing Python code in the kernel

I'd expect us to update the language marker once we've run code in the selected kernel, since at that point we know what language that code is (expected to be) written in.

![image](https://user-images.githubusercontent.com/30305945/104362009-1bb57000-54c8-11eb-92de-3d508558226d.png)

**Comment by DonJayamanne** [comment]
I don't think that's the correct thing to do & I don't think this is a bug either.

I can have a cell with magics for a JavaScript or bash code or other, i could change the language to shell/javascript so i get syntax highlighting & intellisense.
Now just because i changed the kernel to another python kernel, all my cells are changed to Python after I changed it manually to get some features.
I.e. with the proposed change, I'd lost functionality.

I don't think we should change cell languages if kernel changes.

**Comment by DonJayamanne** [comment]
> Pick a non Python kernel
Execute code
Switch to a Python kernel

If the user changes kernels, then I'd leave it for the user to change languages. 
The example you have given doesn't seem to reflect a real world scenario, or does it. How did step 2 complete? (how did they end up with `Shell Script` as the language for the cells?
