### ISSUE TITLE
file tabs flickering, erratic behavoiur on opening notebooks

### ISSUE THREAD

**Issue by franciclo** [microsoft/vscode-jupyter#4405]
Issue Type: <b>Bug</b>

Whenever i open vscode ina project and open a jupyter notebook, some weird thing happen with the tabs, like my previous session was saved and vscode try to open all files at once suddenly and starts focusing in all files except the one i opened. This happens after opening the first notebook when i open vscode. I would prefer to have that tab session deleted, and start fresh.
Im using Ubuntu 20.04.

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 5.8.0-36-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7560U CPU @ 2.40GHz (4 x 3781)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|3, 1, 1|
|Memory (System)|7.42GB (0.73GB free)|
|Process Argv|--new-window /home/franciclo/Proyectos/ads-generator-resources --no-sandbox --crash-reporter-id cad370e1-7bca-49b0-b005-c9999176fde5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
openlogontheside:30221877
python383:30185418
pythonvspyt617:30244266
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30211401
wsl2promptcf:30224613
vstry244cf:30244300
pythonvsdeb440cf:30242243
unusedprompt:30224610
folderexplorer:30224614
openfilemenucf:30224648
pythonvsded773:30236629
pythonvspyt600:30241727

```

</details>

**Comment by IanMatthewHuff** [comment]
@franciclo Our current implementation of notebooks involves us using a webview to support the notebook editor. This approach has some limitations with how files interact with VS Code in general, leading to the behavior that you see. 

In the near future we're going to be moving over to VS Code's new native editor support for notebook like interfaces. If you install VSCode-Insiders today you will see this new interface by default. So we're unlikely to fix this issue in the current implementation that you see, but it should be resolved as we roll out the new interface. If you'd like to check it out just download VSCode-Insiders and take a look. 

I'm going to close this issue as we expect it to be fixed with the new interface rollout, if you disagree just comment back here and I can reactivate.
