### ISSUE TITLE
Conda enviroments that do not exists proposed every startup, buffer issues

### ISSUE THREAD

**Issue by PetrovskiIM** [microsoft/vscode-jupyter#4582]
Issue Type: <b>Bug</b>

Sometimes ctrl +x ctrl + v leads to nothing.

It is also every start of the jupyter extension ask for conda enviroment that i was deleted about 2 mounts ago EVERY SINGLE TIME! (i use different one every project).

Extension version: 2020.12.414227025
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:32:10.090Z)
OS version: Linux x64 4.15.0-135-generic snap

**Comment by joyceerhl** [comment]
Hi @PetrovskiIM, if you use this command from the command palette, "Jupyter: Select Interpreter to start Jupyter server", to pick a different environment as your kernel, does that resolve the issue? 

Otherwise, would you mind turning on debug logging by setting `jupyter.logging.level: "info"`, repeating the steps that cause us to ask for the old conda env, and providing detailed extension logs from the Jupyter output panel? Thank you!

![image](https://user-images.githubusercontent.com/30305945/106512579-a6194000-6486-11eb-9077-f06e8e413294.png)
