### ISSUE TITLE
Tests passing on PR validation but failing on CI

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#4597]
https://github.com/microsoft/vscode-jupyter/runs/1810903063
https://github.com/microsoft/vscode-jupyter/runs/1810908818

**Comment by IanMatthewHuff** [comment]
Hmm on those earlier builds there were some old variable view tests that I worry that I regresed. But I'm not seeing those on my most recent run here:
https://github.com/microsoft/vscode-jupyter/runs/1816585506

I just see:
`"before each" hook for "Notebook has 3 cells":1 | Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\uiTests\ipywidget.ui.functional.test.js)`

And

`"after each" hook for "Open notebook and interactive at the same time":1 | Timeout of 180000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\vscode-jupyter\vscode-jupyter\out\test\datascience\interactiveWindow.functional.test.js)`

Also looks like the failures all seem to be windows only (make sense since PRs run on ubuntu) to might need a windows box to investigate.
