### ISSUE TITLE
`api/contents` fetch fails due to not including token

### ISSUE THREAD

**Issue by Joelbear5** [microsoft/vscode-jupyter#4611]
After adding a server with `https://DOMAIN.com/user/USERNAME/?token=XXXXXX` I get this error when creating an interactive window as it doesn't seem to append the token to the `/api/contents` API fetch. If I manually append my token in a web browser, the API request is successful. Without the token it forwards me to the Jupyterhub login page.  I have installed all certificates in the chain, set `"http.proxyStrictSSL": false` and `"http.systemCertificates": true`. This seems to be an incorrect error message and the bug is the lack of appending the token.

`https://DOMAIN.com/user/USERNAME/api/contents/?2612345551295 failed` This looks like it needs `&token=XXXXX` appended to it.

Using version `v2020.12.414227025`.
`OUTPUT: Jupyter`
```
Error 2021-02-02 14:39:11: Failed to change kernel [FetchError: request to https://DOMAIN.com/user/USERNAME/api/contents/?2612345551295 failed, reason: unable to verify the first certificate
	at ClientRequest.<anonymous> (c:\Users\USERNAME\.vscode\extensions\ms-toolsai.jupyter-2020.12.414227025\out\client\extension.js:1:402412)
	at ClientRequest.emit (events.js:228:7)
	at TLSSocket.socketErrorListener (_http_client.js:406:9)
	at TLSSocket.emit (events.js:223:5)
	at emitErrorNT (internal/streams/destroy.js:92:8)
	at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
	at processTicksAndRejections (internal/process/task_queues.js:81:21)]
```

**Comment by IanMatthewHuff** [comment]
@Joelbear5 Sorry about the issue here. Could you do one thing here for me? If you set the setting Jupyter: Logging->Level to debug and then re-run the connection scenario that leads to this issue. Then after that, you can copy out the full contents of the Output: Jupyter tab. Now there should be much more in there, you can save that to a file and paste it in a comment here. That has our extra logging output and would make diagnosing this easier on our end. I'm not sure if this is actually a token issue or not, as I believe in some cases we don't display the token in our output logging such as the Error message that you see above.

**Comment by joyceerhl** [comment]
Closing as this issue has been inactive for >1 month. Please feel free to comment/reopen if you'd like to follow up. Thanks for reporting a bug!
