### ISSUE TITLE
Why does Jupyter show an error saying it requires ipykernal

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4619]
Originally reported https://github.com/microsoft/vscode/issues/115080

The plot draws, why is it complaining? I got hammered with 4 notifications after installing the extension.

![image](https://user-images.githubusercontent.com/2193314/105875117-40264780-5fb2-11eb-94a5-21772535f0e5.png)

**Comment by rchiodo** [comment]
@Tyriar do you have repro steps? That should only happen if you attempt to run a cell. If you attempted to run a cell that's expected. If you didn't then there's a bug.

**Comment by Tyriar** [comment]
I did not attempt to run a cell at that point, repro was basically just install the jupyter extension and open the notebook in https://github.com/microsoft/vscode/issues/114969. I didn't have the python extension installed and my Python 2.7 install seemed to be somewhat corrupted because pip was missing.

**Comment by rchiodo** [comment]
Here's the text content of the notebook.
https://github.com/microsoft/vscode/files/5870534/plotly.txt

**Comment by rchiodo** [comment]
I'm not reproing with our latest but there is a problem if I try and run without the python extension. I can't get a kernel to start. I'll log a separate bug for that though.
