### ISSUE TITLE
Stop execute cell doesn't want to work

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#4620]
Originally reported in https://github.com/microsoft/vscode/issues/115083

This may be because I don't have the python kernel installed. It should error out and stop itself immediately if so.

Also can stop be instant regardless? Do we need to wait for feedback to stop as that will cause the UI to feel sluggish, a better approach generally imo is to trust it will stop and present some error if something failed.

![recording (37)](https://user-images.githubusercontent.com/2193314/105875968-4ec12e80-5fb3-11eb-90e3-a9a743362cbe.gif)

**Comment by rchiodo** [comment]
This is by design. Stopping a cell sends an interrupt to Jupyter. Jupyter is not guaranteed to interrupt/stop the cell. See this issue:
ipython/ipython#3400

If we immediately stopped the cell and didn't show it being still busy, when you ran another cell you'd be wondering why it wasn't running (the kernel would still be busy from the original stop).
