### ISSUE TITLE
Run Cells Above & Below should be an icon in Cell Toolbar

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#4644]
<img width="652" alt="Screen Shot 2021-02-03 at 18 01 04" src="https://user-images.githubusercontent.com/1948812/106834226-dfe67400-6649-11eb-81d5-bc52d6aa3ffd.png">

Other icons we see today for cells..
![Screen Shot 2021-02-04 at 09 52 46](https://user-images.githubusercontent.com/1948812/106935583-62197b80-66d0-11eb-80b1-494b9ba18d37.png)

As a user when I'm on a cell, and I want to run all cells above the current cell or below, then I need to move my mouse all the way up to the toolbar to click on those corresponding icons.

Ideally these icons should be on the Cell Toolbar, i.e. the icons should be next to the cell i'm working on. Just like Run Cell, Stop Cell, Delete cell icons are next to the cell.

**Comment by jaymegordo** [comment]
@DonJayamanne are all these options in an unreleased version? I'm on the newest vscode-insiders with native notebooks, but my menu bar icons only look like this:
<img width="283" alt="Screen Shot 2021-02-04 at 10 43 15" src="https://user-images.githubusercontent.com/29611875/106940085-f5a17b00-66d5-11eb-82c7-049516b94de5.png">

I ask because I've really been hoping for the "run all cells above" functionality back in the nn. Thanks!

**Comment by claudiaregio** [comment]
The run all above/below was placed in the notebook toolbar to mirror the notebook toolbar from stable. The icons could be moved to the cell toolbar but could be potentially resolved by VS Code. https://github.com/microsoft/vscode/issues/105183

**Comment by claudiaregio** [comment]
Also waiting on the response to this first: https://github.com/microsoft/vscode/issues/114927

**Comment by greazer** [comment]
Need to make sure we get SVG's added so that we can do this in the next stable release of VS Code.

**Comment by joyceerhl** [comment]
Validated:
![image](https://user-images.githubusercontent.com/30305945/113433378-f1bb6d80-9393-11eb-8884-b21eaae19b87.png)
