### ISSUE TITLE
More frequent updates?

### ISSUE THREAD

**Issue by coxackie** [microsoft/vscode-jupyter#4690]
Although there is a huge amount of work and commits in this repo, there has not been an official update for the extension for almost 2 months now. Could there be more frequent version updates, if possible, so we can faster enjoy bug fixes and new functionality?

**Comment by joyceerhl** [comment]
We'll be releasing a February update in a couple weeks. With the exception of January (due to most of our team being off for the December holiday season), we generally release on a monthly cadence. Hope this helps and thanks for your patience!

**Comment by coxackie** [comment]
Many thanks, @joyceerhl your work is very much appreciated!

**Comment by XiaomoWu** [comment]
@coxackie You can download the latest (not officially released) version from [here](https://github.com/microsoft/vscode-jupyter/actions/runs/544120289). A lot of features have been added, e.g., variable viewer, *persistent* remote kernel, scrolling, etc.

**Comment by MichaelSteurer** [comment]
> @coxackie You can download the latest (not officially released) version from [here](https://github.com/microsoft/vscode-jupyter/actions/runs/544120289). A lot of features have been added, e.g., variable viewer, _persistent_ remote kernel, scrolling, etc.

Thanks for the pointer. Unfortunately, it fails when opening a notebook with the new interface. When I try to open it with "Jupyter Notebook (preview)" I get this error:

`Cannot open resource with notebook editor type 'jupyter-notebook', please check if you have the right extension installed or enabled.`

Same happens when I compile the extension on my own. Running on most recent Code Insiders. Extension from the marketplace (December release) works fine.

**Comment by rchiodo** [comment]
@MichaelSteurer your issue with the insiders build is this one:
https://github.com/microsoft/vscode-jupyter/issues/4719

If you reopen the file it should open.

**Comment by MichaelSteurer** [comment]
Thanks @rchiodo. It's fine now.
