### ISSUE TITLE
Support cell sync between python script and interactive window. (was: python code with cell magic and "compiled" notebook split-view)

### ISSUE THREAD

**Issue by tobiasbj** [microsoft/vscode-jupyter#4721]
_Note: This feature request might have been created before, but I didn't not find it while searching. I however did not know which key words were the most fitting._

I would like a feature like they have in intellij where you can have the python code (with cell magic and markdown) of the notebook on one side and the compiled notebook on the other side.

**Here is an example from intellij**
![image](https://user-images.githubusercontent.com/7911343/107419866-8fbf5400-6b18-11eb-997e-fd3292c0fd8f.png)
( [The picture is from here](https://www.jetbrains.com/help/idea/running-jupyter-notebook-cells.html) )

It would be nice to actually also add the code block for each of the code output cells to, so basically recreating a standard notebook from python code with cell magic.

This is a "magic" feature which would make me use notebooks much more than I do, because using the standard "compiled" notebooks for coding is quite slow imo.

Feel free to suggest a better name for this feature suggestion.

**Comment by IanMatthewHuff** [comment]
@tobiasbj Thanks for the suggestion. Just to make sure that I'm tracking your suggestion correctly we currently have the two following options in VS Code
1. A standard notebook interface with output interleaved with code cells
2. The interactive window, where cell markers and magics live in .py files. And the output history of what you have executed is hosted in a split window.

What you would like is more like our current interactive window. But instead of the split interactive window hosting a history of execution (if you run a cell five times in a row you would see 5 outputs in the window) the cells would be tied one to one with a single output cell per code cell in the .py file. Is that a correct understanding?

**Comment by tobiasbj** [comment]
@IanMatthewHuff Yes, that is exactly what I'm suggesting (and hoping for). Sorry for my poor explanation.

**Comment by IanMatthewHuff** [comment]
@tobiasbj No your suggestion was quite clear. Just with user enhancements I always like to make sure that we've confirmed what the user is looking for to make sure that we exactly understand them.

I personally do like this suggestion. I generally prefer working with the Interactive Window myself and using .py files and the 1:1 mapping sounds like a good suggestion on this.

**Comment by amunger** [comment]
closing as duplicate
