### ISSUE TITLE
Can't create or open Jupyter Notebook with VSC insiders

### ISSUE THREAD

**Issue by aisbergde** [microsoft/vscode-jupyter#4819]
Issue Type: <b>Bug</b>

it is not possible to open or to create a jupyter notebook in the current 
Cannot read property 'code' or 'markdown'
in the "normal" VCS jupyter notebooks are working.

Extension version: 2020.12.414227025
VS Code version: Code - Insiders 1.54.0-insider (a699ffaee62010c4634d301da2bbdb7646b8d1da, 2021-02-15T05:17:48.792Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (5.89GB free)|
|Process Argv|--crash-reporter-id a200e218-da5e-491f-adc2-d0355fa904c7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30251590
core-portspanel:30233467
coreuntitledfile:30249963
wslfolderdoc:30257224

```

</details>

**Comment by joyceerhl** [comment]
Hey @aisbergde sorry for the trouble. This is happening because there was a breaking change to the VS Code notebooks API in the latest VS Code Insiders update, and the Jupyter extension team is working on publishing a compatible version of the extension to the marketplace. I apologize for the trouble. In the meantime you can work around this by downgrading VS Code as described in https://github.com/microsoft/vscode-jupyter/issues/4796#issuecomment-779266138. Closing this issue as we're tracking the same problem in https://github.com/microsoft/vscode-jupyter/issues/4796, please subscribe to that issue for updates.
