### ISSUE TITLE
Is there anyway to cut and paste cells?

### ISSUE THREAD

**Issue by dclong** [microsoft/vscode-jupyter#4887]
I'd like to be able to cut and pasts cells (best to support cut and paste multiple cells at a time). 

There's an existing close issue https://github.com/microsoft/vscode-jupyter/issues/2131. 
However,
the feature doesn't seem to be implemented based on discussion in the issue.

**Comment by DavidKutu** [comment]
Thanks for reaching out @dclong. The reason that issue is closed is that copy/paste is implemented on our new notebook experience. Its not out in stable yet, but you can use it with VS Code insiders (https://code.visualstudio.com/insiders/).

Once you open a notebook in insiders it should look like this:
![image](https://user-images.githubusercontent.com/20347396/108781991-a3f35000-751f-11eb-8b0b-978eb880d822.png)

Let me know if you can use it.

**Comment by dclong** [comment]
@DavidKutu, Thank you very much for the explanation! Will give the insider version a try.
