### ISSUE TITLE
vscode  does not work with jupyter /Cannot read property 'then' of undefined /jupyter server is not starting

### ISSUE THREAD

**Issue by pleabargain** [microsoft/vscode-jupyter#4976]
## Environment data

-   VS Code version: - Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:44.518Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.4.0-66-generic snap
-   Jupyter Extension version (available under the Extensions sidebar): XXX
- Jupyter
ms-toolsai.jupyter
Microsoft
9,948,266
Repository
License
v2021.2.603412351
Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.

-   Python Extension version (available under the Extensions sidebar): XXX
- Python
ms-python.python
Microsoft
v2021.2.582707922
-   OS  Linux distro) and version:ubuntu 20.04
- 
- python3 --version
Python 3.8.5
-   Type of virtual environment used N/A 
-   Jupyter server running: Local 
jupyter server is not starting!

## Expected behaviour
ctrl + enter to run cell
run code

## Actual behaviour
error:
Cannot read property 'then' of undefined /jupyter server is not starting

## Steps to reproduce:

a = "test"
print(a)

no output/ jupyter server does not start
https://i.imgur.com/dHcMDYm.png

![vscode does not work with jupyterPeek 2021-02-28 15-37](https://user-images.githubusercontent.com/640846/109420447-39d52200-79db-11eb-9932-65d992420532.gif)

**Comment by joyceerhl** [comment]
Hi @pleabargain sorry for the trouble. You appear to be clicking on the local/remote kernel picker. Could you instead try clicking on the rightmost text which says 'Not started' in your GIF above? That should allow you to pick a working kernel.

Additionally, could you please copy and paste debug logs from the Jupyter output tab into a new comment below? This will help us identify why the kernel is failing to start for you. To get full logs, add the following setting to your user settings.json:
>"jupyter.logging.level": "debug"

Then reload VSCode for the new setting to take effect, and you'll be able to find debug logs in the Jupyter output tab:
![image](https://user-images.githubusercontent.com/30305945/109401262-8b5dae00-7902-11eb-8b4e-638a31e7de16.png)

Thank you!

**Comment by pleabargain** [comment]
thank you for the quick reply
I enabled debugging

Jupyter kernel still not starting
no  option to launch Jupyter in terminal

log and gif attached.


![kernel not starting Peek 2021-03-01 08-49](https://user-images.githubusercontent.com/640846/109462173-c29b9e80-7a6b-11eb-8b6a-b54d01268d3e.gif)
[jupyter.error.log](https://github.com/microsoft/vscode-jupyter/files/6059633/jupyter.error.log)

**Comment by pleabargain** [comment]
And FWIW, I cannot save the ipynb file either.

**Comment by DonJayamanne** [comment]
The error is in line `115` we are assuming the value always exists.
![Screen Shot 2021-03-02 at 08 39 02](https://user-images.githubusercontent.com/1948812/109681877-c3e3ce80-7b32-11eb-9f86-008279f21998.png)

**Comment by DonJayamanne** [comment]
@pleabargain 

* Please could you install the following VSIX (our latest development build)
* https://github.com/microsoft/vscode-jupyter/suites/2218332130/artifacts/45926429
* Downlaod the VSIX
* Go into your command palettet and select `Install from VSIX`
* You might have to reload
* Let me know if this fixes your issue

Thanks

**Comment by lesteve** [comment]
I had the same issue here is my stack trace to prove it (the error does happen in listKernelSpecs as hinted above):
![image](https://user-images.githubusercontent.com/1680079/111573263-790cbc80-87aa-11eb-96dd-470c5f5e552b.png)

It seems that for me switching from VS Code 1.54.3 to VS Code insider fixed it. I have used the Jupyter extension on the standard VS Code version for a while without any issues. Is it a new thing that the VS Code Insiders is needed?

For completeness, I tried installing the vsix posted above but I got the error (not sure whether this is expected since I am not that familiar with the VS Code ecosystem):
```
Unable to install extension 'ms-toolsai.jupyter' as it is not compatible with VS Code '1.54.3'.
```

## More details

The version of the extension is not the same in both setups, not sure why because I am not that familiar with the VS Code ecosystem:

VS Code: 2021.3.619093157
VS Code Insiders: 2021.4.641214696

### Error on VS Code 1.54.3

VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:24.277Z)
OS version: Linux x64 4.15.0-133-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3813)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.55GB (3.68GB free)|
|Process Argv|--no-sandbox --crash-reporter-id e0426f7e-f5ef-4e44-8d08-c03253e881b8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.658691958
jupyter|ms-|2021.3.619093157


</details>


### Working with on VS Code insiders 

VS Code version: Code - Insiders 1.55.0-insider (b353f063393226ffc0e70f6b1afe3f362734071e, 2021-03-17T08:39:19.891Z)
OS version: Linux x64 4.15.0-133-generic snap

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 3679)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.55GB (3.34GB free)|
|Process Argv|--no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2021.3.658691958
jupyter|ms-|2021.4.641214696


</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30263608
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30244316
pythonvsdeb440:30224570
pythonvsded773:30223139
pythonvspyt875:30259475
pythonvsnew554:30265444
pythontb:30258533
pythonvspyt943:30277000
vscoresta800:30265947
vspre833cf:30267465
vsfjg287:30275553
vshan820:30276952

```

</details>

**Comment by DonJayamanne** [comment]
@lesteve 
Please could you install VS Code Insiders and confirm this issue has been resolved. We believe this has been fixed. Thanks

**Comment by lesteve** [comment]
> Please could you install VS Code Insiders and confirm this issue has been resolved.

Yes, this is what I was trying to say in my previous post (maybe not clearly enough). To try to summarize in case it helps:
- I encountered the issue with VS Code 1.54.3
- Using VS Code Insiders did fix it indeed

**Comment by DonJayamanne** [comment]
> Using VS Code Insiders did fix it indeed

Woo hoo, thanks

> es, this is what I was trying to say in my 

Yes, going back i can see you did mention that. Sorry for asking again.
& thanks again for providing the feedback & validating the fix.

**Comment by IanMatthewHuff** [comment]
Validated by customer + stacktrace and code change.
