### ISSUE TITLE
Native notebooks: Changing the kernel of a notebook does not mark it as dirty

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#4998]
Change the kernel of a notebook
Reload VS code
Kernel will not be picked as the preferred kernel

**Comment by DonJayamanne** [comment]
I don't see the need for this.
The user hasn't run the cell, hence i don't see why we need to persist this.
This is deliberate.
If a user opens a notebook, a kernel is picked, we can't make it dirty, else every notebook that's opened can be marked as dirty just because the user opened a notebook.

I.e. we cannot differentiate between vscode opening & selecting a kernel vs user selecting a kernel & don't think we need to either. We haven't had users file issues against this.

**Comment by rchiodo** [comment]
I changed the kernel. That should be different metadata. Maybe I only opened it, changed the kernel, but then forgot to run it. It just looks inconsistent.

**Comment by DonJayamanne** [comment]
Works as expected today
