### ISSUE TITLE
Python Interactive Jupyter code cell debug not breaking  on Uncaught Exceptions 

### ISSUE THREAD

**Issue by fleming79** [microsoft/vscode-jupyter#5157]
Issue Type: <b>Bug</b>

The debugger is not pausing for uncaught exceptions.

define error_test.py
```
# %%
def test_error():

    a = []
    a[1]

test_error()
```
* in debugger check "Uncaught Exceptions"
* Click 'Debug cell'

The debugger does not stop on the uncaught exception and instead the interpreter reports the error:

![image](https://user-images.githubusercontent.com/1474668/111014716-2ffae800-83f9-11eb-9ad9-a6fc73b71118.png)

* in debugger check "Raised Exceptions:
* Click 'Debug cell'

The debugger correctly breaks at the error:
![image](https://user-images.githubusercontent.com/1474668/111014744-53be2e00-83f9-11eb-8051-7b48991174ea.png)

Ref: https://code.visualstudio.com/docs/python/jupyter-support-py

Extension version: 2021.2.636928669
VS Code version: Code 1.54.2 (fd6f3bce6709b121a895d042d343d71f317d74e7, 2021-03-11T00:56:19.848Z)
OS version: Windows_NT x64 10.0.19042

**Comment by joyceerhl** [comment]
Thanks @fleming79 I can reproduce the bug. Interestingly breaking on uncaught exceptions appears to work if test_error() is not the last line of code in the interactive cell:

![image](https://user-images.githubusercontent.com/30305945/111683035-441c5c00-87e2-11eb-960f-46725dc01dcf.png)

This seems like a discrepancy in the debug behavior between the Python debugger and the interactive window though it may be by design. Will discuss with team at our weekly triage.
