### ISSUE TITLE
 The conda command is either misspelled or could not be found.

### ISSUE THREAD

**Issue by willie14** [microsoft/vscode-jupyter#5213]
This is happening too many times ,I want to connect to my tensorflow from Jupyter I already installed , but there is always a message in my language :

"  021.3.658691958\pythonFiles\pyvsc-run-isolated.py c:/Users/willi/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/printEnvVariables.py Fatal Python error: init_sys_streams: can't initialize sys standard streams Python runtime state: core initialized....
The conda command is either misspelled or could not be found. ".

Please help me to recognize the error .

Thanks.

Regards,
Wili Eka

**Comment by claudiaregio** [comment]
Hi @willie14 
Could you please provide some additional details on the issue you are experiencing? Please fill out the template below 
-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

Other helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com)

**Comment by willie14** [comment]
Thanks for the reply ,

Before the answers to all yer questions....
I reinstalled the Jupyter notebook and try to install tensorflow.

> Hi @willie14
> Could you please provide some additional details on the issue you are experiencing? Please fill out the template below
> 
> * VS Code version: XXX
> * Jupyter Extension version (available under the Extensions sidebar): XXX
> * Python Extension version (available under the Extensions sidebar): XXX
> * OS (Windows | Mac | Linux distro) and version: XXX
> * Python and/or Anaconda version: XXX
> * Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
> * Jupyter server running: Local | Remote | N/A
> 
> Other helpful information includes steps to reproduce, expected behavior vs. actual behavior, pictures or screen recordings when applicable. (https://www.screentogif.com)
