### ISSUE TITLE
Add a 5 minute delay to feedback prompt

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-jupyter#5261]
To avoid too many notifications from the Python extension on load, we can add a 5 minute delay to display the notification asking for users feedback.

This is to avoid situations like the one below:

![image](https://user-images.githubusercontent.com/45497113/112235359-b5517a00-8bfb-11eb-9f50-24c9534030fe.png)

**Comment by greazer** [comment]
We don't think that this will work to address the core problem.

**Comment by luabud** [comment]
@greazer would you be able to clarify why is that? I created this issue after talking to @ronglums.

**Comment by ronglums** [comment]
@claudiaregio is aware too :) @greazer, I agree it doesn't address the core problem, but as the core problem is being worked on in parallel, this is a reasonable workaround for a nicer (less annoying) experience.

**Comment by greazer** [comment]
@ronglums, let's talk about this.

**Comment by greazer** [comment]
I don't trust that our notebook survey prompt is being displayed at appropriate times. Either our criteria wrong, too easy to hit, or suffering from a bug that is causing it to display way too early. I'd like to revisit the entirety of the mechanics from the ground up. If we have to change it completely, so be it.

There are a couple of non-debatable requirements and one mildly debatable one:
1) We don't prompt somebody who has already ever been prompted in the past. I think we have a memento set already that can allow us to make this a reality. If we can do this based on user rather than machine, that is best.
2) We don't ever prompt on simply opening an ipynb file regardless of whether any criteria metrics have been met in prior sessions or not.
3) Debatable: Our criteria should be based on actual serious use of the notebook features. I don't think it's worthwhile to query somebody who has only mildly tried it. 100 cell runs is not serious use, imo. I don't think that somebody who has spent a lot of time with our notebook support will be willing to spend any time filling out a survey. Even if they are, I'm confident the reasons that they are leaving so early can be gleaned via other means than a survey.

So, if possible, I would propose that our current criteria is greatly increased and/or replaced with or combined with a "total time user has had a notebook file opened in one or more sessions of VS Code". That time should be on the order of at least an hour. We need to be sure that at least some notebook operations are being performed during this time too. 

Then when we do prompt it shouldn't be before at least 20 minutes have elapsed after the user performed at least 10 cell runs in and one cell edit their current session.

**Comment by claudiaregio** [comment]
Based on our call: 
**For Native Notebooks (whether in Stable or Insiders)** 

- Prompt using same criteria.
- If user hits Yes, do not show prompt for 6 months. 
- If user hits No, do not show prompt for 3 months. 
- If user clicks x, treat it same as no. Do not show prompt for 3 months. 

**For Webview** 
- Prompt using this new criteria: 1. They opened 15 notebooks. 2. They ran at least 250 cells. 
- If user hits Yes, do not show prompt for 1 year. 
- If user hits No, do not show prompt for 6 months. 
- If user clicks x, treat it same as no. Do not show prompt for 6 months.

**Comment by joyceerhl** [comment]
Validated. Shows up for me after I open 5 notebooks, wait 10 minutes, then open another notebook.
