### ISSUE TITLE
Lose code when typing into interactive console

### ISSUE THREAD

**Issue by Nintorac** [microsoft/vscode-jupyter#5277]
## Environment data

-   VS Code version: 1.51.1
-   Extension version (available under the Extensions sidebar): 2021.2.633441544
-   OS and version: Debian Buster
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8
## Steps to reproduce:

1. Start typing test code in interactive console
2. Fat finger the up arrow key and the previous command is shown
3. No way to get back half typed code from step 1

**Comment by joyceerhl** [comment]
I do repro this behavior. I believe this is preexisting behavior, so this issue is a request to include the current input cell contents in the interactive window's autocomplete history.

**Comment by joyceerhl** [comment]
@Nintorac This is resolved in the new interactive window, which is currently the default in VS Code Insiders. Please let us know if it works for you!
![recording (2)](https://user-images.githubusercontent.com/30305945/126430771-c97e151d-c327-4a67-a7b4-829d7427326f.gif)

**Comment by ror3d** [comment]
Related to this:
Whenever writing in the interactive text input, if I mistakenly press Escape (because there was some auto-complete, or because I just am used to it from Vim to get to normal mode), the text is removed entirely, without a way to recover it; Ctrl-Z doesn't undo the removing of the text, which is quite disappointing.

I have found #2275 and #3406 seem to be asking for that specific feature (clearing the text), what I want is to remove it, but I am unable to find the mapped command in the Keyboard Shortcuts editor.

Can the fix to the current issue somehow also fix what I'm describing? Thanks

**Comment by joyceerhl** [comment]
@ror3d You're unable to find the mapped command because the previous implementation was webview-based, so the `esc` shortcut was hardcoded and non-configurable. We are currently planning to not bind `esc` to delete text in the native interactive window input box by default, because it introduces many conflicts with keybindings in VS Code core (e.g. Vim keybindings, suggestion widgets, and hover/tooltips). If anything we would provide a command that is unbound to any keyboard shortcut, which users can then configure a keybinding for if they wish.

**Comment by ror3d** [comment]
Ah that sounds great, thank you! is there somewhere I can find an ETA for that to be included in a release?

**Comment by joyceerhl** [comment]
@ror3d The new interactive window implementation is currently the default in Insiders, and assuming we receive no significant customer feedback in Insiders, we will be enabling it for all users in the upcoming Stable release as well. Please give it a try in Insiders if you can 😊
