### ISSUE TITLE
TQDM output looks odd after stderr stdout change

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#5299]
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/a1934967-be11-416b-9d89-3d563a7facf5)

With the new change to vscode handling stderr and stdout differently TQDM now looks funny. Per Don it is writing to stderr, so the red is expected. However the blue elements might either be writing to stdout or explicitly colored blue. Should investigate.

**Comment by greazer** [comment]
Seems more likely to be a core VS Code problem.

**Comment by DonJayamanne** [comment]
```pyhton
import sys
sys.stdout.write('stdout')
sys.stderr.write('stderr')
sys.stdout.flush()
sys.stderr.flush()
```

Here's the expected output from classic Jupyter:
<img width="606" alt="Screen Shot 2021-04-05 at 11 24 17" src="https://user-images.githubusercontent.com/1948812/113610065-7e1e9800-9601-11eb-961e-e0ea9cab15e0.png">


Requested change = Set background color instead of changing the foreground color.
Else it looks weird.

**Comment by DonJayamanne** [comment]
No longer an issue
