### ISSUE TITLE
Unable to work in existing and new Notebooks when connected to Azure ML remote compute.

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#5475]
@lafranke for visibility. Do you mind filling out some of the sections below where applicable (Jupyter extension version, ...)

## Environment data

Version: VSCode: 1.55.1
Platform: Windows 10
-   Jupyter Extension version (available under the Extensions sidebar): N/A
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Windows
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local on Azure ML Compute Instance

## Expected behaviour

Connect to Azure ML remote compute instance using the Azure ML extension and work in .ipynb files.

## Actual behaviour

![image](https://user-images.githubusercontent.com/6413608/114224423-e6cd8380-9925-11eb-9eef-54bf5ca832aa.png)

## Steps to reproduce:

1. Connect to remote compute instance.
2. Open existing .ipynb file or create new one.

## Logs

N/A

**Comment by lafranke** [comment]
Here my answers:


  *   Jupyter Extension version (available under the Extensions sidebar): v2021.3.684299474
  *   Python Extension version (available under the Extensions sidebar): v2021.3.680753044
  *   OS (Windows | Mac | Linux distro) and version: Windows 10
  *   Python and/or Anaconda version: on PC: conda 4.9.2, Python 3.8.3
  *   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
  *   Jupyter server running: Local on Azure ML Compute Instance
Cheers,
Laura

From: Sid Unnithan ***@***.***>
Sent: 09 April 2021 20:25
To: microsoft/vscode-jupyter ***@***.***>
Cc: Laura Franke ***@***.***>; Mention ***@***.***>
Subject: [microsoft/vscode-jupyter] Unable to work in existing and new Notebooks when connected to Azure ML remote compute. (#5475)


@lafranke<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flafranke&data=04%7C01%7Claura.franke%40microsoft.com%7C67eaf96dc0124047aca908d8fb84ca30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535895049951435%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=EmnLU8NneGpppVuS1ZERekqKHCBfMrMnoGGoTeNVgEI%3D&reserved=0> for visibility. Do you mind filling out some of the sections below where applicable (Jupyter extension version, ...)

Environment data

Version: VSCode: 1.55.1
Platform: Windows 10

  *   Jupyter Extension version (available under the Extensions sidebar): N/A
  *   Python Extension version (available under the Extensions sidebar): N/A
  *   OS (Windows | Mac | Linux distro) and version: Windows
  *   Python and/or Anaconda version: N/A
  *   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
  *   Jupyter server running: Local on Azure ML Compute Instance

Expected behaviour

Connect to Azure ML remote compute instance using the Azure ML extension and work in .ipynb files.

Actual behaviour

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F6413608%2F114224423-e6cd8380-9925-11eb-9eef-54bf5ca832aa.png&data=04%7C01%7Claura.franke%40microsoft.com%7C67eaf96dc0124047aca908d8fb84ca30%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637535895049951435%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aXbE9xHXnPHRiFjFFfLPHLfZG8U5nJ6m0v%2F6DnGvzj0%3D&reserved=0>

Steps to reproduce:

  1.  Connect to remote compute instance.
  2.  Open existing .ipynb file or create new one.

Logs

N/A

-

**Comment by joyceerhl** [comment]
Hi @lafranke sorry for the trouble here. Please could you upgrade to the latest version of the Jupyter extension and confirm whether the problem persists there? Additionally, would you mind providing the full log from the Jupyter extension output panel? You can find it at the bottom of VS Code in the terminal panel:

![image](https://user-images.githubusercontent.com/30305945/114463458-4d0e0c80-9b99-11eb-9e38-111fb6a15b02.png)

Thank you!

**Comment by greazer** [comment]
Issues labeled with "Info needed" are closed if we do not receive more information from the issue author in 2 weeks. If you are the issue author and you still are running into this problem, please reactivate with additional information.
