### ISSUE TITLE
Native Notebooks - Green Check + Timer after kernel restart should be removed

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#5481]
## Steps to Reproduce:
1. Open notebook
2. Run some cells
3. Clear outputs or restart kernel

## Actual Behavior: 
**If you clear all outputs:** 
Green check mark remains even though execution count is wiped

![image](https://user-images.githubusercontent.com/19276747/114314962-c16d8080-9ab1-11eb-9722-513edd79faa1.png)

This is especially weird if you delete the code before you clear all outputs. 
![image](https://user-images.githubusercontent.com/19276747/114315299-38574900-9ab3-11eb-9ec4-64c30fcc7398.png)

**If you restart kernel:** 
This looks identical to if I had actually just run it

![image](https://user-images.githubusercontent.com/19276747/114315270-12ca3f80-9ab3-11eb-8340-5b5488bb7973.png)

## Expected Behavior: 
No green check mark or timer in cell status bar when kernel is restarted or all outputs cleared

**Comment by roblourens** [comment]
This is now done correctly for clearing outputs. But for restarting, that would have to be done on the extension side with a fake execution event. I will give it back to you @DonJayamanne to decide whether it's right to clear those when the kernel is restarted. I have no idea how to do that in the extension codebase. But if you want me to tackle it you can point me to the right code

**Comment by DonJayamanne** [comment]
Jupyter has the following options:
* Restart
* Restart and Clear Outputs

The latter ends up clearing the execution count and the output. We do not have such an option.
I don't think we should remove the green tick and not clear the execution count, that would seem an incomplete behaviour.
I think we should instead have the first option (current behaviour which lines up with Jupyter) and the second option (new restart option)

This means we'd need a different restart button or a split dropdown button or the like.

Given the fact that this issue has been open for more than a year and we've only had 2 similar issues, I'm inclined to close this due to a lack of interest from users.
