### ISSUE TITLE
Restrict permissions on the `GITHUB_TOKEN` for GitHub Actions

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5591]
You can now restrict permissions on the `GITHUB_TOKEN` for GitHub Actions

Python team has done this, we should do the same.

**Comment by joyceerhl** [comment]
There's a GitHub app that we can configure to publish test results. However it also requires write access for checks:

![image](https://user-images.githubusercontent.com/30305945/120566383-fc11dc00-c3c3-11eb-8c9c-2651c8821682.png)

Is that preferable? If not, I would suggest we add the current GitHub Action to the allowlist and turn off write access for all other GitHub scopes.

**Comment by joyceerhl** [comment]
Reading through [this thread](https://github.community/t/publishing-test-results/16215), [this GitHub app](https://github.com/marketplace/test-check-publisher) is new since we last discussed this, but only supports third party CI. I think our options are to 
1. Enable write access for the current GitHub Action we use (https://github.com/ScaCap/action-surefire-report)
2. Write our own GitHub Action

**Comment by DonJayamanne** [comment]
Can we go with option 3. Restrict the permissions and then decide on 1 or 2 later.

**Comment by joyceerhl** [comment]
That would block us from viewing test output immediately. Given we're still working on tests now might not be the best time to fully restrict permissions? I'm in favor of just enabling write access for the current action, as follows:

![image](https://user-images.githubusercontent.com/30305945/120568950-cec82c80-c3c9-11eb-8303-59224c374743.png)

**Comment by DonJayamanne** [comment]
> That would block us from viewing test output immediately. Given we're still working on tests now might not be the best time

This will be the case every day, we will be looking at our tests in every pr.

**Comment by IanMatthewHuff** [comment]
Validated. Via GitHub settings.
