### ISSUE TITLE
Run cell and bellow & Run cells above not working

### ISSUE THREAD

**Issue by grudloff** [microsoft/vscode-jupyter#5636]
## Environment data

-   VS Code version: 1.56.0-insider
-   Jupyter Extension version: v2021.6.780948196
-   Python Extension version: v2021.5.756443519-dev
-   OS:  Windows_NT x64 10.0.19041
-   Python and/or Anaconda version: Python 3.8.8 & conda 4.9.2
-   Type of virtual environment used: conda
-   Jupyter server running: Local

Nothing happens when I click 'Run cell and bellow' or 'Run cells above'. Jupyter output doesn't log any new entry when doing either but seems to be working fine when clicking the run all button, or running cell by cell with 'enter+shift' or the run cell button.

**Comment by joyceerhl** [comment]
@grudloff If you first run a cell with shift+enter, then use the "run cell and below" button, does that work? "Run cell and below" isn't working for me either but I'd like to confirm that I'm seeing the same cause you're reporting. To me it looks like "Run cell and below" and "Run cells above" will not work if there's no active kernel for the current active notebook at the time that the command is invoked. 

![image](https://user-images.githubusercontent.com/30305945/116166922-f8e44b80-a6b3-11eb-9088-8dd75e885e04.png)

Instead I believe we'd want to start the kernel if one hasn't already started when "Run cell and below" or "Run cells above" are invoked. Though this is also likely happening because I don't believe we're autostarting kernels anymore after the latest notebook API changes landed.

**Comment by grudloff** [comment]
In my case, it doesn't work even when a cell has been run before and the kernel is already started.

**Comment by grudloff** [comment]
Doing the same in native jupyter notebook under the same environment works as expected without any issue.

**Comment by DonJayamanne** [comment]
@joyceerhl the fix is pretty simple we need to call `getOrCreate` instead of `get`.

**Comment by joyceerhl** [comment]
Validated. Run cell and below and Run cells above are working in the latest VSIX off the release branch.

**Comment by grudloff** [comment]
Seems my problem was unrelated. I am still experiencing the same issue.

**Comment by joyceerhl** [comment]
@grudloff This fix will become available in the next release that we publish. Can you try this temporary VSIX out (should already contain the fix) and let us know if the problem persists? https://github.com/microsoft/vscode-jupyter/suites/2626147023/artifacts/57578598

**Comment by grudloff** [comment]
Hello @joyceerhl. Thanks for the help but sadly the issue still remains.

**Comment by grudloff** [comment]
Hello, it seems the Run cell and bellow & Run cells above was added on the last version (I don't remember seeing those in the insiders version at least) and for some reason using the buttons works perfectly for me but doing the same through right-clicking or selecting the "..." and then selecting either option is still doing nothing.

**Comment by grudloff** [comment]
Normal VS Code was working fine for me.
