### ISSUE TITLE
Matplotlib IPyWidgets is very slow in codespaces (e.g. dragging, etc)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5685]
No idea why.
Run the following and attempt to drag/pan the chart around, its very slow (unusable)..
```python
import numpy as np
import pandas as pd
%matplotlib widget
import matplotlib.pyplot as plt
p = np.linspace(0,20,100)
plt.plot(p,np.sin(15*p))
plt.show()
```

**Comment by DonJayamanne** [comment]
Should be fixed, but lets test again.

**Comment by BearBearCodes** [comment]
Any update on this? `%matplotlib widget` is unusably slow for me on my local VS Code installation.

I'm using the latest version of VS Code (version 1.64.2) with the latest pre-release version of the Jupyter extension (version v2022.2.1010501003). The slow widget behaviour has been occurring since late last year (~November?) and it happens even on the release versions of the Jupyter extension.

**Comment by DonJayamanne** [comment]
Please could you try this with the latest Insider version of VS Code.
It seems to work well for me, dragging is a little sluggish, however I can experience the exact same perf even in classic Jupyter Notebooks (i.e. outside VS Code)

**Comment by BearBearCodes** [comment]
Huh, you're correct. Dragging around and zooming in on a `%matplotlib widget` is sluggish but it seems like Jupyter Lab is equally as sluggish as well. This didn't happen a few months ago so I always thought it was on the VS Code end (I almost exclusively use VS Code to run Jupyter notebooks and never checked Jupyter itself). Another reason why I thought the problem was with VS Code rather than Jupyter is because I no longer see the bounding box made by the cursor when you zoom into a portion of a plot. I must've borked something on the Jupyter end because I don't see the box on Jupyter Lab either...

Apologies for the confusion. The `%matplotlib widget` performance difference between VS Code and regular Jupyter notebooks is negligible.
