### ISSUE TITLE
Jupyter not activating after reload

### ISSUE THREAD

**Issue by niccolomineo** [microsoft/vscode-jupyter#5835]
## Environment data

-   VS Code version: 1.56.1
-   Jupyter Extension version (available under the Extensions sidebar): 2021.6.811652604
-   Python Extension version (available under the Extensions sidebar): PyLance 2021.5.1
-   OS (Windows | Mac | Linux distro) and version: Mac Os Big Sur 11.3.1
-   Python and/or Anaconda version: Python 3.9.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Docker ("Remote - Containers" extension)
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

I should be able to activate Jupyter by reloading VSCode.

## Actual behaviour

Jupyter does not activate after reloading VSCode.

## Steps to reproduce:

1. Update to VSCode 1.56.1
2. You will see the following:

<img width="496" alt="jupyter" src="https://user-images.githubusercontent.com/5409469/117866608-a13f0600-b297-11eb-8ed9-aab5d88707df.png">

3. Reloading VSCode will not get Jupyter activated. You will be stuck in the situation above.

**Comment by joyceerhl** [comment]
We're working on publishing a fix (should be up within the next hour). Sorry for the trouble. Related: https://github.com/microsoft/vscode-python/issues/16209 

More details: this is due to the fact that the May release of the Jupyter extension pinned 1.56.0 for the VS Code engine version. If you upgrade to VS Code 1.56.1 there is currently no compatible Jupyter extension build on the marketplace. Again, we're working on publishing a compatible build ASAP.

**Comment by joyceerhl** [comment]
This should now be resolved with v2021.6.832593372. Please let us know if you continue to experience issues. Thanks for your patience everyone!
