### ISSUE TITLE
Ctrl+S saving is not the same as using the disk icon at the top

### ISSUE THREAD

**Issue by lxndio** [microsoft/vscode-jupyter#5907]
## Environment data

-   VS Code version: 1.56.2
-   Jupyter Extension version (available under the Extensions sidebar): 14.497.071 (2021.6.832593372)
-   Python Extension version (available under the Extensions sidebar): 35.831.718 (2021.5.842923320)
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04 LTS in WSL 2 on Windows 10
-   Python and/or Anaconda version: 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

When using Ctrl+S, a Jupyter notebook should be saved to disk.

## Actual behaviour

When using Ctrl+S to save a Juypter notebook, the asterisk behind the file name in the tab row goes away and it seems like the file has been saved. The notebook file does not change, however.
The changes are only written to disk when clicking on the disk icon in the toolbar at the top.

## Steps to reproduce:

Create a Jupyter notebook, put in some code and press Ctrl+S to save it. When opening the notebook file with another editor, you'll notice that the changes have not been saved.

**Comment by joyceerhl** [comment]
Unfortunately Ctrl+S saving works fine for me in WSL. Can you please share a screenshot of what the file looks like when unsaved?

You mentioned an asterisk, which sounds like you are still on our old webview implementation of notebooks rather than our custom editor implementation. Dirty files should look like this:

![image](https://user-images.githubusercontent.com/30305945/118567339-77b82b80-b72a-11eb-9f84-4382e7ade689.png)


Could you please share logs from the Jupyter output panel? Additionally, if you open your user settings.json, do you see the following? If not, what do you get when you add it?

```
  "workbench.editorAssociations": [
    {
      "viewType": "jupyter.notebook.ipynb",
      "filenamePattern": "*.ipynb"
    }
  ],
```

**Comment by rchiodo** [comment]
If the window has an asterisk instead of what Joyce is showing, that should mean your jupyter extension version is rather old. Please update your jupyter extension.
