### ISSUE TITLE
Better instruction or detection of missing `xelatex`

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#5912]
Issue Type: <b>Bug</b>

* Run "Export As", choose PDF

```
Error 2021-05-17 13:06:37: If you have not installed xelatex (TeX) you will need to do so before you can export to PDF, for further instructions go to https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex. 
To avoid installing xelatex (TeX) you might want to try exporting to HTML and using your browsers "Print to PDF" feature.
```

Extension version: 2021.6.834931520
VS Code version: Code - OSS Dev 1.57.0 (Commit unknown, Date unknown)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|32.00GB (0.26GB free)|
|Process Argv|. --enable-proposed-api ms-vsliveshare.vsliveshare --enable-proposed-api rebornix.better-jupyter-errors|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joyceerhl** [comment]
Some ideas here:
* Make the error message more specific instead of making the user check the error log:
![image](https://user-images.githubusercontent.com/30305945/118566380-a03f2600-b728-11eb-94cd-89c76a19db47.png)
* Check if xelatex / bibtex are installed upfront and route the user to the docs before attempting the installation if it's going to fail. The dependencies are https://github.com/jupyter/nbconvert/blob/88baf7a9ca724d74c9f890a60d5c3680e8959a14/nbconvert/exporters/pdf.py#L54-L60 We can check if they're on PATH (necessitates mirroring nbconvert's dependencies)
* Reimplement export to PDF using Chromium for the PDF export step, and install Chromium for the user. When this was originally implemented we decided to go with xelatex and to not try setting dependencies up for users. That being said, my assumption is that if the user has to install either Chromium or xelatex in order to do the export, Chromium is easier to install, and if they're going to have to set it up anyway we may as well do it for them the way we do for other dependencies. E.g. the `notebook-as-pdf` Python package uses Chromium via Pypetteer: https://pypi.org/project/notebook-as-pdf/

**Comment by DonJayamanne** [comment]
> using Chromium for the PDF export step, and install Chromium for the 

I prefer this option, to my knowledge this is the deafult (preferred) option used in Jupyter when exporting to PDF.

**Comment by joyceerhl** [comment]
Strange, I believe Tim found that JupyterLab goes the `nbconvert` + TeX route, and the HTML to PDF using Chromium route would generate a subpar PDF that's formatted differently.

Not sure how well these work: https://www.npmjs.com/package/html-pdf-node and we could do the HTML step with `nbconvert` or in JS https://github.com/jirutka/ipynb2html

**Comment by DonJayamanne** [comment]
Thank you for filing this issue, given the fact that we haven't had sufficient upvotes on this issue I'm closing this as not planned.
