### ISSUE TITLE
Opening & saving notebooks with format 4.5 will end up with the cell_id lost (hence invalid notebooks)

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#5933]
If a cell id exists, we should retain it.
Related to https://github.com/microsoft/vscode-jupyter/issues/4974

FYI - I'd count this as data loss & breaking notebooks (opening in VS Code breaks it as the notebook is no longer valid)

**Comment by joyceerhl** [comment]
4.5 is released now https://nbformat.readthedocs.io/en/latest/format_description.html#cell-ids

**Comment by greazer** [comment]
Thanks for your feedback. This issue is addressed with new native support for editing notebooks. To opt into that experience see: https://github.com/microsoft/vscode-jupyter/wiki/Introducing-Native-Notebooks.

**Comment by rchiodo** [comment]
/verified. It kinda works. We don't lose the cell ids, but for new cells we're technically incorrect. I'll enter a new bug for that.

Technically in order to support 4.4 and above the 'id' is required:

https://github.com/jupyter/enhancement-proposals/blob/master/62-cell-id/cell-id.md#required-field

**Comment by DonJayamanne** [comment]
> I'll enter a new bug for that.
> Technically in order to support 4.4 and above the 'id' is required:

I have already got a PR in the works for this.
