### ISSUE TITLE
Notebook trust prompt shown for files in trusted workspace

### ISSUE THREAD

**Issue by SiddhanthUnnithan** [microsoft/vscode-jupyter#5938]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.57.0-insiders
- OS Version: Win 10 

Steps to Reproduce:

1. Open a new workspace/folder in VS Code and classify as trusted workspace.
2. Open a Notebook within the workspace and check whether the "Notebook trust" toast notification is shown.

![image](https://user-images.githubusercontent.com/6413608/119011456-ee7f3f80-b949-11eb-87cb-fc178f0a30a2.png)

**Comment by rchiodo** [comment]
Do we think that trusting a workspace is clear enough to indicate code is going to run in notebooks or do we need a separate notification?

And if it is, how do we detect when in a trusted workspace? (We need to disable stuff in webview notebooks at least)

**Comment by SiddhanthUnnithan** [comment]
@rchiodo what do you mean by "indicate code is going to run in notebooks"? 

My impression of "trusted workspaces" was that if toggled, the user trusts the contents of the files in the folder for eventual execution (if they choose to). Isn't this the same intent behind Notebook trust, in that we disallow the user to run code in the Notebook?

If the user doesn't trust the workspace they should not be allowed to execute the code for any files in the workspace (by default). I don't have an opinion about displaying file content / Notebook output. I guess there is a model here (for extensions to work out with VS Code?) where I can trust the contents of specific files in an untrusted workspace? It'd be good to gather some customer feedback on what their expectations are with "trusting" generally in VS Code.

**Comment by rchiodo** [comment]
> It'd be good to gather some customer feedback on what their expectations are with "trusting" generally in VS Code.

I guess this is what I was alluding to. What does a customer think happens when they 'trust' a workspace? Do they even think about it?

Trust for eventual execution isn't the same as trust it to not run code in the background. Trusting a notebook can mean just that. I send you a notebook that modifies the DOM and executes code just by opening it.

And if I trust a workspace because hey I want this file A.py here, but I don't even look at the rest, do I expect the rest to run code? Would I even think about that?

I'm thinking the 'trust' workspace isn't enough IMO. That's why I'd want the secondary 'trust notebook' idea too.

**Comment by SiddhanthUnnithan** [comment]
Got it. I was unaware that I could create a Notebook which executes code when opened. How do we currently prevent against this with Notebook trust? As a user my impression is that the Notebook is opened before being prompted to trust.

The current wording for trusted workspaces is interesting - "You trust the **authors** of the files"...

![image](https://user-images.githubusercontent.com/6413608/119173582-4c7c5780-ba1c-11eb-90ce-66e94f4c9030.png)

I'm assuming that means it doesn't matter whether I look at the rest of the code, I trust who it's been written by.

**Comment by rchiodo** [comment]
> How do we currently prevent against this with Notebook trust?

If a notebook is untrusted we don't run any javascript in a notebook on opening. You have to trust it first. 

> I'm assuming that means it doesn't matter whether I look at the rest of the code, I trust who it's been written by.

This is what I want the customer development on. I'm hypothesizing that most people don't even think about it. Or if they do, they go, ah how bad could it be. What could a notebook do if I don't execute any cells? Because if you didn't realize a notebook could run code just by opening it, I'm guessing lots of people wouldn't think of that.

**Comment by DonJayamanne** [comment]
@rchiodo @SiddhanthUnnithan I'm working on the requirements with @rebornix 
I had a chat with him about notebook trust, workspaces (no workspaces, multi-workspaces), etc last week.
We'll need to wait for the API & workflow to be finalized in VS Code.
For now I have no idea what the final say is, I haven't provided any suggestions/requirements either, just highlighted some scenarios that could product weird user experience & information on how classic Jupyter handles the notion of trust.

**Comment by DonJayamanne** [comment]
I'm closing this issue in favor of https://github.com/microsoft/vscode-jupyter/issues/5745
