### ISSUE TITLE
Variable sort requires 3 clicks to sort

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6079]
Add some variables
Try sorting

It seems there are 3 states 
- Unsorted
- Sort by name ascending
- Sort by name descending

Seems like there should be a default sort?

**Comment by vandyliu** [comment]
Right now, the "unsorted" sort is Name, Asc because the way we retrieve variable names from ipython (it comes back sorted). Are you suggesting that we start out the variable explorer with Name and ASC sorted by default (with the arrow indicator there)? If so, would you expect there to always be the arrow: variable explorer is always sorted by something?

**Comment by rchiodo** [comment]
> Are you suggesting that we start out the variable explorer with Name and ASC sorted by default (with the arrow indicator there)?

Yes that would be the default. Otherwise to get back to descending I have to click 2 times instead of one.
