### ISSUE TITLE
We should allow starting local kernels in virtual workspaces

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6080]
Execution isn't possible, so running cells or using the interactive window should be restricted.

**Comment by DonJayamanne** [comment]
Questions/Suggestion:
* Should we allow users to run code against local Kernels?
	* I think yes, I.e. allow users to open a github repo and run against your local kernels.
	* I believe thats the benefit of virtual workspace, not having to clone everything locally to try something out.
* Similarly, we should allow users to run such notebooks against a local kernel.

**Comment by SiddhanthUnnithan** [comment]
The Python extension is deactivated in the remote repository setting because of the lack of Pylance support (as of now) and because the extension depends on tools (linters, formatters) that make use of the filesystem.

One thing to think about here is whether we should be consistent with the Python extension in terms of its support -- deactivated Python == no interpreter to run which, if we choose consistency, will mean that we do what this issue originally was proposing: restricting cell run and interactive window.
