### ISSUE TITLE
Install kernel/Change Kernel doesn't work in the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6082]
Create a venv with no ipykernel

Send code to interactive window
![image](https://user-images.githubusercontent.com/19672699/120552999-cf9e9580-c3ac-11eb-8d1d-4e3e1a0a13eb.png)

Click change kernel

Dialog pops up a second time and you're not allowed to change a kernel.

**Comment by DonJayamanne** [comment]
This is blocked by https://github.com/microsoft/vscode-jupyter/issues/6135
I've added a work around that will disable changing of kernels.
Also we get a horrible UX, we get the modal dialog twice for Interactive (just again part of the current code flow, we didn't notice this earlier because they weren't modal dialogs).

**Comment by DonJayamanne** [comment]
I'm going to change this from a modal to non-modal for Interactive, as its a very poor UX.

**Comment by DonJayamanne** [comment]
TODO: We seem to get two error messages when ipykernel is not installed. In stable we only get this once. Why? somethign has changed in insiders, we're checking ipykernel more than once.
