### ISSUE TITLE
.NET Interactive notebook custom metadata can be overwritten on open

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode-jupyter#6187]
## Environment data

-   VS Code version: 1.57.0-insider
-   Jupyter Extension version (available under the Extensions sidebar): latest
-   Python Extension version (available under the Extensions sidebar): N/A
-   OS (Windows | Mac | Linux distro) and version: Win 10 latest
-   Python and/or Anaconda version: N/A
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: N/A

## Steps to reproduce:

1. Install the [.NET Interactive extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.dotnet-interactive-vscode).
2. Launch VS Code Insiders.
3. Execute the command "Jupyter: Create New Blank Notebook".
4. Select ".NET Interactive (PowerShell)".
5. Save the notebook to disk.
6. Open the .ipynb in notepad.

Expected:
The notebook's kernelspec should look like this:

``` json
"metadata": {
  "kernelspec": {
   "display_name": ".NET (PowerShell)",
   "language": "PowerShell",
   "name": ".net-pwsh"
  },
  "language_info": {
   "name": "PowerShell"
  }
```

Actual:
The notebook's kernelspec defaults to C# values.  This happens because the custom metadata we're setting is getting destroyed so it enters our fallback path of assigning a C# kernelspec.

Note the two screenshots.  The first shows the custom kernelspec metadata is PowerShell as it's passed into the `openNotebookDocument()` function, but the value that comes back out the other end doesn't have this set; it instead sets just the `language_info`.  The custom metadata should have been preserved.

![image](https://user-images.githubusercontent.com/926281/121093513-5fc44c80-c7aa-11eb-9a41-4845c8870f84.png)

After

![image](https://user-images.githubusercontent.com/926281/121093579-779bd080-c7aa-11eb-8f79-3ca02bbb235a.png)

**Comment by DonJayamanne** [comment]
As per teams discussion, I'll look into this asap.

**Comment by DonJayamanne** [comment]
@brettfo We haven't updated our code to use the new Noteboook Serializer, hence this will happen.
How are you updating the metadata?

**Comment by DonJayamanne** [comment]
@brettfo looking at the code, I can confirm the .NET extension is changing the langauge to C# here
This is where .NET extension is updating it 
https://github.com/dotnet/interactive/blob/953cd94378a5e1d608e912fb2296f1bca2ae2883/src/dotnet-interactive-vscode/stable/src/notebookControllers.ts#L147

FYI - I've added some logging into the .NET extension after isntalling it & I can confirm this beug is caused by .NET extension.

As for `openNotebookDocument`, please note, we don't yet support the new serializer API (hence if you want to open an untitled notebook with default content, we don't yet support that)
That work is being tracked here https://github.com/microsoft/vscode-jupyter/issues/5622
