### ISSUE TITLE
vscode - jupyter notebook main kernel module not found error

### ISSUE THREAD

**Issue by ksg5302** [microsoft/vscode-jupyter#6259]
## Environment data

-   VS Code version: 1.57.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.6.999230701
-   Python Extension version (available under the Extensions sidebar): v2021.5.926500501
-   OS (Windows | Mac | Linux distro) and version: win10 21H1
-   Python and/or Anaconda version: 4.10.1
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local

## Expected behaviour

I want use main kernel

## Actual behaviour

ImportError

## Steps to reproduce:
I did it like this
1. conda create -n tens python=3.7
2. pip install tensorflow
3. pip install keras
4. pip install matpotlib
5. pip install pandas 
6. pip install seaborn 
7. conda install -c conda-forge fbprophet

Before no.7 it works but after no.7 it does'n and make it error like screenshot.

(python -m ipykernel install --user --name tensor --display-name "tens" <-after this and good works change kernel "tens". I don't know why it works!!!!! )

![NiceMS](https://user-images.githubusercontent.com/39893660/121680595-b1dfd780-caf4-11eb-817c-e772f333b740.png)

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by claudiaregio** [comment]
Hi @ksg5302, have you tried following the troubleshooting link with instructions that is provided by the error?

**Comment by DonJayamanne** [comment]
Thanks for filling this issue. 
Unfortunately this is not caused by vscode. It's caused by the packages installed and probably the manner in which they are installed, confirmed by you in step 7.
Please could you check this issue on stack overflow or the corresponding GitHub repos for the packages.
Also, I'm certain the issues is caused by the fact that you are using pip install instead of conda install when using a conda environment, that's generally discouraged.
