### ISSUE TITLE
Remove isTrusted from INotebookModel

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6281]
Not needed with workspace trust, and has caused an issue already.

**Comment by DonJayamanne** [comment]
I don't think we should, the current way it works is isTrusted will use the workspace trusted value.
Hence it will work as expected.
The only benefit is code health, we might as well just want to remove webview completely instead of spending time on remove a small feature like trusted.

FYI - webview needs to load notebook and disable execution, etc i.e. it still needs to support a notion of trust (this was done by keeping `isTrusted`).
