### ISSUE TITLE
Jupyter Notebook Cell in Dark Theme in WSL not colored

### ISSUE THREAD

**Issue by lk-hang** [microsoft/vscode-jupyter#646]
# Bug: Notebook Editor, Interactive Window, Editor cells

## Steps to cause the bug to occur

1. Open VS code regularly (i.e., through the start menu).
2. Create test.ipynb (LEFT in the figure)
3. Launch Ubuntu/WSL. Type `code .`
4. Create test_wsl.ipynb (RIGHT in the figure)
5. Change theme color: Light+ (Default) to produce the following figure (expected):
![image](https://user-images.githubusercontent.com/31430706/90451618-11ba4d00-e0a1-11ea-8afb-80f8bc1e634b.png)
Change theme color: Dark+ (Default) to produce the following figure (unexpected):
![image](https://user-images.githubusercontent.com/31430706/90451631-18e15b00-e0a1-11ea-9002-616df4e2fd47.png)

## Actual behavior

The cell in the dark theme does not have a color that is distinct from the background color in dark theme when connected to WSL (right panel)

## Expected behavior

The cell in the dark theme should have a color that is distinct from the background color in dark theme, similar to the left panel.

### Your Jupyter and/or Python environment

_Please provide as much info as you readily know_

-   **Jupyter server running:** Local 
-   **Extension version:** 2020.08.101144
-   **VS Code version:** 1.48
-   **Setting python.jediEnabled:** true 
-   **Setting python.languageServer:** Jedi 
-   **Python and/or Anaconda version:** 3.8.3
-   **OS:** Windows | Mac | Linux (distro): Windows & WSL Ubuntu 20.04
-   **Virtual environment:** conda

## Python Output

Microsoft Data Science for VS Code Engineering Team: @rchiodo, @IanMatthewHuff, @DavidKutu, @DonJayamanne, @greazer, @joyceerhl

**Comment by rafalpotempa** [comment]
Hello everyone!

The bug persists and since https://github.com/microsoft/vscode/issues/91987 has the `Notebook theme support` marked as `done` I think the issue would require reopening.

I was trying to play around with `jupyter.colorizeInputBox` but this doesn't seem to work. Up to my understanding of 'peek color' it is just the darkest color of the theme. I would expect setting the darker background would force the cells to have distinct background color, but it does not.

What I have in settings + `jupyter.colorizeInputBox: true`
![image](https://user-images.githubusercontent.com/33723064/102716996-c8dd0400-42df-11eb-834e-ae564785cdd1.png)

How I want it to look like vs what I get in WSL:

![wsl](https://user-images.githubusercontent.com/33723064/102717191-08f0b680-42e1-11eb-8c0e-8eb0e56f2201.png)

---

The font coloring seems to be broken too:
Normal:
![image](https://user-images.githubusercontent.com/33723064/102717115-7fd97f80-42e0-11eb-89cc-9c194b3a2e77.png)

WSL:
![image](https://user-images.githubusercontent.com/33723064/102717129-9253b900-42e0-11eb-9b0b-be2538067bb1.png)

**Comment by IanMatthewHuff** [comment]
@rafalpotempa The new notebook support is only supported by the Jupyter extension with VS Code - Insiders not in stable VS Code as it's still in preview. What you have pictured above is still our old webview implementation. That implementation is going away and will not be updated. If you try out Insiders you can see the new UI.
