### ISSUE TITLE
Native Interactive - After executing cell script, it's missing the Goto [#] codelens

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6496]
- Execute any cell in a python script
- After it runs, you should see a new "Goto [#]" that when clicked will scroll the interactive window to that cell.

**Comment by joyceerhl** [comment]
This is happening because for native interactive we aren't updating the `cellExecutionCounts` in the `this.notebookData` map here:

https://github.com/microsoft/vscode-jupyter/blob/2253b23239520a89310ec944f51f54db9d783b14/src/client/datascience/editor-integration/codeLensFactory.ts#L481-L485

So this check always fails:

https://github.com/microsoft/vscode-jupyter/blob/2253b23239520a89310ec944f51f54db9d783b14/src/client/datascience/editor-integration/codeLensFactory.ts#L500-L507

Also we haven't implemented the ScrollToCell handler for native interactive: 

https://github.com/microsoft/vscode-jupyter/blob/d06d8d8b0c2e8d7db45fcb6dc4434cdb313e6271/src/client/datascience/interactive-window/nativeInteractiveWindow.ts#L504-L506
