### ISSUE TITLE
Catboost Error

### ISSUE THREAD

**Issue by MisterKaynan** [microsoft/vscode-jupyter#6538]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by IanMatthewHuff** [comment]
@MisterKaynan I'm sorry, but this issue doesn't have enough info about your scenario to be sure about how to help best. We'd need info on what you are trying to do as well as the versions of VS Code and Jupyter extension involved here.

I do know that at one point catboost publish their widget files on a CDN, which prevented our stuff from working on them. They have since fixed this: https://github.com/catboost/catboost/issues/1673
So making sure that you are updated to the newest version of catboost might be a good first step.
