### ISSUE TITLE
Native interactive has current working directory at root, not file relative.

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-jupyter#6549]
This used to be relative to the working file. Makes loading files different from notebooks and from the old interactive window.

Old Interactive:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/06ec036c-cdd7-48da-8ab1-6d05fb4e467c)

New Interactive:
![image.png](https://images.zenhubusercontent.com/5bdcd40a0faa800c749bac98/1df366e9-15f3-478a-abff-28a78fa6d911)

Both examples starting from a code block in DebuggingDemo folder.

**Comment by joyceerhl** [comment]
Probably lost some code in the transition from interactiveBase.ts which was setting this up properly.

**Comment by jaymegordo** [comment]
FWIW my interactive root is still set correctly.

I have `"jupyter.notebookFileRoot": "${workspaceFolder}",` in settings.json.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/29611875/124814168-88ab3f00-df1a-11eb-977d-e51186287190.png">

**Comment by joyceerhl** [comment]
This is happening because now kernels for the interactive window get started via the native notebooks codepath, where the NotebookDocument URI is used to set the CWD. The interactive window is implemented using an embedded NotebookDocument with a dummy URI that doesn't exist on disk. The dummy `uri.fsPath` which doesn't exist on disk gets passed as the launchingFile, which `path.dirname` resolves to '.':

![image](https://user-images.githubusercontent.com/30305945/124839468-b655af80-df3d-11eb-87ab-d83f999883dc.png)

'.' then gets resolved to '//' by `expandWorkingDir` so this branch gets taken when it really should not be:

![image](https://user-images.githubusercontent.com/30305945/124839606-f026b600-df3d-11eb-989e-3bb1e42733f9.png)


This value for `workingDir` then gets cached so when we subsequently invoke `updateWorkingDirectoryAndPath` with the right launching file URI fsPath, `workingDir` doesn't get updated. I think the right fix here is to tighten the check for launchingFile fsPath validity. We should only attempt to use the `launchingFile` in `expandWorkingDir` if the `launchingFile` actually exists on disk.

**Comment by janosh** [comment]
Thanks for the quick fix!

**Comment by jonvlcs07** [comment]
I'm having the same issue, how do i fix it?

![image](https://user-images.githubusercontent.com/52894575/125106375-f2138500-e0b5-11eb-84a3-8ea250752804.png)

**Comment by janosh** [comment]
@jonvlcs07 Needs a [new release of the Jupyter extension](https://github.com/microsoft/vscode-jupyter/releases).

**Comment by joyceerhl** [comment]
The pwd problem for the preview interactive window is fixed in the Jupyter extension's Insiders builds (we will be publishing a new one later today). Alternatively you can try this workaround: https://github.com/microsoft/vscode-jupyter/issues/6549#issuecomment-875852103 Sorry for the trouble!

**Comment by jonvlcs07** [comment]
Nice, I did the workaround and now it's fixed thanks!

Btw, good job with the new release, I will definitely be switching from jupyterlab to vscode now.
