### ISSUE TITLE
Remove the words `Save` from save icon in interactive window

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#6630]
Save icon is universal, not sure it needs a lable `save`.
We don't have the label for the export icon,
<img width="712" alt="Screen Shot 2021-07-11 at 16 53 17" src="https://user-images.githubusercontent.com/1948812/125213789-af45de80-e268-11eb-885d-a52e0b4b7e6c.png">

**Comment by claudiaregio** [comment]
The plan is to move the export functionality into the file menu. While save is universal, I believe this would be resolved when the toolbar supports just icons? 
https://github.com/microsoft/vscode/issues/125551

**Comment by joyceerhl** [comment]
@DonJayamanne We do have the label for the export icon :) it's truncated in your screenshot but if you scroll horizontally you should see it. There's no way not to have text next to the icons at the moment, if we don't specify a short title VS Code will use the title instead, and I don't believe there's a way to omit the title.

**Comment by DonJayamanne** [comment]
@rebornix Hmm, is it possible to have both.
I think the whole purpose of having `title` was for discoverability. But some icons don't need labels, like save.

Please feel free to close this issue or transfer to VS Code.
I'm not sure whether this should be close or not, either way, I don't think we should have labels for save, but possible we might need them for other icons (based on assumption this was the original requirement)

**Comment by joyceerhl** [comment]
I believe the title is to align with Office because it's considered good UX to have the icons as well as text. IMO 1. it would be weird to have some icons accompanied by text but not others, 2. this issue will be resolved by https://github.com/microsoft/vscode-jupyter/issues/6478 anyway (i.e. we are moving the save option to under the export button) 3. we should allow users to hide the text on all icons https://github.com/microsoft/vscode/issues/125551

**Comment by DonJayamanne** [comment]
> le is to align with Office because it's considered good UX to have 

Seems weird, as none of the icons in standard editor toolbar (today in VSCode) display text when we have icons.

**Comment by DonJayamanne** [comment]
Lets close this, as its been discussed elswhere (i.e. nothing new in this issue)

**Comment by rebornix** [comment]
My 2 cents:

* It makes sense to have Export action on the toolbar, but not Save. The Interactive is not file based so there is no "save" (just like no dirty indicator)
* Whether the label for the actions should be visible to users is going to be controlled by the core based on conditions (e.g. width, settings), other than controlled by each command.

**Comment by joyceerhl** [comment]
100% agreed with @rebornix

**Comment by rebornix** [comment]
> Seems weird, as none of the icons in standard editor toolbar (today in VSCode) display text when we have icons.

@DonJayamanne actions on editor toolbar are meant to be secondary since the primary actions for the text editor are typing, auto-complete, code navigation, etc, which are all accessible through keyboard and even keyboard centric. However notebook is relatively new and users are not necessarily familiar with the shortcuts or icons of the primary actions, so the labels are majorly for educating users. We don't have such ux before (an in-editor toolbar) so we are still exploring and I'm not sure I'll be 100% satisfied with icons only.
