### ISSUE TITLE
cant find python kernels or connect to remote jupyter serevr after last update

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode-jupyter#6653]
Issue Type: <b>Bug</b>

I have been working with notebooks for quite long. For the last couple of weeks, in specific, i have been running jupyter servers in a WSL ubuntu machine, connecting to to server by specifying the url+token. After applying an update today, not only can i no longer conenct to remote or local jupyter server urls, but when i attempt to run a file the "choose kernel" list is empty, not even the native windows python kernels i have installed are shown. I tried restarting both VS and the pc

VS Code version: Code - Insiders 1.59.0-insider (f6df685c62da50886f7540cbf768ed4333d58bea, 2021-07-13T05:12:59.073Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (5.65GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|8.0.1
kite|kit|0.147.0
python|ms-|2021.7.1009617374-dev
vscode-pylance|ms-|2021.7.3-pre.1
jupyter|ms-|2021.8.1025925145
remote-containers|ms-|0.187.0
remote-ssh|ms-|0.65.7
remote-ssh-edit|ms-|0.65.7
remote-wsl|ms-|0.58.2
vscode-remote-extensionpack|ms-|0.21.0
powershell-preview|ms-|2021.6.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
pythonvspyt602:30291494
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyt639:30291487
pythontb:30258533
vspre833:30321513
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscus158:30321503
pythonvsuse255:30319630
vscod805cf:30301675
pythonvspyt200:30323110
vscextlangct:30310089
vsccppwt:30312692
bridge0708:30335490

```

</details>

**Comment by ghylander** [comment]
I don't know if the issue is related, but i cannot run .py files in interactive windows, the message "starting jupyter server" shows up for a split second, disappears, and the cell(s) are not executed

**Comment by joyceerhl** [comment]
@ghylander Sorry for the trouble. Could you please provide the Jupyter output panel logs?

**Comment by ghylander** [comment]
in the case of interactive window this is the output: https://pastebin.com/Fab5B9aV
as i was posting this, a new update to VS had been pushed that seems to have restored some functionality to the "choose kernel" dialogue, but the interactive window issue is still present

**Comment by joyceerhl** [comment]
@ghylander Sorry for the bother--could you please share a screenshot of the interactive window? We're porting the old webview interactive window over to use VS Code built-in UI and I'm trying to determine if we broke the ability to connect to remote Jupyter servers as a result of this update.

**Comment by excelsior091224** [comment]
I have same problem.

## Environment data

-   VS Code version: 1.58.2
-   Jupyter Extension version (available under the Extensions sidebar): 2021.8.1013163132
-   Python Extension version (available under the Extensions sidebar): 2021.6.944021595
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 20.04.2 LTS
-   Python and/or Anaconda version: Python 3.8.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Remote

## Expected behaviour

Python 3.8.10 (/usr/bin/python3) is found in list of kernels.

## Actual behaviour

Python 3.8.10 (/usr/bin/python3) is not found in list of kernels.
From remote, python3 of virtualenvs and python2 is found in list of kernels, but default python3 (/usr/bin/python3) is not found.
![vscode_jupyter](https://user-images.githubusercontent.com/44745901/126100349-a02c2a96-1748-4a49-a756-1998a5f6b6ba.png)
I tried to install VSCode to Ubuntu and launched local, but python3 is not found, only python2 is found.
![スクリーンショット 2021-07-19 114006](https://user-images.githubusercontent.com/44745901/126100354-5f63a218-e12f-4201-86b8-e6e6804358f8.png)

## Steps to reproduce:
I don't know.

## Logs
[9-Jupyter.log](https://github.com/microsoft/vscode-jupyter/files/6837774/9-Jupyter.log)

**Comment by ghylander** [comment]
Hi,
i was close to say that it had been fixed, but i keep getting problems with listing python kernels
i (right now) don't have trouble running interactive python windows
however, i began having issues with selecting python interpreter/kernels

in the following screenshot, thereshould be at least 3 kernels listed, 1 in each venv:
![image](https://user-images.githubusercontent.com/74593034/126979915-30c6b9ed-b267-484e-bb5e-00102b48a08f.png)

only the last selected kernel  (which is atuomatically selected by default when conencting to host) is visible

**Comment by DonJayamanne** [comment]
@ghylander
Please could you test this in the latest VS Code release. I believe this should be fixed now.

**Comment by ghylander** [comment]
> @ghylander
> Please could you test this in the latest VS Code release. I believe this should be fixed now.

I'll keep an eye on it
i can't say i can make it happen becasue it was seemingly at random, but if i don't note any incidences in a week or so i will close the issue

**Comment by ghylander** [comment]
all my test were succesful, both listing loal and wsl kernels. The latter required me to specifically open a WSL exclusive VS window, something i did not need to de before which must be a new change

**Comment by DonJayamanne** [comment]
@ghylander  thanks for getting back to us, really do appreciate it.
