### ISSUE TITLE
Interactive window can take seconds to show any status

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#6847]
Open a folder
Open a  python file with cells
Click run cell

For 5 seconds or so there's no response and then I get the Kernel connection message and the IW comes up.

**Comment by rchiodo** [comment]
I believe the lack of status is the python extension loading.

**Comment by sigxcpu76** [comment]
I get this behavior a lot of time.
- Pandas operations that take less than a second, sometimes take 2+ minutes (until I hit "stop" and it shows the result). Run again and you may get <1 second
- Syntax errors that should've been displayed immediately take 2+ minutes (until I hit "stop" and get the error instantly)

_something_ is waiting on _something else_ for no reason because that _something else_ never comes.
The interesting fact is that during these long waits the CPU is using one core fully, which looks like a busy loop?

**Comment by rchiodo** [comment]
@sigxcpu76 your bug is likely this one:
https://github.com/microsoft/vscode-jupyter/issues/1641

If you disable jedi support in ipython, your problem should go away.

The issue I'm describing in #6847 is only for startup.

**Comment by sigxcpu76** [comment]
Thank you! I searched the issues list like crazy and the closest thing I could find was this issue.

**Comment by amunger** [comment]
feels pretty responsive at this point, closing as stale
