### ISSUE TITLE
Kernel Interrupt not working in interactive window for cells submitted from a #%% file

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#6983]
Version: 1.59.0 (system setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.22000

1. Run a long running notebook using a python script with #%% cells, run it via a codelens then try to stop it with Interrupt Kernel. 

It doesn't stop. No notification that it's even trying to stop it as is expected.

**Comment by robclouth** [comment]
Same issue. After closing, the window opens again automatically because it's still running, then the Interrupt button works correctly.

**Comment by joyceerhl** [comment]
This is happening because cell execution for the interactive window is not managed through the KernelExecution codepath, so when we call interrupt here: https://github.com/microsoft/vscode-jupyter/blob/27a2bf48844416329f24ff89e3f3c8acd326f92c/src/client/datascience/interactive-window/nativeInteractiveWindow.ts#L505

There's no executionQueue, so we report success and never attempt the interrupt: https://github.com/microsoft/vscode-jupyter/blob/f5c89293163be4c90341104ae4aa151610027d98/src/client/datascience/jupyter/kernels/kernelExecution.ts#L96-L99

**Comment by joyceerhl** [comment]
Hotfixed in release branch for upcoming recovery build via https://github.com/microsoft/vscode-jupyter/pull/7070
