### ISSUE TITLE
Unable to copy output of dataframe.columns from interactive window

### ISSUE THREAD

**Issue by janosh** [microsoft/vscode-jupyter#6998]
Running the native interactive window using the latest Python and Jupyter extensions, I'm unable to copy text from the output of `df.columns`.

Minimal example:

1. Open command palette and run "Jupyte Create Interactive Window".
2. Enter
   ```py
   import pandas as pd

   df = pd.DataFrame(range(2), columns=['foobar'])
   df.columns
   ```
3. Try to copy-paste the column name `'foobar'` into the input field at the bottom of the window. Doesn't work (for me).

**Comment by greazer** [comment]
Strange, this is working for me. What platform are you on? Note that if this is blocking you you can temporarily revert to the old interface with the setting:
```   "jupyter.enableNativeInteractiveWindow": false ```

**Comment by janosh** [comment]
Hmmm... working for me as well now. I closed VS Code in the meantime so maybe the restart helped. Will reopen issue if it reoccurs and I can offer more details. Happened on macOS 11.5.

**Comment by janosh** [comment]
Definitely reoccured just now. Couldn't figure out what exactly triggers the problem. Seems to require longer use of the interactive window before it appears.

**Comment by janosh** [comment]
Here's a short screen recording showing the problem. It's possible to copy the cell input and I just noticed it does copy some text from the cell's output, just not the part that was selected.

https://user-images.githubusercontent.com/30958850/129013862-a9b98a44-f32c-41ed-bb3d-6dbffd4a5a3f.mp4

**Comment by greazer** [comment]
Hey @janosh, are you running insiders? Personally, I ran into an issue where random things stopped working, perhaps like you're running into. Turned out that a memory leak exists that may account for odd behavior occurring once memory is exhausted. 
https://github.com/microsoft/vscode/issues/130637. We're hoping to get that fixed in insiders asap. 

It may not resolve the problem you're seeing, but it certainly was something that could cause all sorts of problems.
