### ISSUE TITLE
ESC no Longer Clears Interactive Window Command Entry

### ISSUE THREAD

**Issue by mitchcbr** [microsoft/vscode-jupyter#7113]
ESC and Ctrl-U both clear it. Validated.

_Originally posted by @IanMatthewHuff in https://github.com/microsoft/vscode-jupyter/issues/2275#issuecomment-612239265_

Not anymore, sadly :( 
v2021.8.1195043623

**Comment by joyceerhl** [comment]
@rebornix and I discussed this when we were implementing the native interactive window. Since the native interactive window has workbench integration, it supports VS Code builtin, extension-contributed and user-customized keybindings. We were concerned that this would introduce conflicting keybindings, since Ctrl+U means 'Cursor Undo' in a VS Code text editor, and Esc already has meaning for Vim users. 

I believe we discussed implementing a command to clear the interactive window command entry _without_ a default keybinding associated, and allowing users to add a keymap for that command, bound to Ctrl+U or Esc. @mitchcbr, what are your thoughts on that solution?

**Comment by mitchcbr** [comment]
@joyceerhl I think that'd work. As long as there's a way to bind a single keystroke to clearing the box. When a person is testing or debugging something, clearing the command prompt is a frequent occurrence as mistakes are made. As I see it, there are three ways to clear that box, from best to worst:

1) Single keystroke, e.g. Esc
2) Multi keystroke, e.g. ctrl-A_delete (most recent update)
3) Hand to mouse

**Comment by mitchcbr** [comment]
@joyceerhl I don't know if this would be an alternative option, but ctrl+c is often used for cancelling commands on the terminal. Might be good alternative to esc.

**Comment by joyceerhl** [comment]
@mitchcbr We are still discussing whether the Jupyter extension should contribute a keybinding by default for this command, and we've implemented an `interactive.input.clear` command in VS Code Insiders for the native interactive window, should be available in tomorrow's Insiders and the upcoming August Stable release. You can then add a keybinding like so:

```
{
  "key": "esc",
  "command": "interactive.input.clear",
  "when": "resourceScheme == 'vscode-interactive'"
}
```

**Comment by joyceerhl** [comment]
We have implemented this in Insiders https://github.com/microsoft/vscode-jupyter/commit/bfa29be69d72bd1a83954abbca5b83a19fb42767 Should become available in the next stable release of VS Code
