### ISSUE TITLE
Rework command listener for interactive window

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-jupyter#7164]
We introduced promise chaining in the interactive window to fix a problem in the interactive window where cells executed in rapid succession would get executed out of order: https://github.com/microsoft/vscode-jupyter/blob/2b3fdb7ef5eae0bae50adf1b126060b09b857278/src/client/datascience/interactive-window/nativeInteractiveWindow.ts#L385-L393

This doesn't work very well, because the chained promises do not get correctly cancelled on an interrupt or restart. It also doesn't address problems like https://github.com/microsoft/vscode-jupyter/issues/6982. Instead we should use the CellExecutionQueue to queue cells for execution

**Comment by amunger** [comment]
This is already complete for cells added from a python file, `kernelExecution` holds a map of `ExecutionQueue`s per `document`. Code executed from the input box does not go through the same queue since vscode core calls the execution, but that is accounted for in https://github.com/microsoft/vscode-jupyter/issues/10671
