### ISSUE TITLE
Include #%% in executed code within Interactive window. (was: New notebook-style usability issues)

### ISSUE THREAD

**Issue by svintuss** [microsoft/vscode-jupyter#7240]
Issue Type: <b>Feature Request</b>

Hello. 

After upgrading to VSCode 1.59.1 I have issues with the new notebook format. 
I mostly use .py files and interactive iPython panel. Latest update broke my workflow.

1. There is no indication on the collapsed cell whether it's executing or not. I have to unwrap it just to see it's running. 
2. It's impossible to delete a cell with one click. I have to select it or expand it first. There is no 'X' to get rid of an erroneus code instantly. 
3. Collapsing the cell is not trivial too. If it's a long one I have to scroll all the way down to double-click it's number. Which itself (double-clicking the number) was not an easy thing to figure out.
4. Cell header is not propagating from '#%%' comment. I now have to modify all my files to have a comment right below "#%%' line so that I know what cell is running.

Is there any chance this will be fixed in future releases?

Extension version: 2021.8.1147840270
VS Code version: Code 1.59.1 (3866c3553be8b268c8a7f8c0482c0c0177aa8bfa, 2021-08-19T11:53:52.479Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

**Comment by joyceerhl** [comment]
1. and 2. are both fixed in Insiders and the upcoming Stable release. For 1., a blue progress bar will display on top of the executing cell even when it's collapsed. For 2., the cell toolbar will be rendered when the cell is collapsed. You can configure `"notebook.cellToolbarVisibility": "hover"` so that you don't need to click on a cell for the toolbar to appear. Here's what that looks like together: 
![image](https://user-images.githubusercontent.com/30305945/130537927-5e031f73-7ffd-4c52-b145-d551ef038d60.png)

Re: 3., you can double click anywhere on the cell container to collapse it; doesn't have to be on the execution count. You can also use Ctrl+K Ctrl+C, or right click on the cell and select Collapse Cell Input: 
![image](https://user-images.githubusercontent.com/30305945/130538249-8ba86473-9407-49bb-8375-03a1fcea49d0.png)

> Cell header is not propagating from '#%%' comment. I now have to modify all my files to have a comment right below "#%%' line so that I know what cell is running.

We removed propagating the cell header in response to user feedback https://github.com/microsoft/vscode-jupyter/issues/6623 A setting might make sense here though.

**Comment by amunger** [comment]
closing as most of this looks completed, please open a new issue for any remaining concerns
