### ISSUE TITLE
run code on specify interactive window

### ISSUE THREAD

**Issue by FisherBao** [microsoft/vscode-jupyter#7249]
On the old version, I can select the interactive window to run the python code, interactive  1 or interactive  2 or 3 etc. But it  looks don't  support this on newest version. I update the juypter extention to newest version today. The code only can run on the lastest create interactive window.

I don't know how to set this like the old version.

**Comment by IanMatthewHuff** [comment]
@FisherBao does changing the "Jupyter: Interactive Window Mode" setting get you the result that you are looking for here?

**Comment by FisherBao** [comment]
@IanMatthewHuff 
I select the mode - multiple, it doesn't work. 
But it is ok in the version before v2021.8.1054968649(include this version), and from version v2021.8.1195043623, this don't work.
It always jump to the lastest create  interactive window.
![image](https://user-images.githubusercontent.com/45677283/130707976-cde2511d-b995-4162-b1a2-7a6b8ca32b13.png)

**Comment by joyceerhl** [comment]
Sorry about the inconvenience. Would you mind providing the specific steps that you are taking to create multiple interactive windows and then submit code? e.g. do you have multiple script files, are you creating interactive windows from the command palette as well as a script file?

**Comment by elazarcoh** [comment]
Hi,
I'm having the same issue. I see you already added it to September milestone.
Just to make sure it capture my usage as well:

Steps to reproduce:
1. create python file with cells 
   ```python
   # %%
   x = 1
   # %%
   print(x)
   ```
2. run the first cell with `shift+enter`
3. open command palette with `F1` and execute `Jupyter: Create Interactive Window`
    - it opens a new inteactive window: `Interactive-2`
4. manually select `Interactive-1` tab
5. run the second cell

it runs the cell in `Interactive-2` instead of `Interactive-1`
