### ISSUE TITLE
Variable Explorer should be included within the Interactive Window not as a separate panel

### ISSUE THREAD

**Issue by salmanea** [microsoft/vscode-jupyter#7287]
Hi,

I noticed that in the newer versions, the Variable Explorer is placed down near Terminal and other stuff.
I think that it was much better when it was on the top of the Interactive Window.

It gives a very Spyder-like look for those of us who have just started using VSCode.

If it is not possible to undo this, then please add an option so that we can choose where to see the variables.

Thanks!

**Comment by nicklisterman** [comment]
Agreed. Not sure where we give thoughts but love the new appearance of the interactive window, struggling with variables being part of the panel and forcing a third column or horizontal full width.

**Comment by joyceerhl** [comment]
Rollup of other user complaints on this subject: 

https://github.com/microsoft/vscode-jupyter/issues/7432#issuecomment-914475127
#7153
https://github.com/microsoft/vscode-jupyter/issues/6993#issuecomment-896339377
https://github.com/microsoft/vscode-jupyter/issues/6993#issuecomment-896470591
https://github.com/microsoft/vscode-jupyter/issues/7188#issuecomment-901711018

**Comment by abd-shouman** [comment]
Glad to see all comments about Jupyter Variables grouped in one place. For me, the variable explorer (currently Jupyter Variables) is a key item that I interact with daily. The fact that Jupyter Variables makes it difficuly for me to update to any version that has Jupyter Variables (I have not installed the latest 2 updates on my main machine).

Hope to see some imporvment soon

**Comment by DonJayamanne** [comment]
Moving to triage to discuss

**Comment by jtskowronek** [comment]
It's not obvious where to vote for this feature request so that the votes are actually counted and acted on. 

I would bet the President's life there are plenty of users of vscode who are frustrated by the interactive window and variable explorer being so incompatible, but it seems the devs of this feature might be oblivious to this common use case when both windows are central to one's workflow. 

The best workaround I've found as of yet is to separate the variable explorer from the super annoying sliding side panel. But now I'm taking up space in all columns for just the variable explorer!

![image](https://user-images.githubusercontent.com/56658277/191597077-bd896e51-0b3f-4b36-9cdc-4927267e334a.png)

**Comment by roblourens** [comment]
We are working on turning this table into built-in UI, instead of an extension contribution. We are considering some different UI options. Follow https://github.com/microsoft/vscode/issues/165445 for updates
