### ISSUE TITLE
Support creating an ipynb notebook file via VSCode -> New File...

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#7363]

**Comment by SiddhanthUnnithan** [comment]
(IMO) Relevant: https://github.com/microsoft/vscode-jupyter/issues/7491

**Comment by IanMatthewHuff** [comment]
I spent some time digging around the ChangeModeAction to get familiar with the code on the vscode side, and from what I see the issue here is a bit more interesting for notebooks than I first thought. Seemed worth discussing as a general notebook / UX issue. 

Per the issue it seems reasonable that a customer would take this path here:
![image](https://user-images.githubusercontent.com/812783/134074622-01736b61-dded-4bce-8727-2f1fa20d3a13.png)

And then expect to get an empty notebook cell. As opposed to what they get right now where they get text editor instance set to "Jupyter" language mode, not very useful.

However supporting this might be a bit more of a change than expected, and I'm interested in if what we are proposing is even what the customers will expect to have happen. Right now the code is based around changing the language mode of the active text editor. It shows up in the New File link, but is also available via the language picker and the "Change Language Mode" command. Using this command you can swap between C#->JavaScript->Go and the whole time you have the same fundamental text editor, you just change the language mode. I think that we certainly have the capability to close the active text editor and bring up the notebook editor, but it does raise some of the following issues in my mind.

1. This is a bit of a destructive command, you can change a file from language to language, but changing from the text editor to a notebook editor you can't just change back.
2. What would you do with the content in the file changing from a non-notebook file to a notebook file? These commands don't just work with an empty new file. Would the content go away? Push all the text into the first cell?
3. Is a notebook type actually a language mode and appropriate to be in this list? To me it feels pretty fundamentally different from picking F#, or Java. Something like Jupyter supports different language modes inside of it, it's not a language mode in and of itself. Also what does this mean for something like github-issues?

Coming in newer to the core codebase here it actually feels to me like the notebook types are not actually appropriate language selections here. Just consider per #3 above what exactly does this situation that I set up here mean?
![image](https://user-images.githubusercontent.com/812783/134077108-3124f7b1-1ac7-4ab9-aac3-eb695b60ce1c.png)
If I change the editor language of a Jupyter notebook cell to github-issues I certainly don't expect that cell to turn into a notebook editor instance. Allowing notebook types as language selections in some cases, but not in others is starting to feel pretty special casey. But then the follow up question there is do we have adequate entry points to create a new notebook file if they are not allowed in the language mode change?

**Comment by rchiodo** [comment]
I agree, language picker shouldn't let you pick 'jupyter'. It's weird and destructive. I think that's one of the reasons for this issue actually. We remove the 'jupyter' language, so then how does a user make a new notebook? Well they use the ```New File ...``` which lets them do more than just create text files.

**Comment by IanMatthewHuff** [comment]
Yeah, the comment on the initial issue from Sid sounded like "pick 'Jupyter' and get a notebook" via the language picker but that doesn't seem right to me. I agree on adding it to New File... just wanted to check my understanding on removing it from the language picker.

**Comment by IanMatthewHuff** [comment]
Closing as it's added to New File... opened the issue 133486 on the vscode side for hiding notebook types in language picker.
