### ISSUE TITLE
Cannot open the larger dataset in the data viewer of native interactive window

### ISSUE THREAD

**Issue by fang6100146** [microsoft/vscode-jupyter#7420]
## Environment data

-   VS Code version:1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: win 10 pro 21H1
-   Python and/or Anaconda version: 3.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Local | Remote | Local

## Expected behaviour

I used to open larger dataset with data viewer of webview interactive window, it worked well. However, when I updated my 
jupyter version, it cannot open data and no response in the native interactive window. What can I do to solve this problem?

**Comment by fang6100146** [comment]
I have posted the same problem on stack overflow: https://stackoverflow.com/questions/69053815/where-can-find-the-old-webview-interactive-window

**Comment by joyceerhl** [comment]
Hi @fang6100146, just to clarify, are you saying that you are unable to open a variable in the data viewer that you were previously able to open? If so, that is a bug that our team would like to fix. Would you be able to provide the code and data files that the problem manifests itself with so that we can reproduce the problem on our end? 

If your question is instead about how to switch back to the webview interactive window, the native interactive window supersedes the webview interactive window and the webview interactive window no longer ships as part of the Jupyter extension. The last version which supports the webview interactive window is v2021.8.1236758218 via the setting `"jupyter.enableNativeInteractiveWindow": false`.

**Comment by fang6100146** [comment]
> Hi @fang6100146, just to clarify, are you saying that you are unable to open a variable in the data viewer that you were previously able to open? If so, that is a bug that our team would like to fix. Would you be able to provide the code and data files that the problem manifests itself with so that we can reproduce the problem on our end?
> 
> If your question is instead about how to switch back to the webview interactive window, the native interactive window supersedes the webview interactive window and the webview interactive window no longer ships as part of the Jupyter extension. The last version which supports the webview interactive window is v2021.8.1236758218 via the setting `"jupyter.enableNativeInteractiveWindow": false`.

Hello, Thanks for your reply. Depending on your advice, I have installed the older version VSCode, and it worked well.
For another question, I have uploaded my test data, it can ben opened in the webview interactive window, but no response when I try to open it in the newest native interactive window. Just like image 1. Thank You again! :)
![image](https://user-images.githubusercontent.com/39767052/132302359-af90666f-89da-47d3-bd58-0e167350760a.png)
[lan828_pre_lane1.csv](https://github.com/microsoft/vscode-jupyter/files/7119743/lan828_pre_lane1.csv)

**Comment by IanMatthewHuff** [comment]
I have a fix incoming for this. Should also clean up issues with execution count jumping up at odd times.
