### ISSUE TITLE
Cant connect C++ debugger to interactive python session anymore

### ISSUE THREAD

**Issue by tjahn** [microsoft/vscode-jupyter#7480]
## Environment data

* VSCode  1.60.0 on MacOS Big Sur 11.5.2
* remote SSH server is an OpenSuse 15.2
* ms-python.python@v2021.9.1191016588
* ms-vscode.cpptools@v1.6.0.

## Description

I develop a python extension in C++. 
For debugging I start my python script with vscode using the interactive cell mode, attach the C++ debugger from the ms-vscode.cpptools extension to the process and then start calling cells. This worked until some weeks ago (though I do not know which extension versions I used back then). 
Now the C++ debugger crashes as soon as I try to run some python cell when it is attached. With an error message in the debug output console:
```
Stopping due to fatal error: InvalidOperationException: No handler registered for request of type 'setPydevdSourceMap'!
``` 
This message does not look like it was supposed to be sent to the cpp debugger at all, but seems to be some internal message from debugpy. I did not run the cell with the python debugger though.

I first created this issue in the vscode-cpptools repository: microsoft/vscode-cpptools#8115

## Expected behaviour

I should be able to connect the C++ debugger from the microsoft/vscode-cpptools extension and use breakpoints etc in my C++ module, even when running it in the interactive python process started by vscode.

## Actual behaviour

The attached C++ debugger crashes as soon as the next interactive python cell is run from vscode with the message:
```
Stopping due to fatal error: InvalidOperationException: No handler registered for request of type 'setPydevdSourceMap'!
``` 

## Steps to reproduce:

* Install the extensions  ms-python.python and ms-vscode.cpptools.
* create a python script 
```python
# %% first run this cell to start the python process and get its PID
import os
print(os.getpid())
# %% after attaching the debugger run this cell to trigger the error
print("test")
```
* execute the first cell of the python script in vscode interactively
* attach you debugger to the printed pid using the following launch.json entry
```json
        {
            "name": "(lldb) Attach Debugger",
            "type": "cppdbg",
            "request": "attach",
            "program": "/proc/${command:pickProcess}/exe",
            "processId": "${command:pickProcess}",
            "MIMode": "lldb",
        },
```
* try executing the second cell after the debugger attached

**Comment by rchiodo** [comment]
My guess is that your kernel is ipykernel 6. Ipykernel 6 supports debugging itself and it may be detecting the attach of the C++ debugger and thinking it's talking to a python debugger.

**Comment by tjahn** [comment]
```
python3 -c "import ipykernel;print(ipykernel.__version__)"
```
tells me that I have version 5.5.5 installed. Also a pip install --upgrade says that it is the current newest version in pip.

**Comment by greazer** [comment]
Attaching the C++ debugger to a Python executable is not something that our extension can fix or adjust. I would recommend reopening the C++ issue.

**Comment by int19h** [comment]
This is, indeed, a custom DAP message that debugpy *handles*. However, it is not sent by debugpy; it is sent by vscode-jupyter:

https://github.com/microsoft/vscode-jupyter/blob/38962619f8952b06b19b7932ec4380786e3c9ee9/src/client/datascience/jupyter/jupyterDebugger.ts#L94-L106

Thus the bug is that vscode-jupyter sends the message to the incorrect debug session - the C++ one, in this case.

And I'm not sure whether this has anything to do with the C++ session debugging the same process as the Python session. VSCode has a workflow where the user can start multiple unrelated but concurrent debug sessions. If this issue also repros in that scenario, it is a genuine bug - unrelated debug sessions shouldn't interfere with each other.

(Note, however, that even with that fix, it still wouldn't work, because debuggers generally need to assume full control of the process being debugged. So having two of them trying to independently control the same process will result in all kinds of breakage, possibly unreported.)
