### ISSUE TITLE
Variable Explorer is missing.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/vscode-jupyter#7556]
## Environment data
Build of Visual Studio Code - Insiders: 1.61.0-insider (user setup)  
Build of python-insider: v2021.10.1239554536-dev
Build of jupyter-insider: v2021.9.1001236957
Build of pylance-insider: v2021.9.1
Build of jupyter Keymap-insider: v1.0.0

## Steps to reproduce:
1. Make sure Anaconda installed in local
2. Open the file src/test/datascience/manualTestFiles/manualTestFile.py in VS Code
3. On the first cell click Run Below
4. Interactive Window should open, show connection information, and execute cells
5. Click "Variables" button
6. Observes

## Expected behavior
Variable Explorer at the top of the Interactive Window.

## Actual behavior
No Variable Explorer displayed.

**Comment by greazer** [comment]
@linette-zyy, this behavior is now by design. The new interactive window does not contain an embedded variables window. Instead it is a panel in the VS Code workbench, just like for notebook variables.

**Comment by greazer** [comment]
Need to update manual test plan.

**Comment by linette-zyy** [comment]
When I click the "Variables" button, the VS code is no response. Could you tell me where I should go to see the Variable Explorer?

**Comment by Porgrammer** [comment]
I have a similar problem that I do know where to find the "Variables" tab, (next to the Console) yet there are no variables stored, 
Which also prevents the code to run since it errors out with variables being undefined. 

When I manually execute code in an interactive window command line (via Shift + Enter), it works to save the variable. But when it gets executed within a cell, it is not saved. 

Is this a related issue or should I open a separate topic? 
Thank you

**Comment by greazer** [comment]
@linette-zyy, based on what you're saying this is not an expected behavior. You're saying the variable explorer pane isn't appearing at all. Yes, this is a bug.

**Comment by IanMatthewHuff** [comment]
Note for validation. This issue only shows if just the InteractiveWindow is open in the workspace. If there is a Notebook open things will work correctly even from the InteractiveWindow.
