### ISSUE TITLE
can't copy from cell output

### ISSUE THREAD

**Issue by mmv** [microsoft/vscode-jupyter#7575]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Have a cell with a call to `print("something")`
Try to copy `something` from the output.
`Ctrl+C` doesn't work, and there's no context-menu option to do this either.

### VS Code Version

1.60.1 (user setup)

### Jupyter Extension Version

v2021.8.2041215044

### Running Jupyter locally or remotely?

Local

**Comment by matrix303** [comment]
I am having the exact same issue since a few builds ago.

After some googling, I have found an older thread that mentions this bug and offers a solution:

Old tread with same issue: https://github.com/microsoft/vscode-jupyter/issues/854

Solution:
As an immediate bypass solution: **click the terminal once so that the cursor shows up there. Then copy & paste from interactive window will work as normal**. 
Like this:
![copy_paste_bug_v3](https://user-images.githubusercontent.com/30758624/88011425-4ad4c100-cae5-11ea-97ec-219f6b5d2aaa.gif)

_Originally posted by @nevr1106 in https://github.com/microsoft/vscode-jupyter/issues/854#issuecomment-661611051_

**Comment by greazer** [comment]
Should be fixed in VS Code insiders. See https://github.com/microsoft/vscode/issues/131937.
