### ISSUE TITLE
Run by line: Toggle cell toolbar position moves RBL button

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode-jupyter#7717]
Testing https://github.com/microsoft/vscode/issues/133903

RBL button is leftmost option when cell toolbar is left:

![image](https://user-images.githubusercontent.com/25310137/135153895-86be543f-e2bd-4419-a4d8-908c1a2fa340.png)

When toolbar is toggled to the right, RBL and Continue Execution buttons swap:

![image](https://user-images.githubusercontent.com/25310137/135153948-c5065a2f-a4c2-4dfa-91f7-0b0a6c0dd640.png)

This felt a bit unexpected. Also wasn't sure if it aligned with: _Use the cell toolbar on both positions, check that the Run by Line button doesn't move when you press it_

**Comment by DavidKutu** [comment]
Thanks @bamurtaugh. That is a bit of an unusual setup.

What we wanted to avoid was the `Run by Line/Run Next Line` button shifting. That shifting happens because the `Continue Execution` appears when you're in a RBL session, and if it only appears to the right of the first button, it works fine when the toolbar is on the left, but it shifts the RBL button when you're aligned to the right.

That's why `Continue Execution` always appears towards the center of the cell.

**Comment by bamurtaugh** [comment]
Got it @DavidKutu! I actually remember this now - I think last time I tested this I noticed the RBL position shifted, which felt a bit jarring, and this is a nice solution. Thanks for the great explanation! Closing since this is working as expected from my understanding.
