### ISSUE TITLE
Pylance sometimes incorrectly flagging inside Jupyter.

### ISSUE THREAD

**Issue by cplager** [microsoft/vscode-jupyter#7774]
## Environment data

-   VS Code version: 1.60.2
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2041215044
-   Python Extension version (available under the Extensions sidebar): v2021.9.1246542782
-   OS (Windows | Mac | Linux distro) and version: Windows 10 v1909
-   Python and/or Anaconda version: 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): Conda
-   Jupyter server running: Local 

## Expected behaviour

Nothing should be flagged

## Actual behaviour

PyLance sometimes innappropriately flags code

## Steps to reproduce:

Use variable defined above

![image](https://user-images.githubusercontent.com/17601058/135616925-21096aa2-15ed-437a-9924-95108295d14b.png)

**Comment by claudiaregio** [comment]
@cplager Could you provide the code and the repro steps to how you got here? When did the error pop up? Did you happen to change kernel when the error appeared?

**Comment by cplager** [comment]
It doesn't always happen.  But basically:

`ers = pd.DataFrame({'MaturityDate':range(5)}` in a previous cell.  

No, I did not change the kernel.

**Comment by claudiaregio** [comment]
@cplager That doesn't quite look like the code you have above that cell.. it looks like a function definition? Are you not able to provide all of the relevant code? 

What I think could be happening based on the error is since we concatenate the cells to create the document that is sent to the language server, the error is saying "expected indent block" because technically the line above your error is a function definition. 

I tried the same thing in a python file and got the same error

![image](https://user-images.githubusercontent.com/19276747/135762911-0a05009d-1c2a-4798-949c-a0aa0bd8fd2c.png)

**Comment by cplager** [comment]
ers is a dataframe pulled from a database, so no, I can't easily reproduce it here.

The cell above was formatted correctly, but it is possible that it used to be a cell that was not and was deleted.  The problem is intermittent and I cannot get it to do it again.

I am OK closing this issue where I would just open a new one if I see it again.  (I am OK leaving it open for a while to see if the problem comes back.

Thanks!

**Comment by greazer** [comment]
Thanks for the feedback! However, what you're experiencing is currently due to the way we are supporting Intellisense in a notebook (it concatenates the cells). Going forward we may revisit how this is done as it has other side-effects as well.
