### ISSUE TITLE
Unable to copy native notebook cell outputs

### ISSUE THREAD

**Issue by ldorigo** [microsoft/vscode-jupyter#7792]
Issue Type: <b>Bug</b>

I am unable to copy the outputs of native notbook cells. The usual shortcut ctrl-c does not work, and right-clicking does not give the option to copy the output (only the cell). 

It seems like in some occasions ctrl-c does work, but I have been unable to figure out when or reproduce it. 

Extension version: 2021.8.2041215044
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:06:57.931Z)
OS version: Linux x64 5.14.6-zen1-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics (16 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|30.78GB (9.62GB free)|
|Process Argv|. --crash-reporter-id 9614dc43-c276-4d0e-94fc-c84de505d77f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma-i3|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE-i3|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by DavidKutu** [comment]
Thanks for filing @ldorigo. 

We do have commands to copy the whole cell. To use them, get the cell in command mode (where there's a blue line on the left of the cell, and the editor is not selected). Then the keybinding is just `c` and then just `v` (no ctrl). Its done that way because that was already the default for notebooks.

You can also right click on the cell (and outside the editor) to see the `c` and `v` commands, and finally, they also show up if you press the `...` button on the cell toolbar.

Let me know if that helps.

**Comment by rchiodo** [comment]
This should be the same issue as this one:
https://github.com/microsoft/vscode/issues/134249
