### ISSUE TITLE
Notification overload when installing ipykernel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-jupyter#7907]
Testing microsoft/vscode#114969

I pressed install and I got 3 notifications and the original showed up again. This was so many notifications some were hidden immediately:

![image](https://user-images.githubusercontent.com/2193314/105882714-d3fc1180-5fba-11eb-8983-54cb0378291b.png)

Additionally, the connecting to kernel notification never ends 😱

**Comment by IanMatthewHuff** [comment]
Been working through some getting started issues this iteration. We have a couple of issues dealing with trying to reduce the amount of times that customer see the ipykernel install message. But the specific problem with the notification in this issue is the "missing pip" situation. As such I'm closing it in favor of the vscode python issue intended to handle this:
https://github.com/microsoft/vscode-python/issues/15937
