### ISSUE TITLE
Support remote server being treated like a 'local' server when on same machine as VS code extension host

### ISSUE THREAD

**Issue by lasergyro** [microsoft/vscode-jupyter#7976]
Current Working Directory is not the current notebook directory.

This goes against default behaviour in jupyter notebook and jupyter lab.

Can this be fixed? If not, how can I automate setting the current work directory to the file location? Is there some environment variable that is set to the current notebook file that I can read in a setup cell?

## Environment data

-   VS Code version: 1.61.1
-   Jupyter Extension version (available under the Extensions sidebar): v2021.9.1101343141
-   Python Extension version (available under the Extensions sidebar): v2021.10.1336267007
-   OS (Windows | Mac | Linux distro) and version: Windows 21H1
-   Python and/or Anaconda version: 3.9
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote

## Expected behaviour

`from pathlib import Path; Path.cwd()` returns the directory where the current notebook is.

## Actual behaviour

The directory where the jupyter remote server was started is returned.

## Steps to reproduce:

1. Externally, start jupyter server at `~`
2. Create folder at ~/a
3. Create folder at ~/a/b
3. With vscode remote ssh, open ~/a.
4. Run vscode command to create notebook at ~/a/b/c.ipynb
5. In the notebook, run `from pathlib import Path; Path.cwd()`

**Comment by rchiodo** [comment]
Thanks for the bug. We don't currently control the path where you start the remote server. A kernel from the remote server will default to that path when starting.

You can either:
- Start the jupyter server at a different location
- Change the directory in a cell
- Not use a remote server (remote ssh is supported by the jupyter extension). If you just use 'Default' on this picker here:

![image](https://user-images.githubusercontent.com/19672699/138129647-4ebfe5f7-c28f-41f7-9a0e-4bb6da3ad099.png)

VS code will start the 'remote' server on the box itself. It will then use this setting when starting the kernel:

![image](https://user-images.githubusercontent.com/19672699/138129722-b5bfbd24-5a6f-40c2-b64b-d7abf83b410a.png)

Which should default to the same directory as the notebook.

**Comment by rchiodo** [comment]
In the remote server case where you're using remote ssh, the fact that your remote server and VS code are running on the same machine is a coincidence. Normally when connecting to a remote server, the machine is not in the same place as your code. 

We don't know the directory structure of the remote machine for remote servers so we can't force the ${fileDirname} on the kernel when launching. The ${fileDirname} is for the 'local' machine.

That's why I recommend you just let us create the jupyter server. Then we know the kernel is on the same machine that the VS code extension host is running at.

**Comment by rchiodo** [comment]
This is the hard part:

> then set the cwd to the relative path from the server to the notebook

What's the path that the server started at? We could potentially get cwd from the active jupyter server by querying the process itself, but then we'd have to figure out _which_ process is the jupyter server. Potentially we could start a dummy kernel though and have it output the cwd for us to read. But then we'd have to also make sure the machine is the same.

But since you have VS code on the same machine, there's no need to run the server yourself. You can just have us start it. 

I don't think we'd do the extra work to make remote servers behave like local servers when they are on the same machine as the VS code server. 

Is there a reason you want the remote server there? Maybe sharing with other people that don't use VS code?

**Comment by zpincus** [comment]
FWIW, perhaps the "real" fix here is to figure out ways to address / mitigate the substantial pain-points of using the "local" jupyter server, succinctly noted above by @lasergyro -- which keep coming up in various guises (e.g. #1378, #1654). It's ultimately these issues that cause folks like me and @lasergyro to turn to the "remote" server option even locally on the same machine vscode is running on (or that the remote-ssh extension is running on).

**Comment by TTTPOB** [comment]
> is there a reason you want the remote server there? Maybe sharing with other people that don't use VS code?

for me there is just one reason:
remote sessions won't be closed when i close vscode

a job lasting for days is common for me, I can't keep my laptop connected to the server for like a few days

**Comment by DonJayamanne** [comment]
I'm closing this issue as there haven't been enough upvotes to warrant this feature requets.
Today remote servers are treated as completely remote, and trying to make it work like it was a local maching but using remotes would require a lot of changes with `if` conditions complicating the code.
