### ISSUE TITLE
Create new notebook fails, opening existing notebook does not work (Proposed API error).

### ISSUE THREAD

**Issue by Moarqi** [microsoft/vscode-jupyter#8082]
## Environment data

-   VS Code version: 1.61.0
-   Jupyter Extension version: v2021.9.100
-   Python Extension version: v2021.10.1365161279
-   OS and version: Manjaro 21.1.6
-   Python and/or Anaconda version: 3.9.4
-   Type of virtual environment used: conda
-   Jupyter server running: Local

## Expected behaviour

A clean install of vscode and the respective extensions should create and open jupyter notebooks properly.

## Actual behaviour

- Opening an existing jupyter notebook enables to create and edit cells, but there is no possibility to execute them. 
- `Jupyter: Create New Jupyter Notebook` shows error: `command 'jupyter.createnewnotebook' not found`, nothing more happens.

In both situations, the developer tools console prints the following error:

`[ms-python.python]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api ms-python.python`

See trace in screenshot below.

## Steps to reproduce:

For my configuration, the following steps did not resolve the error:

1. uninstall vscode
2. clear data in `~/.config/Code - OSS/` and `~/.vscode/`
3. install vscode
4. install python and jupyter extension, select proper python interpreter
5. try to create a new notebook using `Jupyter: Create New Jupyter Notebook` or open an existing notebook

## Error screenshot 

![image](https://user-images.githubusercontent.com/11090559/139220440-49534ab4-e4c7-43d7-854c-e5ad1d72733d.png)

**Comment by joshuamegnauth54** [comment]
I have the same issue across two different computers running Arch Linux with the stable release of VSCode. Manjaro and Arch are related distributions, so maybe that's relevant in some way?

I tried launching VSCode with the `enable-proposed-api` switch. The Jupyter extension fails to load existing Notebooks and new Notebooks are blank. The extension's elements show when loading an existing Notebook but don't when creating a new Notebook.

**Opening an existing Notebook:**
![image](https://user-images.githubusercontent.com/48846352/140099054-f381baf9-7047-4ed7-b57c-43ab25fe0d06.png)

**Blank Notebook:**
![image](https://user-images.githubusercontent.com/48846352/140099226-af1a48bc-c227-4d2f-bb3d-0dc943fbe875.png)

**Comment by IanMatthewHuff** [comment]
Hmmm interesting. I don't have access to an Arch Linux machine right now, but I'm checking out the docs online. I was a bit confused that there were Code - OSS directories that were listed as those directories are not usually in the official VS Code releases.

Looking around I believe that I see the answer here. It looks like ArchLinux by default installs Code - OSS (which is not the official Microsoft release, but should function normally). 

https://wiki.archlinux.org/title/Visual_Studio_Code

The actual official Microsoft release looks like it's `visual-studio-code-bin` not `code`. Looking further into the link above it looks like the "Command Not Found" issue is a known issue with Code - OSS, as Code - OSS doesn't recognize specific extensions that are allowed to use the proposed API in stable builds. This sounds exactly like the symptoms that you are seeing. I think that the advice would be to add in those extensions (probably Python and Jupyter here) as detailed as here from the above link:
```
Command "..." not found
In the official build of VS Code, a product.json file lists the extensions that are allowed to use certain proposed APIs accessed by extensions. However, the product.json is absent in the OSS build code. [1]

In the related issues below, some flags may be required to enable certain APIs. [2] You may either run code with these flags, or you can add the relevant entries to the extensionAllowedProposedApi section in the product.json file (code installs this to /usr/lib/code/product.json).

"extensionAllowedProposedApi": [
    "ms-vsliveshare.vsliveshare",
    "ms-vscode.node-debug",
    "ms-vscode.node-debug2"
]
This can also be resolved by installing the code-featuresAUR package, which installs a pacman hook that patches the file on every package update. Alternatively, you may also consider installing the Microsoft branded packages: visual-studio-code-binAUR, visual-studio-code-insiders-binAUR.
```

Or to install the official Microsoft release of vs code instead of Code - OSS.

**Comment by IanMatthewHuff** [comment]
I actually think that python might not need to be listed with proposedAPI anymore as that API is stable now. Looking into this.

**Comment by IanMatthewHuff** [comment]
No that API is still in proposed. I think that the best that you can do now is to fix up Code - OSS or move to the official MS package. If you still see the same issue with the official MS package just report here and I can help to investigate.

**Comment by Moarqi** [comment]
@IanMatthewHuff ah, that totally makes sense! 
Thank you for your investigation and time, that is something I could have found :/

I managed to resolve the issue by adding `"ms-toolsai.jupyter"` to `"extensionAllowedProposedApi": [..]` in `/usr/lib/code/product.json` as suggested.
Closing the issue.
