### ISSUE TITLE
Remove DD as shortcut to delete a cell in Jupyter

### ISSUE THREAD

**Issue by s2500111** [microsoft/vscode-jupyter#8099]
Who thought, this was a good idea, to use a frequently used key as a short cut to delete your work, especially, as currently, the  undo option is somewhat randomly deciding if it brings the cell back or not?

Didn't know, that shortcut until right now, just wondered, why my cells kept disappearing. Yeah, missclicked, so cells where in command mode and two times hitting d is enough. If you do something afterwards and only then find that your cell is gone, you can go and redo your work ...

**Comment by claudiaregio** [comment]
Hi @s2500111, if you'd like to customize your keyboard shortcuts go to File -> Preferences -> Keyboard Shortcuts. Type 'delete cell'. You'll want to update the highlighted contributed by the extension in the 3rd row below. 

![image](https://user-images.githubusercontent.com/19276747/139498106-327a7d6a-0cae-4e04-83c9-ea3327d681e4.png)

**Comment by stellarpower** [comment]
It would be advantageous to be able to turn this feature off completely. I am trying to type in my notebook, all sorts of things fly in front of me, and I don't know what happened, and as the OP says, undoing it either does nothing or what it does is off-screen, and I'm now concerned I lose even more by trying to go back. I thought I'd managed to bluff through it, but I now have code that has been missed off VCS and permanently lost because of this. I totally understand the need to have parity with Jupyter. Hats off to them, they successfully managed to make working in Python even more painful than it already was. But rather than having to go in and wipe all the available shortcuts, it would be really useful simply to have a toggle switch that can disable this "command mode", or whatever it is. Personally I never put anything destructive like that without a shortcut that takes some effort, so I don't know what the original interface designers were thinking. I guess it arguably is Pythonic: "Pressing the d key deletes my work." "Well, don't press it then". Problem solved.

Thanks

**Comment by DonJayamanne** [comment]
@jeremytchang 
Sorry yo'ure running into this issue, you should be able to configure your own shortcuts or just un-install the Jupyyter Notebok keyboar shortcuts extension.

**Comment by jmcapra** [comment]
If `d d` is the accepted standard, then sure, let's keep it. I place a strong vote for improving the ability to UNDO this operation, which as mentioned is not always possible. I think that is the core area for improvement here - a more robust undo/redo framework built with modern computing resources in mind. 

E.g., has anyone ever encountered that frustrating situation where you ctrl+Z a bunch of times, then accidentally make one change and lose your entire redo history? (are there any extensions for this?)
