### ISSUE TITLE
No indication kernel is starting if using run-by-line before starting kernel.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8202]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Open a notebook.
2. Start the first cell with run-by-line before running any other cell.

Seems to work, but there's no indication of what's happening. 

### VS Code Version

Version: 1.63.0-insider (user setup) Commit: a7104f13ff61bcd9f4c827d8fe3c0d27bb479fd8 Date: 2021-11-08T05:14:49.440Z Electron: 13.5.1 Chrome: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22494

### Jupyter Extension Version

v2021.10.1001414422

**Comment by DonJayamanne** [comment]
Could be auto start that's hiding the progress.
@greazer , please could you try this again, but open a python file, wait for a minute or so (you have some slow conda environments, hence I'd wait at least for a full minute) & then try this scenario again.

I'm certain you'll get the progress indicator 
Note: we turned off auto start because of this exact same issue (you ran into) with notebooks, & we didn't turn it off for inteactive window as identified here https://github.com/microsoft/vscode-jupyter/issues/7624.

**Comment by greazer** [comment]
This is not an interactive window problem. This is notebook run-by-line. I still do not see any indication that a kernel is starting if you. 
1. Load an ipynb
2. Click the run-by-line button as soon as it's available.

**Comment by rchiodo** [comment]
Looking into this now.

**Comment by rchiodo** [comment]
I can't repro this problem. It shows status regardless of if I use jupyter or raw.

**Comment by rchiodo** [comment]
May have been fixed by Don's recent kernel status changes.

**Comment by rchiodo** [comment]
@greazer can you try with the latest bits?

**Comment by roblourens** [comment]
Works for me, I'll mark it as verified
