### ISSUE TITLE
Register Jupyter as a language identifier by default

### ISSUE THREAD

**Issue by ivaquero** [microsoft/vscode-jupyter#8503]
I would like to activate the extension `json-color-token` in `.ipynb` files to change colors in a handy way when plotting. However, it needs a language identifier.

I didn't find jupyter in the know identifiers list at [https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers).

Could you please register Jupyter as a language identifier by default? Or is there any instruction that helps me to handle this by myself ?

**Comment by IanMatthewHuff** [comment]
@ivaquero Can you activate using the "onNotebook:jupyter-notebook" activation event? Jupyter not being in the language list is intentional as a Jupyter notebook isn't a language itself, just a container that contain cell of Python, Julia, R, or whatever else. We don't put it in the known languages list as that leads to some oddities like the ability to create a "Jupyter" language cell in a Jupyter document.

**Comment by DonJayamanne** [comment]
You could optionally just ship your extension with a custom language for *.ipynb files. that way when ipynb files are opened as plain text (i.e. as JSON), then your extension will get activated.
Hopefully that would be sufficient.
