### ISSUE TITLE
Cleanup our *suggested* kernels to ensure we lead people down "good" paths. 

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#8530]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Open a notebook
2. Click the "Select Kernel" button

<img width="542" alt="image" src="https://user-images.githubusercontent.com/11685408/145659283-22f27bb7-72a2-4a0d-9fdf-475b35b4eb3d.png">

On my machine a "base" conda environment is suggested. My understanding is that this is something that the Python community is trying to change about how people use Python. 

### VS Code Version

Version: 1.64.0-insider (user setup) Commit: 065b450db9f555f177161748e8f2911ebb5677f9 Date: 2021-12-10T05:14:44.789Z Electron: 13.5.2 Chromium: 91.0.4472.164 Node.js: 14.16.0 V8: 9.1.269.39-electron.0 OS: Windows_NT x64 10.0.22509

### Jupyter Extension Version

v2022.1.1001562662

**Comment by abatomunkuev** [comment]
@greazer  

Hello! 

I think we can change it to the environment that was previously used by the user and mark it as suggested so that the user doesn't have to specify the environment again. 

Maybe for the initial start (very first start), we can ask the user: "what environment would you like to choose". Once the user selects the environment, we can mark it as suggested. From there, every time user creates a new notebook, the environment will belong to the one that the user has chosen previously (marked as "suggested").

**Comment by abatomunkuev** [comment]
I would like to work on this issue, if it is relevant! I may need some assistance.

**Comment by greazer** [comment]
Couple things. 
1) Yes we should avoid *suggesting* kernels or python versions that could be dangerous or lead to bigger problems. 
2) What do we do if the notebook has one of the problem kernels already specified?

**Comment by greazer** [comment]
Split out @abatomunkuev  into a separate issue.

**Comment by greazer** [comment]
Opened https://github.com/microsoft/vscode-jupyter/issues/9115 to track @abatomunkuev's request. Closing otherwise. It's ok to suggest "base" for a conda environment. I was confusing this with installing packages to interpreters outside any environment.

**Comment by roblourens** [comment]
Sounds like nothing was changed here, removing it from the verification query
