### ISSUE TITLE
jupyter cannot enable widgetsnbextension

### ISSUE THREAD

**Issue by zesluo** [microsoft/vscode-jupyter#9071]
## Environment data

Version: 1.64.2 (user setup)
Commit: f80445acd5a3dadef24aa209168452a3d97cc326
Date: 2022-02-09T22:02:28.252Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

it pops up with an error message:  'Exit with non zero 3221225477' when I use the below command in my spark and hive tool. I have virtual env. Previously it worked. It start broken from last month.  

C:\\Users\\xx\\.msvscode.hdinsight\\hdinsightJupyter\\Scripts\\jupyter.exe nbextension enable --py  --user --sys-prefix widgetsnbextension 

jupyter:
v2022.1.1301854968

vscode-python:
v2022.0.1814523869

Thanks.
## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by amunger** [comment]
From searching for that error code, it looks like you have a [compatibility issue](https://stackoverflow.com/questions/62804960/setup-py-install-for-mayavi-error-code-3221225477) with python modules, and not due to anything in the VS Code extension, so we're not going to be able to help much with this. 
I'd suggest trying to ask on Stack Overflow for help, or try your scenario again in a fresh Python virtual environment.
