### ISSUE TITLE
Don't start kernel daemon for non-python kernels.

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-jupyter#9298]
Request is to hide the "Jupyter: Debug Cell" command for .NET Nb. 

Just had a user try to use it while using C# in a notebook and it completely broke their setup :( 

We want to make sure users don't think they can use this debugging feature to the point where they are completely broken.

**Comment by rchiodo** [comment]
I think the user in your scenario was actually using a .NET kernel from Jupyter (not .NET interactive). We should make sure to disable debug cell for non python kernels.

**Comment by rchiodo** [comment]
The command on the dropdown is already hidden:

```json
            "notebook/cell/execute": [
                {
                    "command": "jupyter.runAndDebugCell",
                    "when": "notebookType == jupyter-notebook && jupyter.ispythonnotebook && notebookCellType == code && isWorkspaceTrusted && !jupyter.notebookeditor.runByLineInProgress"
                }
            ],

```

**Comment by rchiodo** [comment]
The command itself isn't flagged with a when clause though:

```json
            {
                "command": "jupyter.runAndDebugCell",
                "title": "%jupyter.command.jupyter.debugCell.title%",
                "icon": "$(debug-alt-small)",
                "category": "Jupyter"
            },
```

**Comment by mrsharm** [comment]
Just experienced an issue where my workflow was affected right after choosing "Jupyter: Debug Cell". 

Whenever I tried to open a notebook, I got the following error:


``Error: The kernel died. View Jupyter [log]() for further details. Error: Unhandled exception: System.IO.IOException: The process cannot access the file 'C:\Users\<UserName>\AppData\Local\Temp\tmp-4836JTB1GoV0BpKh.json' because it is being used by another process.``

*Things I tried*

- Deleting the file manually -- doesn't work since the Code.exe process still is holding on to it.
- Closing VSCode and reopening -- doesn't fix it .. just creates a different tmp file in C:\Users\<UserName>\AppData\Local\Temp
- Closing the notebook and reopening leads to the same error.



To debug, I first looked up which process was holding the tmp file using ProcessExp and figured out it was a python process whose parent was a VS Code instance with the following command line args: "C:\Users\<UserName>\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --inspect-port=0 "c:\Users\<UserName>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork" --type=extensionHost --skipWorkspaceStorageLock

![image](https://user-images.githubusercontent.com/68247673/157355905-ccafc098-91de-47e2-9408-e1751d98d90b.png)

This gave me a hint that it must have been the Jupyter extension. And so I uninstalled the .NET Interactive VS Code Extension, uninstalled the Jupyter extension and then reinstall both and that fixed it.

A symptom of the issue was that I could put breakpoints in my notebook cells:

The full call stack is: 

[jupyter error.txt](https://github.com/microsoft/vscode-jupyter/files/8210943/jupyter.error.txt)

**Comment by rchiodo** [comment]
What's the command line for the python process that was started?

**Comment by mrsharm** [comment]
I think I am able to repro this issue. Whenever the kernel is changed to .NET (C#) dotnet from .NET Interactive, I am unable to execute the cells of the notebook and the aforementioned issue shows up:

![image](https://user-images.githubusercontent.com/68247673/157817534-2ff5b709-cf24-4d1a-b6c6-714fccb4b5ef.png)

The python command line args are:
```
C:\Users\<Username>\AppData\Local\Microsoft\WindowsApps\python3.7.exe -m vscode_datascience_helpers.daemon --daemon-module=vscode_datascience_helpers.kernel_interrupt_daemon -v --ppid 1508
```

I am convinced that choosing the "Jupyter: Debug Cell" automatically changed the Kernel to .NET C# and at this point, all the badness began. 

The fix was to simply change the selected kernel and update all the cells to now point to the ".NET Interactive" flavor of C#.

**Comment by rchiodo** [comment]
We may be starting the interrupt daemon for non python kernels. That would be bad. I'll have to double check that. That's the python process you show in your command line args. Although not sure how it would have the file open? Maybe it's through file handle inheritance from the old kernel.

**Comment by rchiodo** [comment]
@mrsharm can you verify we've fixed your problem? 

To verify:
- Install [VS code insiders ](https://code.visualstudio.com/insiders/)
- Install the latest 'prerelease' jupyter extension
- Repro the steps you had before

Verify your kernel doesn't immediately die.

Thanks.

**Comment by mrsharm** [comment]
@rchiodo, just tried this out and seems like the "Jupyter: Debug Cell" option is still there, however, it doesn't break my workflow i.e. no issue with executing the cells after the selection. 

Thanks for the help!
