### ISSUE TITLE
Unable to find extension qgrid

### ISSUE THREAD

**Issue by KoroNiko** [microsoft/vscode-jupyter#9381]
## Environment data

-   VS Code version: XXX
-   Jupyter Extension version (available under the Extensions sidebar): XXX
-   Python Extension version (available under the Extensions sidebar): XXX
-   OS (Windows | Mac | Linux distro) and version: XXX
-   Python and/or Anaconda version: XXX
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Jupyter server running: Local | Remote | N/A

## Expected behaviour

XXX

## Actual behaviour

XXX

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. XXX

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by rchiodo** [comment]
Thanks for the issue. This is likely the same problem as this issue here:
https://github.com/microsoft/vscode-jupyter/issues/1974

QGrid hasn't been updating their js package on npm. We therefore cannot render it. 

If you open 'Help | Toggle Developer Console' there should be some errors about not being able to load qgrid and a version number. 

If you look on jsdelivr.com (one of the CDNs we use to look for widgets), you'll see that qgrid is only supported up to version 1.1.1.

![image](https://user-images.githubusercontent.com/19672699/158637659-275d89f8-6bed-48e4-a9ed-f019eca03d1c.png)


Ideally qgrid would update their npm package. I suggest logging a bug on qgrid to update their bits in npm.
