### ISSUE TITLE
Expose the “suggested kernel” API

### ISSUE THREAD

**Issue by kjcho-msft** [microsoft/vscode-jupyter#9412]
For VS Code extension we are working on, it’d be helpful if there is a way to tell which kernel is recommended/suggested. Would it be possible to expose the “suggested kernel” API that is used in VS Code Jupyter’s kernel picker? 

![image](https://user-images.githubusercontent.com/26585299/158927686-13925147-1d9d-4e3d-a26c-9584a9543e7f.png)

## Environment data

-   VS Code version: 1.66.0-insider (user setup)
-   Jupyter Extension version (available under the Extensions sidebar): v2022.3.1000781005
-   Python Extension version (available under the Extensions sidebar): v2022.2.1924087327
-   OS (Windows | Mac | Linux distro) and version: Windows 11
-   Python and/or Anaconda version: Python310
-   Jupyter server running: Local

**Comment by jruales** [comment]
Ideally, we'd want to be able to replicate the exact same Quick Pick on our side, so we would ideally also have "Conda Env" and "Global Env" flags, as well as any other info we'd need to replicate the Quick Pick, if any

**Comment by DonJayamanne** [comment]
the quickpick is generated by vscode.
will discuss with the team.

note, you can build the quickpick today using vscode api and using the list exposed to extension authors . that's pretty much what we'd have to do, and im personally in favor of this code going into the other extension instead of jupyter.

e. g. we don't have a quick pick to allow users to select an existing live local kernel, that's something you'll need to do (we have no such functionality nor any existing ui for this).

**Comment by DonJayamanne** [comment]
>  so we would ideally also have "Conda Env" and "Global Env" flags, as well as any other info we'd need to replicate the Quick Pick, if any

@jruales
This information is already provided today. Each kernel	 as an interpreter propery

Here's the info 
```typescript
    getKernelSpecifications(refresh?: boolean): Promise<KernelConnectionMetadata[]>;

KernelConnectionMetadata = .. | PythonKernelConnectionMetadata | ..

export type PythonKernelConnectionMetadata = Readonly<{
    kernelSpec: IJupyterKernelSpec;
    interpreter: PythonEnvironment; // This contains the information about the Python interpreter
    kind: 'startUsingPythonInterpreter';
    id: string;
}>;

export type PythonEnvironment = {
    displayName?: string;
    path: string;
    version?: PythonVersion;
    sysPrefix: string;
    envType?: EnvironmentType; // This will tell you if its Conda or not
    envName?: string;
    envPath?: string;
};


```

**Comment by DonJayamanne** [comment]
TODO:
As part of this issue, we're to expose an API that provides the suggested kernel.
E.g. we can have a method as follows:
```typescript
getSuggestedKernel(notebook: NotebookDocument): Promise<KernelConnectionMetadata | undefined>
```

**Comment by pwang347** [comment]
@DonJayamanne apologies for the late reply, only saw this now. Makes sense, I think from what I understand you're saying that the detection logic depends on factors like what is the kernelspecs within the ipynb file etc. And since we don't have an actual ipynb file it's not really useful.

For the purposes of our application, I think a "preferred kernel" would be something like the latest interpreter version + dependencies are installed. The former is pretty trivial and I'm not sure if the latter is something that is currently being checked by the Jupyter extension (since it presumably requires a connection).

Unless there's more happening under the hood that I'm missing from my description above, maybe this is something we should implement ourselves. Thanks!

**Comment by DonJayamanne** [comment]
> something like the latest interpreter version + dependencies are installed.

We don't perform such a validation (i.e. we never check if dependencies are installed).

> t I'm missing from my description above, maybe this is something we should implement ourselves. Thanks!

Closing as something 3rd party extensions would have to do.
For your use case, i'd say access the Python API and determine what the active interpreter is , and match that against the kernels and find the kernel that points to that same python interpreter.
