### ISSUE TITLE
Mitigate slow kernel discovery (API adoption, placeholder kernels, measurements) 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9628]
https://github.com/microsoft/vscode-jupyter/issues/5861

**Problems**
* Unable to run a cell after opening a notebook for first time after installing VS Code
	* Basically user needs until all Python interpreters have been discovered. This can be very slow depending on a number of factors.
	* The users perception is `They cannot run a cell`

Tasks/Suggestions:
* Review (& provide feedback) the new Python API
	* What will it take to implement this
	* Do we need changes in the API
* [ ] Progress indicator for kernels loading/being fetched (would be be of any value?)
* [ ] Add a placeholder lazy kernel for `Python`? (see corresponding issue with usecases for Lazy kernels)
* [ ] Add active interpreter as a controller (while discovering other interpreters)
* [x] Add telemetry (if we don't already have this) to determine how quickly we return controllers
* [x] Add telemetry (if we don't already have this) to determine how quickly we get interpreters from Python extension

**Comment by DonJayamanne** [comment]
![Placeholder](https://user-images.githubusercontent.com/1948812/162663736-e3f37a59-c6e4-4632-b5e7-ebb49466312b.gif)

![SlowDiscovery](https://user-images.githubusercontent.com/1948812/162664181-c1baa92b-e322-45e1-ad81-d13f375302ba.gif)

![JupyterIsFaster](https://user-images.githubusercontent.com/1948812/162664354-65fbfd5a-bf10-43c6-9fb5-5fe983849887.gif)

**Comment by Tma2333** [comment]
Hi, glad to see this issues is being address. Thank you very much! Want to give my experience here. I am developing on shared server with network attached drive and large amount of conda environment, the Discovering Python Interpreters process could take hours to complete. My only saving grace was the last used kernel will be saved? (I found there is some information being saved in `temp`). However, if I need to use more than one environment, I am basically out of luck.  

It will be great if there is an option where we can manually give the path to the interpreter, rather than wish Discovering would be done quickly or the correct interpreter shows up eventually.

**Comment by DonJayamanne** [comment]
@Tma2333 please could you for an issue with the problems you are facing. currently we do cache kernels for jupyter. please file an issue and we can continue the discussion there

**Comment by DonJayamanne** [comment]
Closing as this isn't requried anymore and all of the work has been done or no longer relevant.
