### ISSUE TITLE
DataFrame working in web extension

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9665]
Only difficulty might be in getting the dataframe scripts to run on the remote jupyter machine.

**Comment by sadasant** [comment]
After meeting with @DonJayamanne and @rchiodo , we now have a path forward regarding this issue.

Our priority is to solve this issue, so first we will make sure to enable the Data Frame viewer on the web:

- By changing the `IDataViewerDependencyService` to receive an `IKernel` besides the `PythonEnvironment` that it receives today.
- By adding a universal version of the `dataViewerDependencyService` that would only work if `IKernel` is provided and throw otherwise an error saying `Installation of "pandas" not supported while debugging. Please ensure you have "pandas" installed.`
- By keeping the current node-specific version of the `dataViewerDependencyService` that would extract the interpreter from the `IKernel` if the `IKernel` is provided.
- Besides ensuring the `dataViewerDependencyService` is registered on the web service registry, and removing the conditional that disables the Data Frame on the web.

This approach is a compromise of a more valuable set of changes, which will come with other PRs. You can see the current plan at: https://github.com/microsoft/vscode-jupyter/issues/10638
