### ISSUE TITLE
Support multiple remote servers

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#9684]
As part of the lazy kernel exploration https://github.com/microsoft/vscode/issues/146942#issuecomment-1097405365 , we want to support multiple remote servers, which would allow each notebook to use their preferred remote server, contributed by remote jupyter server provider.

**Comment by DonJayamanne** [comment]
While refactoring the kernel code I explored this task and at that point the plan was to add the Uri (some of remote connection info) into the kernel connection & when starting/connecting to the remote server we'd use that information instead of assuming the connections was in the single setting. 

This was discussed with the team, however not completed. Can't remember why it wasn't completed, either ran out of time or just lost track of it. One use case was the ability to connect to multiple remotes and display in the kernel manager.

**Comment by DonJayamanne** [comment]
Will not be done as we don't see the need to support multiple remotes for now.
