### ISSUE TITLE
Set preferred kernel only when Jupyter finds exact match

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode-jupyter#9685]
With https://github.com/microsoft/vscode/issues/146339, VS Code will now pre-pick the suggested kernel if there is only one. With this change, users will less likely see the kernel quick pick and use the suggested kernel by default. It's a good thing if the suggested kernel is exactly matching the kernel spec info in the notebook document, but if it's a fuzzy match, it has chances to be the wrong one. We might want to relax this a bit: only set the kernel to preferred when it's exact match.

**Comment by DonJayamanne** [comment]
> want to relax this a bit: only set the kernel to preferred when it's exact match.

I've run into this exact same issue with the improvements to loading kernels when discovering Python.

> only set the kernel to preferred when it's exact match.

Not sure about this, preferred doesn't mean exact match. E.g. even if something is a fuzzy match we nominate it as a preferred/suggested kernel. I think there's a confusion with the API. In the UI we display it as a `suggested` (that's the wording used in the UI) kernel. 
Surely even if there's no exact match we shoudl be able to nominate a kernel as a recommended kernel. E.g. assume user doesn't have a kernel that never matches something, in that case we should at a minimum recommend the next best thing.

I think the issue can be avoided if we don't have just one kernel. I.e. if we have mulitple, then it will never be an issue.
& I dont think we'll ever have one kernel, except in the case where the remote kernel no longer exists, & in that case its valid to nominate the `kernelspec` as the preferred kernel.

**Comment by rebornix** [comment]
> I think the issue can be avoided if we don't have just one kernel. I.e. if we have mulitple, then it will never be an issue

@DonJayamanne this is another option we discussed and I'm good with either. With VS Code auto-picking the only suggested, my concern is users would find it annoying when the "suggestion" is not accurate and end up using the wrong one without knowing it in advance. Showing more than one suggested kernel can help, e.g., making all Python 3.x kernels as suggested when the language/kernelspec says "python3".

**Comment by IanMatthewHuff** [comment]
I think part of the discussion from the standup was some doubts about this being true:

> E.g. assume user doesn't have a kernel that never matches something, in that case we should at a minimum recommend the next best thing.

Or at least some doubts about our ability to know the next best thing via fuzzy matching. I want to look more at our matching code, but the assumption that if 3.9.3 is requested then 3.9.2 is better than 3.9.1 feels iffy. The distinguishing factor is quite possibly in the name of the kernel (myPytorchKernel, CoolProjectKernel, ect...) which is something that we don't and can't make our best guess on. But yes, discussing in standup sounds good.

**Comment by IanMatthewHuff** [comment]
Adding a note here to continue / follow up from our standup.

To keep the discussion limited we're specifically looking at any changes that we should or need to make based on the change in https://github.com/microsoft/vscode/issues/146339. In which if there is now only one single suggested kernel then that kernel will be autoselected by VS Code core, without having to have the kernel picker pop up. Bigger discussion should happen in https://github.com/microsoft/vscode-jupyter/issues/9615 for longer term goals.

Option A: Remove Fuzzy Matches, set affinity only on an exact match.
Work: Change the CompareKernels function. 
Results: When we are very sure of the kernel it will now get auto-selected and user doesn't need to see the quick pick. However, if we have looser suggestions we can't surface the "best" of our looser suggestions unless we want it auto selected in the quick pick.

Option B: Don't remove the Fuzzy Matches, continue to set affinity as we do now.
Work: None (yet)
Results: Previously the kernel picker would be invoked if we only had suggested matches and no exact match. Now that best possible match will be elevated to auto selected in the kernel picker and automatically run. This might be ok? If it's still our best guess at the correct match then the user might be more likely to have success with it.

Option C: Categorize matches different between exact / fuzzy. Return singles. Group suggestions.
Work: Results would have to be moved back to a score of some type, unless we just take the top X of the list or something like that.
* If we have a single exact match, return it
* If we have a single suggested match, return it
* If we have multiple suggested matches, return them all, or return top X of them
Results: If you have an exact match, it's auto selected. If we only have one suggestion, it's auto selected. If we have multiple suggestions, the kernel picker is invoked but we still give guidance via multiple suggestions.

Option D: Keep things the same, but add telemetry.
Work: Telemetry added around situations where we suggest the "incorrect" kernel. Via the definition that the user switches the kernel manually after auto selection to actually use the notebook. (or switches after X number of executions). Note, we might already have the telemetry for this in place, just analysis that is needed.

**Comment by greazer** [comment]
CCing my opining from our recent sync here: 

Personally, yes, truly IM(current)O, I'm hesitant that we should bother ever suggesting kernels if we do not know they are an exact match, even in the kernel picker. UNLESS, the user can easily reason why they are suggested. If they have to have our heuristic algorithm memorized, then I think there's a problem as they have to keep a lot in their head that really shouldn't be necessary.  I'm afraid that any form of heuristic/ranking model will be difficult to reason about.

What's easy to reason about, IMO?

* Don't suggest any kernel if there's no exact match AND a kernel hasn't been chosen before in the ipynb's workspace. User has to make a choice.

* If a kernel has been chosen for a different ipynb in the same workspace, then default to that going forward until it's changed again (again if there's no exact match). Seems more likely that for given workspace a single kernel/environment will be used.

* Don't choose the active interpreter unless the user can see the active interpreter on the screen. Currently, I It's not shown when an ipynb has focus.

* If a user starts VS Code from an activated Python environment (Conda in particular) and an opened ipynb does not have an exact interpreter match, we use the activated environment by default. Maybe we don't even allow the user to change it in this case... Not sure that's a good idea, or even feasible.

BTW, the idea that a user could get in a situation that they can run a cell, but it might use the wrong kernel because discovery hasn't completed yet does not sound like a good user experience to me. UNLESS, it's clearly indicated somehow on screen that discovery is still in progress and when it ends. In other words, the user needs to be able to make a conscious decision to use the kernel that's currently considered the "suggested" one and realize that more may be coming.

**Comment by DonJayamanne** [comment]
**Technical details**
* If we have an exact match for a kernel, then mark that controller as the ONLY preferred controller
* If we don't have an exact match, then either have more than one preferred controller or no preferred controllers.

The change that will be introduced in VS Code is to automatically select the preferred controller and if there are none or more than one, then the quick pick will be displayed as is the case today.

**Comment by TylerLeonhardt** [comment]
Can we have some verification steps?

**Comment by rchiodo** [comment]
Verification steps:

1. Install jupyter
1. Create a custom jupyter [kernelspec](https://queirozf.com/entries/jupyter-kernels-how-to-add-change-remove#add-virtualenv-as-python-kernel) from a virtual environment
2. Start jupyter outside of VS code and create a notebook using this custom kernelspec
3. Save the notebook
4. Open the notebook in VS code
5. Verify that the kernelspec you picked in jupyter is the selected kernel when opening the notebook (eventually, it might take 30 seconds to look through all of your python environments to find a match)
