### ISSUE TITLE
Incorporate Gather extension into eventual Jupyter Powertoys extension

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-jupyter#9755]

**Comment by greazer** [comment]
let's just validate gather is working correctly (make sure it accounts for execution). Then we can consider shipping it with Jupyter itself.

**Comment by rebornix** [comment]
Not sure if we still want to do this.

**Comment by DonJayamanne** [comment]
I agree, we should close this as this means we have to port all of the users from one extension to the other and have a story to communicate the change.
Also `power toys` is a place for testing extension features so they are moved into a seprate extension, but doing the above means we want to test gather because we're not sure its ready to go into a separate extension & that doesn't feel right.

**Comment by DonJayamanne** [comment]
@amunger please feel free to close this issue, I think we shouldl
