### ISSUE TITLE
Cannot connect to a remote kernel

### ISSUE THREAD

**Issue by misha-antonenko** [microsoft/vscode-jupyter#9758]
Issue Type: <b>Bug</b>

On trying to connect to a remote kernel, the extension says something like this:
```
Error 08:31:54: Failed to find & set preferred controllers [i [Error]: https://<an ip address>:8888/
	at /home/mike/.vscode-server/extensions/ms-toolsai.jupyter-2022.3.1000901801/out/extension.js:2:368403
	at processTicksAndRejections (node:internal/process/task_queues:96:5)] {
  category: 'jupyterselfcert'
}
```

Extension version: 2022.3.1000901801
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-96-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id de7537ee-b7ff-4aa6-9ac1-40d3f0a20bb2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: seraph|
|OS|Linux x64 5.4.0-96-generic|
|CPUs|Intel Xeon Processor (Icelake) (14 x 1999)|
|Memory (System)|13.66GB (1.09GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by misha-antonenko** [comment]
The certificate for HTTPS is self-signed.

**Comment by rchiodo** [comment]
Verification steps:

1. Install jupyter into a python environment
2. Follow the directions here in order to generate a certificate (https://jupyter-notebook.readthedocs.io/en/stable/public_server.html#using-ssl-for-encrypted-communication)
3. Run jupyter with the following command `jupyter notebook --certfile=mycert.pem --keyfile mykey.key --no-browser`
It should print a URL with 'https'. Copy this to the clipboard
4. Start VS code
5. Pick the URL as your remote server for jupyter (`Jupyter: Specify Jupyter server for connections`)
6. Run a notebook

You should get a warning like so:
![image](https://user-images.githubusercontent.com/19672699/165642965-854c40f7-a4e9-44e9-979e-c255ebe47a77.png)

If you pick yes, you should be able to run a kernel.

**Comment by IanMatthewHuff** [comment]
Verified. However I did notice that we used to have a functional test for this (I remember writing it eons ago). But that test is commented out and hasn't been replaced. I'm filing an issue to replace it.
