### ISSUE TITLE
After jupyter remote server is shutdown, can no longer open the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-jupyter#9806]
1. Create jupyter server
2. Open VS code
3. Set as the server as the remote connection in VS code
4. Kill server
5. Start interactive window

Get a message like so:

![image](https://user-images.githubusercontent.com/19672699/165578987-7470df9b-82f0-4128-b216-6dfe901d7fc2.png)

**Comment by DonJayamanne** [comment]
@rchiodo I've tried this and I cannot replicate this at all.
I'm getting a different error message.
Please could you provide the output from the console window to show where things fall over `reading split`.

**Comment by rchiodo** [comment]
That one doesn't repro for me anymore either. I was getting a different error this morning. I think it's random based on where the failure occurs.

**Comment by rchiodo** [comment]
See the other bug for what's happening to me now. It's like completely random when it will fail.

**Comment by DonJayamanne** [comment]
Should be fixed in the latest insiders. Closing for verification

**Comment by joyceerhl** [comment]
In web after connecting a remote Jupyter server to the IW, closing the IW, killing the server, and creating a new IW, I get this 
![image](https://user-images.githubusercontent.com/30305945/171922581-f382b611-ce77-4d42-986c-a356fb1fa31f.png)

Minor nits:
- Instead of having 'Failed to fetch' in the detail, could we have the title be 'Failed to connect to the remote Jupyter server.', and the detail be 'Verify the server at <link> is running and reachable.'?
- 'Select a different Kernel' -> 'Select a Different Kernel' to be consistent with the capitalization in the other actions
