### ISSUE TITLE
Suggested/Default controller can be local when connected to remote jupyter server from desktop with local kernels. Should it? 

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode-jupyter#9834]
Assuem we have local kernels & we're connected to a remote jupyter server:
* What's the expected default kernel for IW? This may be different than for a notebook as it chooses the selected Python interpreter.

* What's the expected default kernel for Notebook? 

Filed this issue so we discuss and re-visit these defaults.

**Comment by greazer** [comment]
Ideas:
* Always make the user pick a kernel. Stop trying to guess, at least for notebooks.
* Allow choice of Preferred URI

@rchiodo can you list your ideas here?

**Comment by rchiodo** [comment]
- Stop picking. User always has to select. Kernel is saved so that next time user doesn't have to pick. 
- Allow the user to set a 'preferred' kernel. Get rid of jupyter:local setting and just have a 'kernel' picker at the bottom (or just a command)
- Combine 'remote' and 'local' kernels into interpreter picker from python

**Comment by amunger** [comment]
duplicate
