### ISSUE TITLE
Jupyter Lmod for vscode 

### ISSUE THREAD

**Issue by maxwellyin** [microsoft/vscode-jupyter#9887]
the jupyter has an extension call [lmod](https://github.com/cmd-ntrf/jupyter-lmod), which allows us to load modules while using HPC. I'm used to use vscode to write python script and run jupyter cell. I hope vscode can also add extension similar to the lmod

![image](https://user-images.githubusercontent.com/20868903/166329084-f51e19aa-35d2-4c2f-bd09-c2c44bdf8f2a.png)

**Comment by rchiodo** [comment]
Thanks for the suggestion.

Just so I understand, lmod allows you to preload modules into the kernel?

**Comment by rchiodo** [comment]
Yes I don't think it would work with the way we start kernels. I haven't looked at the source for lmod, but it's likely interacting with jupyter in some way. Our kernels don't even use jupyter most of the time.

But that doesn't mean it's impossible to get it to work.

**Comment by maxwellyin** [comment]
Yeah, lmod is integrated into jupyter notebook. After you choose a module, it will apply to all kernels on the jupyter server. I think this should be something like environmental vibrable, or some commands that can be executed automatically when the kernel starts.

**Comment by DonJayamanne** [comment]
Closing this for now, as we currently do not have any plans on supporting this. 
This presents a number of challenges such as getting this to work consistenly in all instances of Jupyter, local vs remote and considering the fact that this has been only requested by a single user, I'm closing this for now.

If other feel this is important please feel free to up-vote this issue or create a new issue,

**Comment by surak** [comment]
Lmod sets variables on the environment - that's all it does. 

This is not only useful for jupyter - it's pretty common in HPC environments, where one only "loads" the softwares one needs.

This is because HPC centers might have multiple version of the same softwares and libraries installed, and there might be thousands of different softwares installed altogether, each on its own, isolated space.

To avoid having variables like PATH, LD_LIBRARY_PATH and PYTHONPATH comprised of multi-megabyte strings, Lmod was created.

When you "load" a module, it adds this module's variables content into these variables.

For example, on the European Supercomputer JUWELS BOOSTER:

```bash
$ echo $PYTHONPATH

$ module load Python
$ echo $PYTHONPATH
/p/software/juwelsbooster/stages/2023/software/Python/3.10.4-GCCcore-11.3.0/easybuild/python
```

In fact, I can't use python remotely, as I need it set up beforehand with the module load command, as you see above.

**Comment by mmazeika** [comment]
This feature would be very useful.
